### ISSUE TITLE
Using @Throws annotation instead of Java throws syntax

### ISSUE THREAD

**Issue by geralt-encore** [square/kotlinpoet#100]
I was checking out sources and stumbled upon usage of the invalid in Kotlin `throws` syntax. Before fixing it I decided to open the issue since it probably will require api changes. 
So there are several options:

- Completely remove `addException` apis from `FunSpec` since this syntax is not a part of the language and delegate it to `AnnotationSpec`

- Leave current api unchanged and convert supplied `exceptions` to `AnnotationSpec` internally

- Create a new api

What do you think? I would be happy to fix it.

**Comment by swankjesse** [comment]
I think I like #2 best.

**Comment by JakeWharton** [comment]
Since exceptions are extremely uncommon, I lean toward 1. Especially since
the library could be used to generate Kotlin targeting JS or native.

**Comment by burntcookie90** [comment]
I think going with the first option works better, aligns with the actual language spec as well. "Morphing" from a thrown exception to an annotation would be a bit confusing.

**Comment by vanniktech** [comment]
This can be closed, right?
