### ISSUE TITLE
Generated redundant code

### ISSUE THREAD

**Issue by oh-Rin** [square/kotlinpoet#1001]
```Kotlin
FunSpec.builder("checkAllMatch")
   .receiver(CLASS_DEF)
  .addModifiers(KModifier.PRIVATE)
  .addStatement("shapeDrawable.checkAllMatch(this)")
  .build()

TypeSpec.companionObjectBuilder()
  .addProperty(
    PropertySpec.builder("classLoader", ClassLoader::class)
      .initializer("Tracer::class.java.classLoader")
      .mutable()
      .build()
  ).build()
```

![image](https://user-images.githubusercontent.com/58068445/96283469-d7245080-100e-11eb-95b1-c9b1db4c2e04.png)

**Comment by JakeWharton** [comment]
This is by design and is intended to support explicit API mode.

**Comment by oh-Rin** [comment]
> This is by design and is intended to support explicit API mode.

Okay, but it doesn't seem to be mandatory in previous versions? Can I disable it, or ignore the warning?

**Comment by Egorand** [comment]
Generating explicit API mode-compatible code is a new feature that shipped in version 1.7.0. I would recommend disabling code style checks for generated code, or reverting back to 1.6.0.

**Comment by oh-Rin** [comment]
@Egorand How to individually specify the generated code to disable checking?

**Comment by ZacSweers** [comment]
That depends on your build system and/or IDE (settings), you'll need to figure out for yourself as it's tangential to kotlinpoet

**Comment by daviddenton** [comment]
This seems to be a little bit of a far reaching change, so it would be great to have the option to turn off the explicit API mode if possible. Not every piece of code generated by Poet will be continually regenerated by a build system (and hence would never normally be modified by hand). In these scenarios, the redundant code will just be an annoyance.

By way of example, we're using Poet in http4k to generate one-off templates for people to kickstart their projects, or generate server and client stubs from OpenApi specs - this type of code isn't in need of explicit API mode.

**Comment by Egorand** [comment]
KotlinPoet is perhaps not a good fit for generating code that is supposed to live in `src/main/kotlin`, but it works great for code that lives in `build/generated/sources`. The library is opinionated in many ways which ultimately shouldn't matter if generated code is only used in its compiled form. Introducing API to tweak every single aspect of codegen increases maintenance burden and doesn't really win us anything in terms of code correctness - which is the main priority. If it's essential for your use case to generate code in a specific format then our recommendation is to post-process KotlinPoet's output as desired.

**Comment by arkadiuszpalka** [comment]
It would be great to introduce kind of flag or different implementation of CodeWriter which will omit `public` modifier. Current CodeWriter could be use by default

**Comment by ZacSweers** [comment]
No, it would be error prone and often wrong
