### ISSUE TITLE
Create annotations for @get:

### ISSUE THREAD

**Issue by oberstrike** [square/kotlinpoet#1015]
Hello,

How can I create an annotation that is specified on the getter of a property?

Example:

```
interface ExampleInterface{
  @get:Schema(required = false, maxLength = 24, pattern = "^[a-zA-Z0-9]*\$")
    override var id: String?
}
```

Problems:
It's a property of a interface, so 
`FunSpec.getterBuiler().addAnnotation(annotation)... `
doesn't work, cause it's abstract and can't have a defined getter.

Thank you!

**Comment by Egorand** [comment]
Are you looking for [`AnnotationSpec.Builder.useSiteTarget()`](https://square.github.io/kotlinpoet/1.x/kotlinpoet/com.squareup.kotlinpoet/-annotation-spec/-builder/use-site-target.html)?

Also, [Stackoverflow](https://stackoverflow.com/questions/tagged/kotlinpoet) is a better place for usage questions, this issue tracker is for bug reports and feature requests.

**Comment by oberstrike** [comment]
Alright, thank you, I will ask there next time!
