### ISSUE TITLE
Delegated constructor call in external class is not allowed

### ISSUE THREAD

**Issue by NiematojakTomasz** [square/kotlinpoet#1016]
Sample of invalid generated code:
```
public open abstract external class AbortSignal : EventTarget() {
  public val aborted: Boolean?
}
```

**Comment by Egorand** [comment]
It seems that Kotlin doesn't even allow `external` classes, I get a `Modifier 'external' is not applicable to 'class'` compiler error on the following declaration:
```kotlin
external class Foo
```

**Comment by NiematojakTomasz** [comment]
@Egorand It does allow. org.w3c.dom package of kotlin-stdlib-js is full of it.
For example:
```
public external abstract class HTMLElement : Element, GlobalEventHandlers, DocumentAndElementEventHandlers, ElementContentEditable, ElementCSSInlineStyle {
```

What error are you getting?

**Comment by Egorand** [comment]
Interesting! The error, as mentioned, is `Modifier 'external' is not applicable to 'class'`.

Looks like JVM vs JS compiler behavior is different for `external`, I don't get the same compiler error with JS: https://pl.kotl.in/eW5KMwFJY
