### ISSUE TITLE
Integrate kotlin ABI validator

### ISSUE THREAD

**Issue by ZacSweers** [square/kotlinpoet#1022]
We've been burned by this once or twice in the past, probably worth a look

https://github.com/Kotlin/binary-compatibility-validator

**Comment by Egorand** [comment]
Yeah, looks good. Wanna set it up? We used Japicmp in Okio while migrating from 1.x to 2.0 but we only cared about Java binary compatibility.

**Comment by JakeWharton** [comment]
May want to consider Metalava instead which makes an effort to _also_ ensure source compatibility and can work for targets other than the JVM.

**Comment by ZacSweers** [comment]
Is Metalava publicly consumable? The only project I know of using it is androidx

**Comment by JakeWharton** [comment]
android-ktx used it when it was on GitHub. It's just a project that poops out a jar like any other. Wire it up to a JavaExec and you're good to go.

**Comment by Egorand** [comment]
@ZacSweers this has already been done, right?

**Comment by ZacSweers** [comment]
Yup!
