### ISSUE TITLE
 ParameterSpec，file is converted to 'file'

### ISSUE THREAD

**Issue by caizemingg** [square/kotlinpoet#1033]
code：  
constructorBuilder.addParameter(
                        ParameterSpec.builder("file", typeName).defaultValue(initializer)
                            .build()
                    )

reslut ：
public data class ShareConfig(
  \`file\`: Boolean = false
)

What I want is：
 public data class ShareConfig(
  file: Boolean = false
)
I don't want file to be turned into 'file'.

**Comment by ZacSweers** [comment]
Kotlinpoet defensively escapes all keywords. It doesn't affect the functionality of your generated code
