### ISSUE TITLE
Using reserved keyword for parameter generates an invalid data class

### ISSUE THREAD

**Issue by ansman** [square/kotlinpoet#1035]
I'm trying to generate a data class that contains a property named `data`:
```kotlin
val parameter = ParameterSpec.builder("data", STRING).build()

TypeSpec.classBuilder("Example")
  .addModifiers(KModifier.DATA)
  .primaryConstructor(FunSpec.constructorBuilder()
    .addParameter(parameter)
    .build())
  .addProperty(PropertySpec.builder(parameter.name, STRING)
    .initializer("%N", parameter)
    .build()
  .build()
```
The output does not compile however:
```kotlin
public data class Example(
  `data`: String
) {
  public val data: String = `data`
}
```

**Comment by Egorand** [comment]
Any specific reason you'd want to use `%N` in the initializer? If I change that part to `initializer(parameter.name)` it all works fine.

**Comment by ansman** [comment]
I just figured it was better to not pass unknown input as as format string

**Comment by Egorand** [comment]
I just retested this and the output I see is the following, which looks fine to me:

```kotlin
public data class Example(
  public val `data`: kotlin.String,
)
```

I added a regression test (#1250) and will close this issue, but please let me know if there's anything I'm missing or if there's anything else to be done here.
