### ISSUE TITLE
ReflectiveClassInspector: Use custom Classloader

### ISSUE THREAD

**Issue by oberstrike** [square/kotlinpoet#1036]
Problem:

I am testing my annotation processor and a new classloader-object is being created. Now I want to use the ReflectiveClassInspector to analyse the newly generated classes. However, in the function `ReflectiveClassInspector#lookupClass` the expression `Class.forName(className.reflectionName())` is used. 

Possible solution suggestion: 
The function:  `CLass#forName(name: String, initialize: boolean, loader: ClassLoader)`.

**Comment by ZacSweers** [comment]
Want to send a proposal PR?

**Comment by oberstrike** [comment]
Yes, I'm working on it, I'm currently working on writing the tests.

**Comment by oberstrike** [comment]
See #1037
