### ISSUE TITLE
ImmutableKmProperty.toMutable() doesn't copy fieldSignature

### ISSUE THREAD

**Issue by forsenonlhaimaisentito** [square/kotlinpoet#1044]
Hi, I've noticed that while `KmProperty.toImmutable()` does copy `fieldSignature`, `ImmutableKmProperty.toMutable()` does not.

Sample code:

```kotlin
fun main() {
    val original = KmProperty(0, "test", 0, 0).apply {
        // Required fields
        returnType = KmType(0).apply { classifier = KmClassifier.Class("test/Test") }

        // Set fieldSignature
        fieldSignature = JvmFieldSignature("test", "Ltest/Test;")
    }
    val immutable = original.toImmutable()

    println(original.fieldSignature == immutable.fieldSignature)  // true

    println(original.fieldSignature == immutable.toMutable().fieldSignature)  // false
}
```

Is this intended? At the moment I'm using a wrapper that copies the field in the toMutable result, but it would be nice to have lossless conversions between mutable/immutable.

**Comment by ZacSweers** [comment]
Not intended! Want to send a PR?

**Comment by forsenonlhaimaisentito** [comment]
Sure, what about the other fields that don't get copied by toMutable, is the conversion supposed to be completely lossless?

**Comment by ZacSweers** [comment]
It's been awhile since I looked at the code but I would expect it to be lossless
