### ISSUE TITLE
Consider adding Filer convenience methods back

### ISSUE THREAD

**Issue by JakeWharton** [square/kotlinpoet#105]
kapt compiles kt files generated from processors per comments on https://github.com/square/kotlinpoet/pull/93

**Comment by hotchemi** [comment]
sorry I commented to a wrong thread 🙇 https://github.com/square/kotlinpoet/pull/93#issuecomment-315720172

**Comment by hotchemi** [comment]
I investigated a bit so let me share about it here.

- kapt3 actually supports .kt file generation and the destination is supposed to be `generated/source/kaptKotlin/$sourceSetName`(obtained by `processingEnv.options["kapt.kotlin.generated"]`), not `generated/source/apt/$sourceSetName`
  - [KT-17883 Enhancement request - support annotation processing with generation of Kotlin source (rather than Java source)](https://youtrack.jetbrains.com/issue/KT-17883)
  - [Kapt3: Support Kotlin sources generation (KT-14070)](https://github.com/jetbrains/kotlin/commit/4a2e40994848883cc7007485dc87d1ab449e45d2)

**Comment by JorgeCastilloPrz** [comment]
Do you have any clue about how to write KotlinPoet generated classes to filer without using the not yet available KotlinPoet api method `writeTo(filer)` for it @hotchemi?

**Comment by JakeWharton** [comment]
Call toString(), write that as your file contents.

**Comment by hotchemi** [comment]
@JorgeCastilloPrz might be an off topic for this issues but right now we do as below and it works...the reason of `replace("kaptKotlin", "kapt")` is https://youtrack.jetbrains.com/issue/KT-19097. Hope it will help you.
https://github.com/hotchemi/PermissionsDispatcher/blob/master/processor/src/main/kotlin/permissions/dispatcher/processor/PermissionsProcessor.kt#L69

**Comment by JorgeCastilloPrz** [comment]
Well it feels also helpful for what is going on on this issue (to me). So might be not so offtopic! :). It's quite interesting, so is ` generated/source/kapt/$sourceSetName` dir already auto indexed to avoid compilation errors without the `idea plugin` build.gradle code to force indexing? Or that code still needed on `build.gradle`?

Thanks for your help.

**Comment by JorgeCastilloPrz** [comment]
Im gonna add here a link to a repo I'm contributing to where we are also generating Kotlin files and compile time using KotlinPoet API and being able to referentiate those files from production code with no compile time errors: https://github.com/kategory/implicits-processor

**Comment by codeprogression** [comment]
This is what worked for me (inspired by the [kotlin-examples processor](https://github.com/JetBrains/kotlin-examples/blob/master/gradle/kotlin-code-generation/annotation-processor/src/main/java/TestAnnotationProcessor.kt)).

In the process method...

Get  the target generated directory for kapt:
``` kotlin
val kaptKotlinGeneratedDir = processingEnv.options["kapt.kotlin.generated"] ?:
  run {
      processingEnv.messager.printMessage(
        ERROR, 
        "Can't find the target directory for generated Kotlin files."
      )
      return false
  }
```

Create your file object:
``` kotlin
val kotlinFile = KotlinFile.builder("com.example", "KotlinClass.kt")
  .addType(TypeSpec.classBuilder("KotlinClass").build())
  .build()
```

Write the file:
``` kotlin
File(
  "$kaptKotlinGeneratedDir/${kotlinFile.packageName.replace(".", "/")}", 
  kotlinFile.fileName
).apply {
  parentFile.mkdirs()
  writeText(kotlinFile.toString())
}
```

**Comment by ZacSweers** [comment]
Definitely want this now that Kapt is adding support for gradle's incremental kapt support and using the same filer APIs

https://github.com/JetBrains/kotlin/pull/2179

https://github.com/JetBrains/kotlin/pull/2179/files#diff-f5958ff916f88658e65a723fb591467dR142

I can take a swing at this this weekend

**Comment by Egorand** [comment]
Awesome, please do!
