### ISSUE TITLE
backticks in package names

### ISSUE THREAD

**Issue by dariuszkuc** [square/kotlinpoet#1055]
Hello 👋 

Unsure if it was intentional but when [upgrading from version `1.6.0` to `1.7.2`](https://github.com/ExpediaGroup/graphql-kotlin/pull/1092) there was a change in imports logic that now wraps some keywords (like `annotation`) in backticks (`). It is still a valid code but is just weird looking.

old behavior when using any Jackson annotations

```kotlin
import com.fasterxml.jackson.annotation.JsonEnumDefaultValue
import com.fasterxml.jackson.annotation.JsonProperty

enum class CustomEnum {
  ONE,

  @JsonProperty("two")
  TWO,

  @JsonEnumDefaultValue
  __UNKNOWN_VALUE
}
```

new behavior

```kotlin
import com.fasterxml.jackson.`annotation`.JsonEnumDefaultValue
import com.fasterxml.jackson.`annotation`.JsonProperty

public enum class CustomEnum {
  ONE,
  @JsonProperty("two")
  TWO,
  @JsonEnumDefaultValue
  __UNKNOWN_VALUE,
}
```

**Comment by ZacSweers** [comment]
This is working as intended and highlighted in the changelog for 1.7.0:

> New: Escape soft and modifier keywords, in addition to hard keywords.
