### ISSUE TITLE
KotlinPoet Doc page error

### ISSUE THREAD

**Issue by aniketbhoite** [square/kotlinpoet#1062]
https://square.github.io/kotlinpoet/1.x/interop/kotlinx-metadata/classinspectors/reflec/com.squareup.kotlinpoet.classinspector.reflective/index.html

**Comment by ZacSweers** [comment]
We consolidated the artifact into a single interop artifact, that one no longer exists. Is it linked from somewhere else that we need to fix?

**Comment by aniketbhoite** [comment]
Yes, Under the API dropdown section
https://square.github.io/kotlinpoet/ 

On a different topic, I am trying to learn Annotation processer, KotlinPoet, and JavaX Elements for one project. Having a hard time finding documentation or tutorials(examples) especially for JavaX elements, can you help regarding this?

**Comment by ZacSweers** [comment]
Thanks we'll fix it. We have extensive examples in the README and on the doc site. There are also examples in the community like Moshi. This issue tracker is for bugs and feature requests though, but you're welcome to try posting on the repo's [discussions page](https://github.com/square/kotlinpoet/discussions/categories/q-a) or stackoverflow with specific issues. When you do, it might be helpful to share what you have found so far and specific examples of what you're trying to do.

**Comment by ZacSweers** [comment]
@Egorand looks like the new docs deploy action maybe didn't work?

**Comment by Egorand** [comment]
The deploy action [did complete](https://github.com/square/kotlinpoet/runs/2229249707?check_suite_focus=true), but I'm seeing a few warnings in the logs:

```
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - interop-kotlinx-metadata-specs.md 
WARNING -  A relative path to '1.x/interop/kotlinx-metadata/classinspectors/elements/com.squareup.kotlinpoet.classinspector.elements/index.html' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to '1.x/interop/kotlinx-metadata/classinspectors/reflec/com.squareup.kotlinpoet.classinspector.reflective/index.html' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to '1.x/interop/kotlinx-metadata/core/com.squareup.kotlinpoet.metadata/index.html' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to '1.x/interop/kotlinx-metadata/specs/com.squareup.kotlinpoet.metadata.specs/index.html' is included in the 'nav' configuration, which is not found in the documentation files 
```

Maybe we forgot to update `mkdocs.yml` to point to the correct doc pages after the artifacts were merged?
