### ISSUE TITLE
Provide better FileSpec API for writing into an OutputStream

### ISSUE THREAD

**Issue by Egorand** [square/kotlinpoet#1069]
KSP's [`CodeGenerator.createNewFile()`](https://github.com/google/ksp/blob/8a8d16855c23f3cc24d05218b16f6c6e46fdbbd8/api/src/main/kotlin/com/google/devtools/ksp/processing/CodeGenerator.kt#L61) returns an `OutputStream`. The best way to write a `FileSpec` into it seems to be the following:

```kotlin
val fileSpec = ...
val file = CodeGenerator.createNewFile(...)
val writer = OutputStreamWriter(file)
writer.use(fileSpec::writeTo)
```

This isn't very ergonomic, as this overload of `writeTo` accepts an `Appendable`, so it doesn't know how to close it - we have to do it ourselves via `use`. It's too easy to make the mistake of just calling `fileSpec.writeTo(writer)` and wonder why nothing is being generated.

Should we provide API for writing into an `OutputStream`, or `OutputStreamWriter`, or `Writer`? Or am I missing a better API that already exists?

Also not sure whether KSP's API has been finalized, so we might hold off until that happens.

**Comment by JakeWharton** [comment]
I wouldn't close an OutputStream if we supported it.

**Comment by Egorand** [comment]
Yeah, fair enough. Still it's annoying that the simplest approach in this case is incorrect. Do you think KSP should be doing something different here, i.e. returning something that's not `Closeable` to avoid confusion?

**Comment by Egorand** [comment]
Obsolete now that @ZacSweers added KSP-specific `writeTo` API:

https://github.com/square/kotlinpoet/blob/master/interop/ksp/src/main/kotlin/com/squareup/kotlinpoet/ksp/originatingKSFiles.kt#L125-L144
