### ISSUE TITLE
Plugin version (1.4.32) is not the same as library version (1.4.10) 

### ISSUE THREAD

**Issue by luck-apple** [square/kotlinpoet#1071]
ext.kotlin_version = "1.4.32"

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

    implementation('com.squareup:kotlinpoet:1.7.2')
    implementation("com.google.auto.service:auto-service-annotations:1.0-rc7")
    kapt "com.google.auto.service:auto-service:1.0-rc7"
}

**Comment by ZacSweers** [comment]
Not clear what the issue is, please add more details next time

**Comment by Egorand** [comment]
1.7 is indeed built against Kotlin 1.4.10 (see the [changelog](https://github.com/square/kotlinpoet/blob/master/docs/changelog.md#version-170)), upgrade to `1.8.0` to get Kotlin 1.4.32.

**Comment by luck-apple** [comment]
> 1.7 is indeed built against Kotlin 1.4.10 (see the [changelog](https://github.com/square/kotlinpoet/blob/master/docs/changelog.md#version-170)), upgrade to `1.8.0` to get Kotlin 1.4.32.

i update kotlinpoet to 1.8.0
implementation('com.squareup:kotlinpoet:1.8.0')

There's still a warning on line: implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
warning info: Plugin version (1.4.32) is not the same as library version (1.4.31)

**Comment by Egorand** [comment]
Ah, sorry, I lied, 1.8.0 shipped with Kotlin 1.4.31. Anyway, it's just a warning, likely the difference between .32 and .31 is nothing to worry about. We won't be shipping a dot release just for that patch version bump.

**Comment by luck-apple** [comment]
> Ah, sorry, I lied, 1.8.0 shipped with Kotlin 1.4.31. Anyway, it's just a warning, likely the difference between .32 and .31 is nothing to worry about. We won't be shipping a dot release just for that patch version bump.

thank you
