### ISSUE TITLE
License file has no date or license owner

### ISSUE THREAD

**Issue by ianhanniballake** [square/kotlinpoet#1077]
[LICENSE.txt](https://github.com/square/kotlinpoet/blob/master/LICENSE.txt) has:

```
   Copyright [yyyy] [name of copyright owner]
```

This should be filled in with the correct copyright year and owner.

**Comment by JakeWharton** [comment]
This is the portion of the license that provides a template for you to use on copyrighted content which is licensed. Our README and source files apply the template with the placeholders filled out. The license file is not meant to be edited.

**Comment by ianhanniballake** [comment]
The License in the released artifacts has the same - no owner. Is that also expected?

**Comment by JakeWharton** [comment]
I don't believe we distribute a copy of the license, but if it's the full license file then yes it should appear exactly the same as the one we have checked in with the placeholders in place. They are part of the license. The only reference our released artifact should have is to the canonical one on the Apache website via the `pom.xml`: https://search.maven.org/artifact/com.squareup/kotlinpoet/1.8.0/jar
