### ISSUE TITLE
KotlinPoet generates redundant extra line

### ISSUE THREAD

**Issue by mars885** [square/kotlinpoet#1085]
For example, this code:
```kotlin
println(
  FileSpec.builder("", "Test")
    .addType(TypeSpec.classBuilder("Test").build())
    .build()
    .toString()
)
```
generates the following:
```kotlin
public class Test


```

As you can see above, the file has extra new line at the end. Is this by design?

**Comment by JakeWharton** [comment]
Change to using print not println. KotlinPoet emits a trailing newline, and then you are adding an additional one with println.

**Comment by mars885** [comment]
`println` was just used to provide an example, but the underlyfing issue still exists. 

> KotlinPoet emits a trailing newline

All my tests have to padded with this newline as well. In comparison, JavaPoet does not emit trailing newline, as far as I remember. This problem is easy to fix in post-processing (like a simple `trim()` method call), but still feels kinda weird that KotlinPoet does it anyway.

**Comment by JakeWharton** [comment]
If you're referring to the single trailing newline then it is intentional. The Kotlin Android style guide has it as optional with no recommendation for or against. It's inclusion is useful for diffs, however, as it prevents the last line from being part of the diff when new content is appended.
