### ISSUE TITLE
Empty primary constructor not generated properly

### ISSUE THREAD

**Issue by pavlospt** [square/kotlinpoet#1093]
Hello! 

I am using Kotlinpoet v1.8.0 and I am trying to generate an empty primary constructor for a class `TypeSpec`.

```kotlin
builderSpec.primaryConstructor(FunSpec.constructorBuilder().build())
```

The expected result here would be something like:

```kotlin
class Foo() { ... }
```

whereas the actual result is:

```kotlin
class Foo { ... }
```

This breaks the functionality when we are trying to add a second constructor that uses `callThisConstructor()` since there is no primary empty constructor to delegate to.

**Comment by Egorand** [comment]
Yeah, looks like we're omitting empty primary constructors. I think we should honour `builderSpec.primaryConstructor` and generate the constructor, even if it's empty. Wanna send us a PR?

**Comment by pavlospt** [comment]
@Egorand of course! Will prepare one tomorrow! :)
