### ISSUE TITLE
Redundund public modifier

### ISSUE THREAD

**Issue by pe4enko** [square/kotlinpoet#1098]
When generating classes using kotlin poet 1.6.0, the default identifier "public" was not added, but now in version 1.8.0 it is always added. Because of this, all tests were broken and the generated code was less readable due to excessive use of the "public" modifier. Is it possible to somehow disable the generation of the "public" modifier where it is already implied by default?

**Comment by Egorand** [comment]
This is by design, we want the code generated by kotlinpoet to be compatible with explicit API mode by default. There's no way to disable this behavior.
