### ISSUE TITLE
Add .editorconfig

### ISSUE THREAD

**Issue by Egorand** [square/kotlinpoet#1104]
Square's code style enforces 2-space indents, contrary to many other official and unofficial code styles. To make it easier for contributors to follow the correct code style, we can add an `.editorconfig` file to the root of the repo. IDEs such as Intellij IDEA should pick it up and apply the settings.

**Comment by anandwana001** [comment]
Can I send a PR for this issue?

**Comment by Egorand** [comment]
Go for it!
