### ISSUE TITLE
TypeSpec looses information about type package

### ISSUE THREAD

**Issue by tntclaus** [square/kotlinpoet#1110]
The problem is when you create type spec from `ClassName`, information about package gets lost and when one later may need to know which package the type belongs to it's not possible.

Why not to have `TypeName` property inside `TypeSpec`? And why not to make `TypeSpec` open class so we could extend it?

**Comment by Egorand** [comment]
Package is not a property of a type, it's a property of a file, hence you can obtain it from a `FileSpec`, but not a `TypeSpec`.

If you want to attach arbitrary data to a `TypeSpec` though, you can - just add it as a tag:

```kotlin
val typeSpec = TypeSpec.classBuilder(className)
  .tag(ClassName::class, className)
  .build()
println(typeSpec.tag(ClassName::class))
```

> why not to make TypeSpec open class so we could extend it?

What's the use case for it?

**Comment by JakeWharton** [comment]
Another way of thinking about it is that the `TypeSpec` factory which takes a `ClassName` does so as a convenience rather than you having to call `.simpleName` to get just the type name.

**Comment by tntclaus** [comment]
I disagree that package is property of file only: Type inherits package from file. We can have 2 types with same name which are essentially different as they belong to different packages. E.g. #387 , which was fixed, but root cause wasn't.

How one is supposed to know which TypeSpec describes which type? Am I supposed to always transfer tuples e.g. `Pair<TypePackage, TypeSpec>`?  Or should I prepare `FileSpec` service beforehand and make it somehow available for other parts of code so they could ask of which package is particular `TypeSpec` object? 

I definitely know very few things about kotlinpoet API and apt so if there is already simple well-known solution to do this (or knowledge there are better approaches) I would be glad if you tell me.

>  > why not to make TypeSpec open class so we could extend it?
> 
> What's the use case for it?

The case is above. More broadly: I generate kotlin files and after that I wan't to reuse all `TypeSpec` objects to generate TypeScript interfaces. Knowledge of which package Type belongs to will help to greatly reduce complexity of the code.

**Comment by Egorand** [comment]
KotlinPoet makes a distinction between "names" and "specs": e.g. a `ClassName` does indeed have a `packageName` property as it represents a fully-qualified class name, however a `TypeSpec` only keeps data needed to render a type, and unless added to a `FileSpec`, it doesn't know which package it belongs to. The convenience of this is that you can generate a single `TypeSpec` and add it to multiple `FileSpec`s with different packages, without needing to modify the original `TypeSpec`.

Tags should work, but I also wanted to suggest changing your code to operate on `FileSpec`s instead of `TypeSpec`s if it requires package name info, e.g.:

```kotlin
val files = listOf<FileSpec>()
for (file in files) {
  val packageName = file.packageName
  val typeNames = file.members
    .filterIsInstance<TypeSpec>()
    // Ignore anonymous objects.
    .mapNotNull(TypeSpec::name)
  for (typeName in typeNames) {
    val className = ClassName(packageName, typeName)
  }
}
```

**Comment by tntclaus** [comment]
> The convenience of this is that you can generate a single TypeSpec and add it to multiple FileSpec

I definitely don't know something. How often and at what circumstances one may need to generate 2 or more exactly same `TypeSpec`s?

> I also wanted to suggest changing your code to operate on FileSpecs instead of TypeSpec

@Egorand thank you, I thought about `FileSpec` too. My current flow is: get `TypeSpec`, iterate props: get return type `TypeName`, check it's parametrized, retrieve each type spec, goto start until there are no types with props remaining.  If `FileSpec` can be seamlessly replaced to TypeSpec, guaranteed that for ClassName we can get `FileSpec` with single `TypeSpec` this will do the job.

**Comment by Egorand** [comment]
> How often and at what circumstances one may need to generate 2 or more exactly same TypeSpecs?

I don't have a specific use case in mind, but decoupling `TypeSpec`s from the concepts of files and packages makes it is possible.

I'm gonna close this issue as it doesn't look like there's anything for us to do, and there are a couple of options that should work for your use case.

**Comment by JakeWharton** [comment]
`TypeSpec` can also nest arbitrarily in others. For example, if you are generating protos you can produce a `TypeSpec` from a message and then based on the options of the proto file either generate it as top-level or nest it within a class that holds all messages from the proto file.
