### ISSUE TITLE
Add Val + Var to ParameterSpec

### ISSUE THREAD

**Issue by agrosner** [square/kotlinpoet#113]
Allow us to add parameters to `primaryConstructor()` which add `val`/`var` so we don't have to explicitly add each property on the type itself, or a simple method on the `PropertySpec.Builder` to specify it goes into primary constructor.

Something like:
```kotlin
addParameter(ParameterSpec.valBuilder(name, valueType)
                                                        .defaultValue(defaultValue) // vals

addParameter(ParameterSpec.varBuilder(name, valueType)
                                                        .defaultValue(defaultValue) // vars
``` 

Or 
```kotlin
.addProperty(PropertySpec.builder("name", String::class)
            .initializer("name")
            .inPrimaryConstructor()
            .build())
```

So our outputted code is more concise.

**Comment by JakeWharton** [comment]
This is already supported automatically when you create a property and constructor argument which match. See this test: https://github.com/square/kotlinpoet/blob/4a0bbc83af359076432c55275a1a9e7366120e48/src/test/java/com/squareup/kotlinpoet/KotlinPoetTest.kt#L95-L127.

**Comment by agrosner** [comment]
ah thank you! I think the example on the main page is out of date, it shows them as defined separately.

**Comment by JakeWharton** [comment]
Probably. We haven't released a version that does this collapsing, but we
should in the next few days.

We'll update the sample when 0.3 is out.

**Comment by agrosner** [comment]
ok sounds good. Thank you.

**Comment by JakeWharton** [comment]
Released and updated
