### ISSUE TITLE
Support copying a ParameterizedTypeName with different type arguments

### ISSUE THREAD

**Issue by ansman** [square/kotlinpoet#1139]
I need to create a wildcard projected type name and currently there is no way to do so using public APIs. I suggest a `copy` function is added which has all of the parameters of the class.

**Comment by Egorand** [comment]
> I need to create a wildcard projected type name and currently there is no way to do so using public APIs.

Do you mean e.g. `val listOfAny = List::class.asClassName().parameterizedBy(STAR)`? Not sure how a `copy` function would solve this. Can you please include a code example?

**Comment by ansman** [comment]
So my use case is that I get a `TypeName` from the caller and I need to create a version of that typename that has wildcards. In some cases I am not the creator of the type names so I cannot easily create a new version with different type arguments.
