### ISSUE TITLE
1.10.0 release notes prep

### ISSUE THREAD

**Issue by ZacSweers** [square/kotlinpoet#1156]
Working notes for next release

* **New:** Add a new [KSP](https://github.com/google/ksp) interop artifact. See <doc link> docs for more details
* **New:** Allow copying a `ParameterizedTypeName` with new type arguments via new `copy()` overload.
* kotlinx-metadata artifacts have been consolidated to a single `com.squareup:kotlinpoet-metadata` maven artifact. The previous `kotlinpoet-metadata-*` subartifacts are no longer published.
* **New:** `TypeNameAliasTag ` has been moved to KotlinPoet's main artifact under `TypeAliasTag`, for reuse with KSP interop.
* **Fix:** Fix self-referencing type variables in metadata parsing.
* **Fix:** Use delicate APIs rather than noisy logging ones when converting annotation mirrors in `AnnotationSpec.get`.
* **Fix:** Update error message when metadata cannot be read to a more actionable one.
* **Fix:** Avoid escaping already escaped strings.
* Add docs about `kotlin-reflect` usage.
* Avoid using kotlin-reflect for looking up `Unit` types where possible.
* Test all the way up to JDK 17.
* Update Kotlin to `1.5.31`

Thanks to [@martinbonnin](https://github.com/martinbonnin), [@idanakav](https://github.com/idanakav), [@goooler](https://github.com/goooler), and [@anandwana001](https://github.com/anandwana001) for contributing to this release.

**Comment by Egorand** [comment]
> See docs for more details

nit: add a link to docs?

**Comment by ZacSweers** [comment]
Left as a placeholder as the doc isn't published yet
