### ISSUE TITLE
primaryConstructor of TypeSpec created from KmClass is always null

### ISSUE THREAD

**Issue by Legion2** [square/kotlinpoet#1166]
If creating `TypeSpec` from `KmClass`, then `TypeSpec.primaryConstructor` is null even if there is a primary constructor:

```kotlin
import com.squareup.kotlinpoet.metadata.KotlinPoetMetadataPreview
import com.squareup.kotlinpoet.metadata.isPrimary
import com.squareup.kotlinpoet.metadata.specs.toTypeSpec
import com.squareup.kotlinpoet.metadata.toKmClass
import kotlin.test.Test
import kotlin.test.assertTrue

class Test {
    @OptIn(KotlinPoetMetadataPreview::class)
    @Test
    fun test() {
        val kmClass = Foo::class.toKmClass()
        val kmClassPrimaryConstructor = kmClass.constructors.find { it.isPrimary }
        val typeSpecPrimaryConstructor = kmClass.toTypeSpec(null).primaryConstructor

        assertTrue { kmClassPrimaryConstructor != null } // passes
        assertTrue { typeSpecPrimaryConstructor != null } // failes
    }

    class Foo(name: String)
}
```

Versions:
kotlin: 1.5.30
kotlinpoet: 1.10.1
kotlinpoet-metadata: 1.10.1

**Comment by ZacSweers** [comment]
You need to give it a ClassInspector instance, not null. It can only resolve partial information without one

**Comment by Legion2** [comment]
OK, thanks for this information. I didn't find any documentation why this ClassInspector instance is needed and where and how to get an instance. The documentation should be updated to include an example on how to create a ClassInspector and maybe add an extension function:

`fun ProcessingEnvironment.createClassInspector() = ElementsClassInspector.create(elementUtils, typeUtils)`

and reference it in the documentation.

**Comment by ZacSweers** [comment]
It's explicitly called out on the docs for metadata interop: https://square.github.io/kotlinpoet/interop-kotlinx-metadata/#source-representation

**Comment by Legion2** [comment]
Did not see that, only looked at the dokka documentation, which is available in the IDE.
