### ISSUE TITLE
name and ordinal enum constant names generates non-compiling code

### ISSUE THREAD

**Issue by oldergod** [square/kotlinpoet#1183]
```kotlin
    val byeNat = TypeSpec.enumBuilder("ByeNat")
      .addEnumConstant("name")
      .addEnumConstant("ordinal")
      .build()
```
This will fail because Kotlin enums already have an `name` and an `ordinal` fields.

**Comment by Egorand** [comment]
KotlinPoet is trying to avoid being a compiler as much as possible, it doesn't guarantee that the code it produces is compilable. In this case I think we shouldn't validate explicitly, your code should probably filter out those names.

**Comment by oldergod** [comment]
Is there a warning that could be printed or something? I don't know if KP has a logger.

**Comment by Egorand** [comment]
To print the warning we'd need to encode the checks for `name` and `ordinal` as disallowed enum constant names, and this is what I'd like to avoid, cause this is what the compiler should do.

**Comment by Egorand** [comment]
I changed my mind: #1184
