### ISSUE TITLE
Wny Kotlinpoet not support to add comment for propertySpec or typeSpec? 

### ISSUE THREAD

**Issue by JoshuaQYH** [square/kotlinpoet#1190]
I found the fileSpec and funcSpec are suppoted. 
api: 
com.squareup.kotlinpoet.FileSpec.Builder#addComment
com.squareup.kotlinpoet.FunSpec.Builder#addComment

**Comment by JoshuaQYH** [comment]
I think it is not hard to implement such a mini-feature for propertySpec or typeSpec . Is there any reason for it?

**Comment by JakeWharton** [comment]
Are you looking for `addKdoc`?

**Comment by JoshuaQYH** [comment]
> Are you looking for `addKdoc`?

Oh, thx. It's kind of you that`addKdoc` really can meet some of my requirements.  But I found it cannot support to add comment like `val field: Int = 0 // comment`. Is it not recommended for generating code like this?

**Comment by JakeWharton** [comment]
We do not support that style of comment on class properties, no.
