### ISSUE TITLE
How to generate stuff like ClassName::class.java 

### ISSUE THREAD

**Issue by C7ABT** [square/kotlinpoet#1198]
Assume that we have a class name in String form, say TestClass. How to generate `TestClass::class.java` using poet? Code generated is expected to be a plain Name, not String with "" like `addStatement("return %S", "TestClass::class.java")`

**Comment by Egorand** [comment]
See [%T for Types](https://square.github.io/kotlinpoet/#t-for-types).

If that doesn't help, please ask a follow up question on [Discussions](https://github.com/square/kotlinpoet/discussions) or [Stackoverflow](https://stackoverflow.com/questions/tagged/kotlinpoet), we only use the issue tracker for bug reports and feature requests.
