### ISSUE TITLE
Adding `KModifier` for interface type parameter.

### ISSUE THREAD

**Issue by vnermolaev** [square/kotlinpoet#1206]
Hi!

Somewhere in the code, I have interfaces:
 
```kotlin
interface Base

interface BaseProvider {
    fun list(): List<out Base>
}
```

now using kotlin poet, I'd like to create an implementation of `BaseProvider`, but I am facing difficulties trying to specify the return type of `list()`, consider the following fragment:
```kotlin
List::class.parameterizedBy(
    Base::class  // <- how do I add a modifier KModifier.OUT 
)
```

One thing I tried is to "abuse" `TypeVariableName` as follows
```kotlin
List::class.asClassName().parameterizedBy(
    TypeVariableName(T::class.qualifiedName.toString(), KModifier.OUT)
)
```
but in this case, the modifier is stripped and the results of the two snippets are equivalent.

Is there a mechanism or a workaround to variance in such cases?

**Comment by ZacSweers** [comment]
Please use the discussions section for questions, this is the issue tracker
