### ISSUE TITLE
Add option to emit fully qualified type names in function signatures

### ISSUE THREAD

**Issue by gpartida** [square/kotlinpoet#1223]
I'd like for there to be an option to emit the fully qualified type name of a parameter and the return types of a function rather the default behavior of emitting just the type name and adding an import for the package the type belongs to. My use case is a bit specific but I am generating a kotlin class which will be further processed by another Kapt processor K2 but the class I generate also references types that will be generated by a third Kapt processor K3. I am not able to ensure the ordering of these downstream processors such that K2 always runs after K3 so what ends up happening is that when generating stubs for K2 Kapt substitutes the types which will be generated by K3 with `NonExistentClass` by default. This behavior can be overriden by setting a kapt flag https://kotlinlang.org/docs/kapt.html#non-existent-type-correction. However, when I enable this option what ends up still happening is the the package import generated by kotlinpoet ends up being replaced with "import unknown.TypeOfInterest". I found that by "manually" generating the function with the yet to be generated parameter types, if I output the fully qualified name of the types right in the signature then this substitution behavior is skipped and my code is able to generate as needed for the final compilation phase (even if the generated code is overly verbose).

**Comment by Egorand** [comment]
This use case indeed feels very specific to warrant a new API. Are there any tools (like ktlint or detekt) that would allow you to post-process the generated code to replace short names with fully qualified ones?

**Comment by JakeWharton** [comment]
You could also call toString on a TypeSpec and write that out since it won't require any imports.

**Comment by gpartida** [comment]
> You could also call toString on a TypeSpec and write that out since it won't require any imports.

Are you saying to define a TypeSpec with the method I want to have parameters with fully qualified names in the signature and then after calling toString on it, search the resulting string for the parameter I care about and add in the package names in front of the generated parameter type before writing this out to a file?

**Comment by gpartida** [comment]
Ended up just forking one of the two downstream processors so I could control their sequencing so that the types are always generated and available on time.
