### ISSUE TITLE
Less for loops

### ISSUE THREAD

**Issue by jmfayard** [square/kotlinpoet#1224]
Good morning, afternoon or night!

First, I would like to thank you for Kotlinpoet, I am very pleased what I can do with it inside https://github.com/krzema12/github-actions-kotlin-dsl

Then I have a suggestion for a more functional Kotlinpoet:

In my normal Kotlin code, I rarely use for loops, because I have been spoiled by Kotlin's stdlib.

I had a look at my Kotlinpoet code where I use loops, and most of them follow the same pattern:
- emit a given prefix
- do a for loop on a list or a map
- emit some CodeBlock and a separator
- emit a postfix
- maybe do something different if the list/map is empty

This is exactly what has been solved by the Stdlib with the function

```kotlin
fun <T> Iterable<T>.joinToString(prefix: String, separator: String, postfix, transform: (T) -> String) : String
```

So I created an equivalent for Kotlinpoet

```kotlin
fun <T : Any> Iterable<T>.joinToCodeBlock(
    prefix: CodeBlock,
    separator: CodeBlock.of(",\n"),
    postfix: CodeBlock = CodeBlock.of(")"),
    ifEmpty: CodeBlock = CodeBlock.EMPTY,
    transform: ((T) -> CodeBlock?),
): CodeBlock

fun <K,V> Map<K,V>.joinToCodeBlock( <same args>) : CodeBlock
```

Usage:

To generate a `listOf()` with its `vararg`:

```kotlin
fun List<Int>.toKolin(): CodeBlock = 
    this.joinToCodeBlock(
        prefix = CodeBlock.of("listOf("),
        separator = CodeBlock.of(", "),
        ifEmpty = CodeBlock.of("emptyList<String>()"),
        transform = { CodeBlock.of("%S", "$it$it") }
    )

listOf(1, 2, 3).toKolin().toString() shouldBe """
    listOf("11", "22", "33")
""".trimIndent()

emptyList<Int>().toKolin().toString() shouldBe "emptyList<String>()"
```

or to generate a call to a constructor with named arguments

```kotlin
val properties: Map<String, Any> = mapOf(
    "always-auth" to "false",
    "node-version" to "1.0.0",
    "token" to "my-token",
)

val codeblock = properties.joinToCodeBlock(
    prefix = CodeBlock.of("val %L = %T(", "myAction", SetupNodeV2::class.asTypeName()),
    transform = { key, value ->
        CodeBlock.of("%L = %S", key.toCamelCase(), value)
    }
)
codeblock.toString() shouldBe """
  val myAction = it.krzeminski.githubactions.actions.actions.SetupNodeV2(
    alwaysAuth = "false",
    nodeVersion = "1.0.0",
    token = "my-token",
  )
  
""".trimIndent()
```

I really liked how this transforms my codebase.

What do you think, would such a functional helper make sense?

**Comment by ZacSweers** [comment]
We already have `joinToCode()`, albeit without prefix/suffix/empty handling. I don't know that those extra parameters are worth operating an alternative

**Comment by jmfayard** [comment]
Oh that's handy, I didn't know about that.

I see that `joinToCode()` operates on a `List<CodeBlock>` and has parameters which are String, while my solution does it the other way around, `List<T>` with parameters of type `CodeBlock`. I prefer my solution personally.

`joinToCode()` does have prefix and suffix.
I added the parameter `ifEmpty()` because else my code generated a `listOf()` in a context where the type could not be inferred, resulting in a compilation error ; also often it generated `MyConstructor(\n)` instead of `MyConstructor()`

**Comment by ZacSweers** [comment]
It's more flexible but at the cost of filling the autocomplete for all collections, whereas our existing one constrains itself to CodeBlock. Flexibility isn't always better as we want to limit API surface area and focus on offering nuts and bolts.

**Comment by jmfayard** [comment]
I understand, have a nice day
