### ISSUE TITLE
Allow to opt out of escaping for soft & modifier keywords 

### ISSUE THREAD

**Issue by efemoney** [square/kotlinpoet#1229]
Soft keywords (eg. `get`) only act as keywords in very specific cases. 

There should be a way for codegen authors to explicitly opt out of escaping soft keywords in specific cases.

One example is generating ktor client code where generated code reads better without the backticks
```kotlin
client.get { ... }
// VS
client.`get` { ... }
```

**Comment by Egorand** [comment]
Our general philosophy for this library is to prefer sane defaults and smaller API surface over customizability. Exposing and maintaining extra API to customize the look and feel of generated code is not something we want to do. I'm closing this issue, however, if there's a stronger reason for having the ability to enable/disable backticks - please let us know.

**Comment by Omico** [comment]
@Egorand Hello, I ran into an annoying problem with this. It makes Ktlint throw an error because it contains an `internal` with backticks in my package name. Maybe this is a good reason to let us work on this issue. Currently, I have to do secondary processing of code generated by kotlinpoet.

```
package me.omico.consensus.spotless2.`internal`
```

```
Step 'ktlint' found problem in 'src\main\kotlin\me\omico\consensus\spotless2\internal\ConsensusSpotless2ExtensionImpl.kt':
Error on line: 1, column: 9
rule: standard:package-name
Package name contains a disallowed character
java.lang.AssertionError: Error on line: 1, column: 9
rule: standard:package-name
Package name contains a disallowed character
```

```
private fun tidyUpGeneratedSourceFile(file: Path): Unit =
    file.readText()
        // Remove backticks for internal keyword
        .replace(".`internal`", ".internal")
        .let(file::writeText)
```

**Comment by Omico** [comment]
> @Omico this looks like a bug in Ktlint.
> 
> That said, I do think we're being overly cautious by escaping all keywords. Escaping of all keywords was introduced by #994, and it has a link to an issue we had with `open`, which acts as a keyword in some contexts and can be used as an identifier in other contexts - we weren't sure how to handle this properly. Let me know if you have thoughts!

Found something interesting, maybe we can follow this https://github.com/JetBrains/intellij-community/blob/master/plugins/kotlin/code-insight/inspections-shared/src/org/jetbrains/kotlin/idea/codeInsight/inspections/shared/RemoveRedundantBackticksInspection.kt
