### ISSUE TITLE
Cannot add "override" annotation on constructor parameters

### ISSUE THREAD

**Issue by alinaeftn** [square/kotlinpoet#1230]
Current version: 1.10.2
Upgrading to: 1.11.0

Hi! I am trying to upgrade kotlinpoet to 1.11.0 and I receive an exception:

```
Exception in thread "main" java.lang.IllegalArgumentException: Modifiers [OVERRIDE] are not allowed on Kotlin parameters. Allowed modifiers: [VARARG, NOINLINE, CROSSINLINE]
```

We are deriving classes from a superclass and we need to be able to add `override` on the property declaration in the primary constructor. Reference: https://kotlinlang.org/docs/inheritance.html#overriding-properties

I think this was introduced by PR #1182.

Is this intended?

**Comment by JakeWharton** [comment]
Parameters cannot override things which is why the modifier is forbidden. Properties are the syntactical element which override things and are the spec on which you should add the override modifier.

Here's a random example from our tests:

https://github.com/square/kotlinpoet/blob/master/kotlinpoet/src/test/java/com/squareup/kotlinpoet/TypeSpecTest.kt#L3939-L3980

**Comment by JakeWharton** [comment]
If that does not help please include an example of your desired output and the current code you are using to attempt to generate it.

**Comment by alinaeftn** [comment]
Thank you for the quick response, @JakeWharton!

Here is our current example:

```
// define the model spec
    val modelFile = FileSpec.builder(testPackage, modelClassName)
        .addType(
            TypeSpec.classBuilder(modelClassName)
                // add the annotations
                .addAnnotation(annotationSpec)
                // the model is a data class
                .addModifiers(KModifier.DATA)
                // the model implements one of the interfaces
                .addSuperinterface(interfaceName)
                // the primary constructor uses all the fields
                .primaryConstructor(defineConstructor(fields))
                // specifying the primary constructor and the properties is necessary for Kotlin Poet to
                //  generate a data class where all the fields are specified in the constructor
                .addProperties(
                    fields.entries.map { (fieldName, fieldType) ->
                        PropertySpec.builder(fieldName, fieldType).initializer(fieldName).build()
                    }
                )
                // we generate a copy function which takes in new settings
                .addFunction(copyFunction)
                .build()
        )
        .indent("    ")
        .build()

private fun defineConstructor(fields: Map<String, KClass<*>>): FunSpec = FunSpec.constructorBuilder()
  .addParameters(
      fields.entries.map { (fieldName, fieldType) ->
          ParameterSpec.builder(fieldName, fieldType).addModifiers(OVERRIDE).build()
      }
  )
  .build()
```

With the code above, the generated class looks like this:
```
public data class TestsRecords(
    public override val id: String,
    public override val name: String,
    public override val title: String
) : TestsImplementationRecord {}
```

As you can see, we need to add the `override` to the constructor parameters because they are overriding the values from the superclass. Removing the override will end up in an error
```
'id' hides member of supertype 'TestsImplementationRecord' and needs 'override' modifier
```

Please let me know if this helps and if we can achieve this behaviour with 1.11.0.

**Comment by alinaeftn** [comment]
> It doesn't seem like you've changed it based on my suggestion above though.

Yes, you are right. Thank you!
