### ISSUE TITLE
Add support for context receivers

### ISSUE THREAD

**Issue by DRSchlaubi** [square/kotlinpoet#1232]
Kotlin 1.6.20 has added [context receivers](https://github.com/Kotlin/KEEP/blob/master/proposals/context-receivers.md) however there is currently no way to generate them using kotlin poet.

These would be needed for both lambdas and functions

**Comment by JakeWharton** [comment]
Let's discuss API proposals here and then we'd love for someone to contribute a PR.

**Comment by JakeWharton** [comment]
Also note that these will have to remain behind an opt-in annotation with no API guarantees until they are actually released as stable as the version in Kotlin 1.6.20 is most emphatically not.
