### ISSUE TITLE
Don't emit empty class bodies

### ISSUE THREAD

**Issue by JakeWharton** [square/kotlinpoet#124]
```kotlin
class Foo {
}
```

**Comment by geralt-encore** [comment]
Isn't  it already implemented [here](https://github.com/square/kotlinpoet/blob/master/src/main/java/com/squareup/kotlinpoet/TypeSpec.kt#L81)? `companionObject`, `enumConstants` and `initializerBlock` should be probably added as well. Should I make a PR?

**Comment by JakeWharton** [comment]
It doesn't work. Try adding a primary constructor and a property initialized to the constructor.

You get

```
class Foo(val bar: Bar) {
}
```

**Comment by vanniktech** [comment]
This can be closed, right?
