### ISSUE TITLE
Add support for context receivers and/or code block in FileSpec

### ISSUE THREAD

**Issue by seriouslyhypersonic** [square/kotlinpoet#1243]
Hello,

I am writing a library that has multiple annotation processors and also uses KotlinPoet (thank's for the awesome work!). However, I am stuck on a very specific issue due to a new language feature which is essential for this library.

1. Kotlin 1.6.20 added [context receivers](https://blog.jetbrains.com/kotlin/2022/02/kotlin-1-6-20-m1-released). I currently need to declare a property that has multiple implicit receivers. It seems this will require an update to KotlinPoet. 
2. These waiting could be avoided if there was a way to add a custom block at file spec level something like:

```kotlin
FileSpec
    .builder(packageName, fileName)
    .addCode("context(TypeA, TypeB)") // As a workaround 
    .addProperty(propertySpec)
    .build()
```

Is there a way to achieve this that I am not aware of?

Thanks in advance

**Comment by JakeWharton** [comment]
Context receivers were tracked by #1232 and support is merged. Arbitrary code addition isn't an appealing feature here because we do not guarantee the order that you add items to a spec builder is the output order.

**Comment by seriouslyhypersonic** [comment]
@JakeWharton Thanks for the feedback! Arbitrary code addition doesn't indeed sound appealing under those circumstances. I'll move on to a snapshot version until it's officially released.
