### ISSUE TITLE
Create annotationSpec from annotation

### ISSUE THREAD

**Issue by DHosseiny** [square/kotlinpoet#1251]
When writing annotation processors in some cases someone wants to add some annotation to generating class with an existing annotation instance. 
Actually, some annotations are present on some classes that the annotation processor is processing and want to add/copy that annotation as it is to the generating class. 
Something like this in ksp:

```
val myAnnotation = ksClassDeclaration.getAnnotationsByType(SomeAnnotation::class).first()
...
FileSpec.builder(
            packageName = PACKAGE_NAME,
            fileName = className
        )
.addAnnotation(myAnnotation)
```
I don't know if it is applicable or not.

**Comment by ZacSweers** [comment]
This exists already - `KSAnnotation.toAnnotationSpec()`

https://github.com/square/kotlinpoet/blob/master/interop/ksp/src/main/kotlin/com/squareup/kotlinpoet/ksp/annotations.kt
