### ISSUE TITLE
Can't output sealed class with open parameter in constructor

### ISSUE THREAD

**Issue by asm0dey** [square/kotlinpoet#1258]
For example
```
public sealed class ActivityItem(
  public open val id: String,
)
```
throws error
```
Exception in thread "main" java.lang.IllegalArgumentException: Modifiers [OPEN] are not allowed on Kotlin parameters. Allowed modifiers: [VARARG, NOINLINE, CROSSINLINE]
```

**Comment by asm0dey** [comment]
Here is the minimal example:
```
    FileSpec.builder("nop","nop.kt").addType(
        TypeSpec.classBuilder("Test")
            .addModifiers(KModifier.SEALED)
            .primaryConstructor(
                FunSpec.constructorBuilder()
                    .addParameter(
                        ParameterSpec("id", String::class.asTypeName(), KModifier.OPEN)
                    )
                    .build()
            )
            .build()
    ).build().writeTo(System.out)
```

**Comment by Egorand** [comment]
The easy fix here is to associate the parameter with a property:

```kotlin
FileSpec.builder("nop","nop.kt").addType(
  TypeSpec.classBuilder("Test")
    .addModifiers(KModifier.SEALED)
    .primaryConstructor(
      FunSpec.constructorBuilder()
        .addParameter(
          ParameterSpec("id", String::class.asTypeName())
        )
        .build()
    )
    .addProperty(PropertySpec.builder("id", String::class, KModifier.OPEN)
      .initializer("id")
      .build())
    .build()
).build().writeTo(System.out)

// outputs

package nop

import kotlin.String

public sealed class Test(
  public open val id: String,
)

```

**Comment by asm0dey** [comment]
Wow, I didn't even think about it. I think it should be documented

пн, 6 июн. 2022 г., 20:14 Egor Andreevich ***@***.***>:

**Comment by Egorand** [comment]
The [Constructors](https://square.github.io/kotlinpoet/#constructors) chapter of our main doc page mentions a similar example. As for `ParameterSpec` not accepting the `OPEN` modifier, this simply mirrors Kotlin compiler's behaviour - you can't mark a function parameter as "open". Please let us know if you've got suggestions on how to document this better!

**Comment by asm0dey** [comment]
Hm, maybe we need this concrete or similar example. And maybe we need a separate section about parameter-property merging.

Also, I would say it would be cool if constructors would know their context and if it's a primary constructor — they may have properties inside.

**Comment by asm0dey** [comment]
Well, to be honest the only way I see it's too differentiate context of
function. If it's a primary constructor it can accept open or override
parameters, otherwise no.

пн, 6 июн. 2022 г., 21:59 Egor Andreevich ***@***.***>:
