### ISSUE TITLE
KSType.toTypeName incorrectly resolves typealias type argument

### ISSUE THREAD

**Issue by micHar** [square/kotlinpoet#1304]
For `typealias LeAlias = Map<Int, String>`, if I use `KSTypeReference.toTypeName` I get excessively parameterized typealias if the typealias itself is a type param. Complicated 😅, so here's an example:

```
original KSTypeReference -> TypeName
---
LeAlias -> LeAlias (OK)
Flow<LeAlias> -> Flow<LeAlias<Int, String>> (wrong, unexpected type params for LeAlias)
```

kotlinpoet version: 1.12.0

**Comment by micHar** [comment]
What happens is that when `Flow` type is encountered, we fall into [this line](https://github.com/square/kotlinpoet/blob/8f6c9a56bc554fddd32d527bc67b7679fac223a7/interop/ksp/src/main/kotlin/com/squareup/kotlinpoet/ksp/ksTypes.kt#L66). If I understand it correctly, `arguments` is resolved to TypeName without regard to wether it's a typealias or not. Relevant info seems to be provided by `KSTypeArgument`, just not used in `KsTypeArgument.toTypeName` like it is in `KsType.toTypeName`.

<img width="660" alt="Zrzut ekranu 2022-07-1 o 14 26 22" src="https://user-images.githubusercontent.com/1609815/176894162-945fa69f-8efc-4991-bfd5-f33a9bc54f1a.png">

**Comment by micHar** [comment]
This still doesn't work in my case, although I can see that it's supposed to be fixed and there are even tests for it.

I used 1.14.2 and 1.15.0-SNAPSHOT.
I matched the kotlin and ksp version with the main branch.
```
kotlin = "1.8.22
ksp = "1.8.22-1.0.11"
```

However I still get this:
```
List<Alias997<Int, String>>
```
from this:
```
typealias Alias997 = Map<Int, String>
List<Alias997>
```

I narrowed it down to the fact, that in `internal fun KSType.toTypeName`
```
    is KSClassDeclaration -> {
      decl.toClassName().withTypeArguments(arguments.map { it.toTypeName(typeParamResolver) })
    }
```
the `arguments` in my case is `Map<Int, String>` and in the kotlinpoet tests it's `Alias997`. `arguments` is part of KSP API, but I cannot understand why in my case it's a resolved typealias and in your case still the unresolved one. @ZacSweers @Egorand do you have any idea what might be the cause?

**Comment by micHar** [comment]
I tried to do that but failed. Thought that you guys might understand the ksp internals a bit better than me. I have this test case in an open source repo, though. It's not pushed to github yet, but I could push it. Question is if you are interested in compiling a separate project to look into it, I understand you might not have time for that.

**Comment by Egorand** [comment]
@robertfmurdock wanna open a new bug ticket?
