### ISSUE TITLE
Support KotlinJS external classes

### ISSUE THREAD

**Issue by marciodel** [square/kotlinpoet#131]
In KotlinJS, declaring a class as external makes all members implicitly external.

Currently the implicit modifiers set for members are not dynamic.

**Comment by JakeWharton** [comment]
I'm not sure we even need implicit modifiers like we do in JavaPoet. I
think the whole concept can be removed from the library.

**Comment by JakeWharton** [comment]
Nevermind. I was thinking of something different.

We can probably do this, although implicit modifiers are an optimization that isn't strictly needed for correctness, just for cleaning up the generated code.

**Comment by marciodel** [comment]
Nice!

For KotlinJs the implicit 'external' it is about correctness. Only top-level declaration can have 'external' modifier and it propagates for the inner declarations.

In fact I've modified the code to implement it. It is working fine. I intend to create a PR, ASAP.

**Comment by cypressious** [comment]
Currently you also can't do `external` top-level properties.

**Comment by Egorand** [comment]
Fixed with #287
