### ISSUE TITLE
How to convert TypeSpec to TypeName

### ISSUE THREAD

**Issue by NamekMaster** [square/kotlinpoet#1328]
I try to generate a class and use it in another function as return type. if the generated class has generic type, How do I convert it to TypeName with generic type?

for example:
```
// the generated class
class Foo<T>(val a: T)

// the function use class above as return type
fun getFoo(): Foo<T> {
  // function body
}

```

I have a look on FunSpec source, seems I need something like `com.squareup.kotlinpoet.CodeWriter#emitTypeVariables`. Is there any other more convenient way to do this?

**Comment by ZacSweers** [comment]
This is the issue tracker, please use discussions for questions
