### ISSUE TITLE
Import Kotlin-JS class

### ISSUE THREAD

**Issue by DATL4G** [square/kotlinpoet#1332]
So I have a jvm module with which I create Kotlin-JS files, and I wanna put them in another module (js).

I'm creating the File like this:

```kotlin
FileSpec.builder("test", "Import")
            .addAnnotation(
                AnnotationGenerator.POLYFILL_ANNOTATION
            ).addKotlinDefaultImports(
                includeJvm = false,
                includeJs = true
            )
            .addDefaultPackageImport("kotlin.js")
```

And adding functions with return classes like this:

```kotlin
ClassName("kotlin.js", "Promise").parameterizedBy(String::class.asTypeName())
```

The functions are created as expected, however the ```kotlin.js.Promise``` import is completly missing and no ```kotlin.js.*``` as well.

I'm not sure how to add the Import then

**Comment by ZacSweers** [comment]
I think you misunderstood how that works. Default imports are imports that do not need to be explicitly declared, so they would not be generated in this case

**Comment by DATL4G** [comment]
Oh now I see.
I think the naming here can be easily misunderstood

**Comment by ZacSweers** [comment]
The naming matches Kotlin's: https://kotlinlang.org/docs/packages.html#default-imports
