### ISSUE TITLE
Dependency on guava with vulnerability

### ISSUE THREAD

**Issue by micHar** [square/kotlinpoet#1334]
That's probably not a big deal, but Sonatype Lift reports a vulnerability in the version of guava imported by kotlinpoet (`com.google.guava:guava:31.1-jre`). 
https://ossindex.sonatype.org/vulnerability/sonatype-2020-0926

**Comment by ZacSweers** [comment]
From the upstream issue: https://github.com/google/guava/issues/4011

> Updating to Guava 30.0 does not fix this security vulnerability. The method is merely deprecated. There currently exits no fix for this vulnerability.
