### ISSUE TITLE
KSP interop outputs annotation parameter value of type `Char` incorrectly

### ISSUE THREAD

**Issue by mars885** [square/kotlinpoet#1336]
Hey.

I'm in a process of migrating my project [hilt-binder](https://github.com/mars885/hilt-binder) to use the KSP interop artifact. However, I stubled upon the issue where if there is an annotation that has `Char` parameter, then the output code will be invalid because of the lack of the single quotes `'`.

For example:
`kotlinpoet/interop/ksp/test-processor/src/main/kotlin/com/squareup/kotlinpoet/ksp/test/processor/exampleAnnotations.kt`
```kotlin
package com.squareup.kotlinpoet.ksp.test.processor

import kotlin.reflect.KClass

annotation class ExampleAnnotation

annotation class ComprehensiveAnnotation<T : CharSequence>(
  // ...
  val char: Char, // <---------------- new type
  // ...
```
`kotlinpoet/interop/ksp/test-processor/src/test/kotlin/com/squareup/kotlinpoet/ksp/test/processor/TestProcessorTest.kt`
```kotlin
  @Test
  fun smokeTest() {
    val compilation = prepareCompilation(
      kotlin(
        "Example.kt",
        """
           package test

           import com.squareup.kotlinpoet.ksp.test.processor.AnnotationEnumValue
           import com.squareup.kotlinpoet.ksp.test.processor.AnotherAnnotation
           import com.squareup.kotlinpoet.ksp.test.processor.ComprehensiveAnnotation
           import com.squareup.kotlinpoet.ksp.test.processor.ExampleAnnotation

           typealias TypeAliasName = String
           typealias GenericTypeAlias = List<String>
           typealias ParameterizedTypeAlias<T> = List<T>
           
           // Input File
           @ComprehensiveAnnotation<String>(
             true, // Omit the name intentionally here to test names are still picked up
             booleanArray = [true],
             byte = 0.toByte(),
             byteArray = [0.toByte()],
             char = 'a', // <---------------- new type
             // ...

            // Output file
            assertThat(generatedFileText).isEqualTo(
              """
              package test
        
              // lots of imports
        
              @ComprehensiveAnnotation<String>(
                boolean = true,
                booleanArray = arrayOf(true),
                byte = 0.toByte(),
                byteArray = arrayOf(0.toByte()),
                char = a.toByte(), // <---------------- outputs a.toByte(), but should 'a'
                short = 0.toShort(),
```
I've forked a repo and provided a demo of the bug on the branch [bug_showcase_invalid_char_type_output](https://github.com/mars885/kotlinpoet/tree/bug_showcase_invalid_char_type_output).

Having checked your sources for a possible fix, it appears that [this line](https://github.com/square/kotlinpoet/blob/d685eca08d6de064bdf16511be496bcd17e668ab/interop/ksp/src/main/kotlin/com/squareup/kotlinpoet/ksp/Annotations.kt#L114)
`is Char -> CodeBlock.of("$value.toChar()")` should be made like this: `is Char -> CodeBlock.of("'%L'", value)`. I've tried that in a fork and it has successfully fixed the issue.

Would love to contribute if possible.

**Comment by ZacSweers** [comment]
PR welcome!
