### ISSUE TITLE
Long lists line wrapping makes code not compile

### ISSUE THREAD

**Issue by pablisco** [square/kotlinpoet#1346]
If we have a list of strings that is too long the way Kotlin Poet wraps the line. However, it looks for spaces without taking into account if the space is in the code or inside a literal String. 

This means we can end with code that does not compile.

This is an example producer code:

```kotlin
        FileSpec.builder("example", "Example")
            .addProperty(PropertySpec.builder("test", List::class.parameterizedBy(String::class))
                .initializer((1..10).joinToString(", ", "listOf(", ")") { "\"$it $it $it\"" })
                .build())
            .build()
```

This generates the following code:

```kotlin
public val test: List<String> = listOf("1 1 1", "2 2 2", "3 3 3", "4 4 4", "5 5 5", "6 6 6", "7 7
    7", "8 8 8", "9 9 9", "10 10 10")
```

Which doesn't compile:

![image](https://user-images.githubusercontent.com/260697/183885877-de6235b1-dd28-40e2-a971-c562bc4b00d3.png)

There are two possible solutions I can think of (there may be more and both could be valid)

1. Allow defining the max line length (and potentially other format options) when creating a `FileSpec`. This could potentially scale a bit better as would help to fix this for other unforeseeable cases. At least until a fix is made. Also, there are some cases where it makes sense to have long lines.
2. Take into account Strings when breaking the line.

For now, the workaround I had to use is to add new line breaks to each entry. However, this is not ideal as some of the collections I'm working with can have hundreds of lists with hundreds of items each and want to avoid wrapping 🤞 

 Thank you for the help and thank you for this amazing tool 🙂

**Comment by Egorand** [comment]
Use `%S` ([docs](https://square.github.io/kotlinpoet/#s-for-strings)) to tell KotlinPoet that those strings are in fact string literals and should be handled accordingly:

```kotlin
FileSpec.builder("example", "Example")
  .addProperty(PropertySpec.builder("test", List::class.parameterizedBy(String::class))
    .initializer((1..10).joinToString(", ", "listOf(", ")") { CodeBlock.of("%S %S %S", it, it, it) })
    .build())
  .build()
```

**Comment by JakeWharton** [comment]
And consider using `map` and then `joinToCode` to keep a `CodeBlock` all the way through. This will allow using things such as member references for functions (like `listOf`) if you need them.

**Comment by pablisco** [comment]
Oh, amazing!!! Thanks for the tip @JakeWharton. For reference, this is what I ended with:

```kotlin
FileSpec.builder("example", "Example")
    .addProperty(
        PropertySpec.builder("test", List::class.parameterizedBy(String::class))
            .initializer(
                CodeBlock.builder()
                    .add("%M(", MemberName("kotlin.collections", "listOf"))
                    .add((1..10).map { CodeBlock.of("%S", "\"$it $it $it\"") }.joinToCode())
                    .add(")")
                    .build()
            )
            .build()
    )
```

Happy to make a separate ticket (and close this one). As I mentioned, I was wondering if there is an option of having longer lines?

**Comment by pablisco** [comment]
Ok, to answer my own question and for future searchers (probably me). This can be done using the no line break symbol like this: `.joinToCode(",·")` 🥳

**Comment by Egorand** [comment]
Making line length configurable is a popular ask, however our stance on it is that we don't want to introduce extra API for tweaking the style and formatting of generated code. Our recommendation is to post-process generated code if needed, using tools like ktlint or ktfmt.
