### ISSUE TITLE
ClassName.bestGuess generates bad imports

### ISSUE THREAD

**Issue by JQTechnologies** [square/kotlinpoet#1350]
for example if we have created (by using `TypeSpec`) class `Exx` 

then created Parameter for function with type `ClassName.bestGuess("Exx")`, after doing this import is created `import Exx` which is an code error

(Everything in this example is in one file/module)

Is there any workaround for this or am I doing something wrong?

**Comment by ZacSweers** [comment]
This API expects a package name, not just simple names
