### ISSUE TITLE
KSP default annotation arguments cause a NullPointerException

### ISSUE THREAD

**Issue by rickclephas** [square/kotlinpoet#1357]
Converting a `KSAnnotation` to an `AnnotationSpec` results in a `NullPointerException` when the annotation doesn't explicitly specify all arguments.

E.g. using the [`@ObjCName`](https://github.com/JetBrains/kotlin/blob/cc00dcc0384443147115f4321436b24bebd8eecb/libraries/stdlib/src/kotlin/annotations/NativeAnnotations.kt#L68) annotation:
```kotlin
annotation class ObjCName(val name: String = "", val swiftName: String = "", val exact: Boolean = false)
```
with a single argument:
```kotlin
@ObjCName("myCustomName")
val myProperty = ""
```
results in the following `KSAnnotation.arguments`:
```
[name:myCustomName, swiftName:null, exact:null]
```

which fails with a `NullPointerException`:
https://github.com/square/kotlinpoet/blob/6596014943a39961b9c5075da758a9b16397902f/interop/ksp/src/main/kotlin/com/squareup/kotlinpoet/ksp/Annotations.kt#L44

**Comment by rickclephas** [comment]
Noticed that this should actually be supported and [tested](https://github.com/square/kotlinpoet/blob/17828e15c214971ce8837f3ff5a2e4ac5f18c3e3/interop/ksp/test-processor/src/main/kotlin/com/squareup/kotlinpoet/ksp/test/processor/exampleAnnotations.kt#L48).
Might be related to Kotlin/Native and/or the dev builds I am currently using.
Will do some more testing 🙂.

**Comment by rickclephas** [comment]
Alright it doesn't seem related to K/N or the dev builds.
Using an annotation from the same compilation does actually work.
The issue arises when an annotation from stdlib (or another library) is used.

Tested with Kotlin 1.7.10 and KSP 1.7.10-1.0.6.

**Comment by rickclephas** [comment]
The same issue can be reproduced with the [`@Deprecated`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-deprecated/) annotation.
For JVM targets the default arguments are available, but for Native targets they are not.

**Comment by rickclephas** [comment]
This should work correctly once KSP correctly exposes the default arguments: https://github.com/google/ksp/issues/885

**Comment by Egorand** [comment]
Appreciate the in-depth investigation, thanks!
