### ISSUE TITLE
Imports not added when generating Files

### ISSUE THREAD

**Issue by alreadyhaveanaccount4** [square/kotlinpoet#1358]
I have an Annotation-processor, which should generate a class `MyGeneratedClass` containing a variable of another class `MyEntity`.

My code inside the `process`function:

```kotlin

    val elementsWithAnnotation = roundEnv.getElementsAnnotatedWith(Entity::class.java)
        if (elementsWithAnnotation.isEmpty()) {
            return true
        }
        val fileName = "MyGeneratedClass"
        val packageName = "me.myname.sdk.generated"
        val classBuilder = TypeSpec.classBuilder(fileName)

        for (element in elementsWithAnnotation) {
            val ann = element.getAnnotation(Entity::class.java)
            println("package: "+ ann.javaClass.packageName)

            val variableBuilder =
                PropertySpec.varBuilder(
                    name = element.simpleName.toString(),
                    type = ClassName("", element.asType().asTypeName().asNullable().toString()),
                    ).initializer("null")
           



            classBuilder
                .addProperty(variableBuilder.build())
        }


        val file = FileSpec.builder(packageName, fileName)
            .addType(classBuilder.build())
            .build()
        val generatedDirectory = processingEnv.options[KAPT_KOTLIN_GENERATED_OPTION_NAME]
        file.writeTo(File(generatedDirectory, "$fileName.kt"))
        return true

```

But the generated code misses the `import MyEntity`

``` java
package me.myname.sdk.generated

class MyGeneratedClass {
    var MyEntity: MyEntity? = null
}

```

When looking inside the generated file, IntelliJ suggests me to import `MyEntity`, which resolves the error. But how can I achieve, that the `import MyEntity` statement is being added when generating the file?

I have already tried adding `MyEntity` as first parameter in `ClassName()`, but this results in an *incorrect* import like this: `import MyEntity.MyEntity?`

**Comment by JakeWharton** [comment]
```
ClassName("", element.asType().asTypeName().asNullable().toString())
```
should just be
``` element.asType().asTypeName().asNullable()
```
You're explicitly setting the package name to empty string before. If there's no package you're not going to get an import.

**Comment by alreadyhaveanaccount4** [comment]
I  now changed it to `element.asType().asTypeName().asNullable()` but still no import.

Maybe something's wrong with my Project structure?
The `MyEntity`Class is annotated with @Entity and the generated file will be present in `sample/build`



<img width="422" alt="screenshot" src="https://user-images.githubusercontent.com/108612066/188287962-6e320fa1-700f-44d4-9ab3-16481f3ace5e.png">

**Comment by Egorand** [comment]
Do you want to share a repro project that we can look at and tweak, to better understand what's not working?

**Comment by alreadyhaveanaccount4** [comment]
https://github.com/alreadyhaveanaccount4/annotationprocessing

**Comment by Egorand** [comment]
Noticed that you were using KotlinPoet version `1.0.0-RC1` which is super old - the behaviour you were observing was likely a bug back then. The latest version is `1.12.0`, I updated the sample project and the correct import was added to the generated code.
