### ISSUE TITLE
KClass to TypeName broken ?

### ISSUE THREAD

**Issue by ShortyFR** [square/kotlinpoet#136]
In 0.2.0, you could get a TypeName from a KClass with this : 

`TypeName.Companion.get(String::class)`

Which enabled one to get a nullable version of it to define a property with type String? for instance : 

`TypeName.Companion.get(String::class).asNullable()`

This doesn't work anymore, and I can't seem to be able to find a replacement for it in the new version (0.3.0) of TypeName.

Maybe I'm doing something wrong or not looking in the right place ?

**Comment by Egorand** [comment]
There's now an extension function for that:

```kotlin
String::class.asTypeName().asNullable()
```

For some reason, IDEA doesn't auto-suggest `asTypeName()`, so import the function manually if needed:

```kotlin
import com.squareup.kotlinpoet.TypeName.Companion.asTypeName
```

**Comment by JakeWharton** [comment]
It's an IDEA bug. I'm mobile or I'd link. Considering moving them to
top-level for next release.

**Comment by ShortyFR** [comment]
Thanks for the answers. I had seen the asTypeName function but was confused because of the IDEA bug. Thanks a lot for the import tip. Works fine now!
