### ISSUE TITLE
No TypeSpec.expectObjectBuilder

### ISSUE THREAD

**Issue by silverhammermba** [square/kotlinpoet#1385]
We've got `TypeSpec.objectBuilder` and `TypeSpec.expectClassBuilder` but there is no companion method that returns `Builder(Kind.OBJECT, name, EXPECT)`.

You can work around it with `TypeSpec.objectBuilder(className).addModifiers(KModifier.EXPECT)` but the API does feel inconsistent because of it.

**Comment by JakeWharton** [comment]
There's also no `expectInterfaceBuilder`. We should probably just deprecate `expectClassBuilder` for removal.
