### ISSUE TITLE
IntelliJ can't automatically import TypeName, ClassName etc extensions

### ISSUE THREAD

**Issue by ansman** [square/kotlinpoet#141]
This might be an issue in Intellij but this does not work in AS 3.0 or Intellij 2017.1.4:
```kotlin
String::class.asClassName()
```
It doesn't help importing `import com.squareup.kotlinpoet.*`, `import com.squareup.kotlinpoet.ClassName.*` or `import com.squareup.kotlinpoet.ClassName.Companion.*`

This works however:
 ```kotlin
ClassName.run { String::class.asClassName() }
```

**Comment by Egorand** [comment]
https://youtrack.jetbrains.com/issue/KT-15286
https://youtrack.jetbrains.com/issue/KT-10343
https://youtrack.jetbrains.com/issue/KT-18416

**Comment by ansman** [comment]
@Egorand Ah, nice. Though I can't get it to work even if I import it manually

**Comment by Egorand** [comment]
@ansman not sure why `*` imports won't work, the following always works for me:

```kotlin
import com.squareup.kotlinpoet.ClassName.Companion.asClassName
```

**Comment by JakeWharton** [comment]
Not supporting star imports is an accidental bonus!

**Comment by ansman** [comment]
Let's close this one then seeing as it isn't an issue in Kotlinpoet

**Comment by JakeWharton** [comment]
We were planning on moving these functions anyway which will fix IntelliJ
