### ISSUE TITLE
Relax classname requirement to allow _ as the first character of class name

### ISSUE THREAD

**Issue by hchen** [square/kotlinpoet#1414]
**Is your feature request related to a problem? Please describe.**
[Netflix dgs-codegen](https://github.com/Netflix/dgs-codegen/) relies on this library to generate kotlin type for federated graphql schema.

One of the [requirement](https://www.apollographql.com/docs/federation/subgraph-spec/#defining-the-_entity-union) for Federated subgraph is to include `union _Entity = SomeEntity`  in the schema for the entities the subgraph can resolve.

For this particular execution path, there is a [check](https://github.com/square/kotlinpoet/blob/master/kotlinpoet/src/main/java/com/squareup/kotlinpoet/ClassName.kt#L205) only allowing upperCase character as the first character of the class name.

However, the rest of execution path doesn't have this restriction. For example, 
```
type _Service {
  sdl: String
}
```
does generate 
```kotlin
public data class _Service(
  @JsonProperty("sdl")
  public val sdl: String? = null,
) {
  public companion object
}
```

Due to this restriction, we have to instruct DGS codegen to generate types in `java` instead of `kotlin`.

**Describe the solution you'd like**
I would suggest that `_` should be allowed as the first character of a className in this execution path.

**Describe alternatives you've considered**
We have to instruct DGS codegen to generate types in `java` which will not use this library.

**Additional context**
Here is the stacktrack for the error:

```
Caused by: java.lang.IllegalArgumentException: couldn't make a guess for com.abc.graphql.testgql.types._Entity
        at com.squareup.kotlinpoet.ClassName$Companion.bestGuess(ClassName.kt:205)
        at com.netflix.graphql.dgs.codegen.generators.kotlin.KotlinPoetUtilsKt.ktTypeClassBestGuess(KotlinPoetUtils.kt:281)
        at com.netflix.graphql.dgs.codegen.generators.kotlin.KotlinPoetUtilsKt.toKtTypeName(KotlinPoetUtils.kt:244)
        at com.netflix.graphql.dgs.codegen.generators.kotlin.KotlinPoetUtilsKt.toKtTypeName$default(KotlinPoetUtils.kt:240)
        at com.netflix.graphql.dgs.codegen.generators.kotlin.KotlinTypeUtils.findKtInterfaceName(KotlinTypeUtils.kt:110)
        at com.netflix.graphql.dgs.codegen.generators.kotlin.AbstractKotlinDataTypeGenerator.generate$graphql_dgs_codegen_core(KotlinDataTypeGenerator.kt:266)
        at com.netflix.graphql.dgs.codegen.generators.kotlin.KotlinDataTypeGenerator.generate(KotlinDataTypeGenerator.kt:71)
        at com.netflix.graphql.dgs.codegen.CodeGen$generateKotlinDataTypes$3.invoke(CodeGen.kt:422)
        at com.netflix.graphql.dgs.codegen.CodeGen$generateKotlinDataTypes$3.invoke(CodeGen.kt:420)
```

**Comment by JakeWharton** [comment]
I'm on mobile so I can't navigate to the call side easily, but it seems like you can use the factory function that accepts the package name and class simple name as separate arguments. Or does something prevent that? This side-steps any kind of validation like this since the structure is now obvious rather than needing to be inferred.

**Comment by hchen** [comment]
@JakeWharton thanks for the quick reply. 
We are using netflix dgs-codegen plugin for our project. I understand I can submit an improvement request on `dgs-codegen`. But from kotlinpoet's perspective, I'm wondering if this check is necessary for this particular execution path. As I mentioned, `_` is allowed in different flow.

**Comment by JakeWharton** [comment]
The problem is that the API they are using is imprecise. It's named `bestGuess` because it's just that–a guess. Could we add this specific case? Absolutely. But while it may solve your specific case it's never going to cover 100% of the cases that you can encounter. For example, using a lowercase name for that type would also break.

Let's try to get the plugin fixed to use the correct API. There should be almost no reason to use the `bestGuess` API in such a case when you know the simple name of a type separately from the package into which it's being generated.

**Comment by hchen** [comment]
Totally agree with you that `bestGuess` is best to be avoided. I will try to figure out why they are handling `type _Service` differently than `union _Entity`. 

This is the [line of code](https://github.com/Netflix/dgs-codegen/blob/master/graphql-dgs-codegen-core/src/main/kotlin/com/netflix/graphql/dgs/codegen/generators/kotlin/KotlinPoetUtils.kt#L281) where `bestGuess` is called.

**Comment by hchen** [comment]
After further investigation it turns out there is no need to add `union _Entity = SomeEntity` in the schema.

**Comment by hchen** [comment]
Thanks!  It might be a tough sell to the team since we're basically misusing the schema.
