### ISSUE TITLE
Strange indentation for a delegated property with multi-line code

### ISSUE THREAD

**Issue by afollestad** [square/kotlinpoet#1437]
I was able to reproduce in this repo. Take this (non-existing) test case for an example:

```kotlin
@Test fun delegatedMultiline() {
  val fakeClassName = ClassName("", "FakeClass")
  val prop = PropertySpec.builder("foo", fakeClassName)
    .delegate(
      CodeBlock.builder()
        .beginControlFlow("lazy {")
        .add("%T(", fakeClassName)
        .withIndent { add("fakeParam = true") }
        .add(")\n")
        .endControlFlow()
        .build()
    )
    .build()
  assertThat(prop.toString()).isEqualTo(
    """
    |val foo: kotlin.String by lazy {
    |  FakeClass(fakeParam = true)
    |}
    """.trimMargin(),
  )
}
```

It fails because the actual property code comes out to be:

```kotlin
val foo: FakeClass by lazy {
      FakeClass(fakeParam = true)
    }
```

---

If I replace the `add` usages with a single `addStatement`, the problem goes away; this will pass:

```kotlin
@Test fun delegatedMultiline() {
  val fakeClassName = ClassName("", "FakeClass")
  val prop = PropertySpec.builder("foo", fakeClassName)
    .delegate(
      CodeBlock.builder()
        .beginControlFlow("lazy {")
        .addStatement("%T(fakeParam = true)", fakeClassName)
        .endControlFlow()
        .build()
    )
    .build()
  assertThat(prop.toString()).isEqualTo(
    """
    |val foo: FakeClass by lazy {
    |  FakeClass(fakeParam = true)
    |}
    """.trimMargin(),
  )
}
```

This became a problem when I wanted to be able to construct a class inside of a delegated property with multiple named arguments on separate lines.

**Comment by ZacSweers** [comment]
If you want to take full control of indents and formatting around them, you'll need to learn the control characters for this in CodeWriter. They're not really intended to be commonly used (generated code isn't normally something that needs to be read), so the documentation is a bit sparse. You should be able to grok them from reading source [here](https://github.com/square/kotlinpoet/blob/master/kotlinpoet/src/main/java/com/squareup/kotlinpoet/CodeWriter.kt#L316) and then fiddle with them in your code gen.

**Comment by afollestad** [comment]
> If you want to take full control of indents and formatting around them, you'll need to learn the control characters for this in CodeWriter. They're not really intended to be commonly used (generated code isn't normally something that needs to be read), so the documentation is a bit sparse. You should be able to grok them from reading source [here](https://github.com/square/kotlinpoet/blob/master/kotlinpoet/src/main/java/com/squareup/kotlinpoet/CodeWriter.kt#L316) and then fiddle with them in your code gen.

Oh interesting, thanks @ZacSweers! This still seems like something that others will observe. If attention has been given to parameter formatting elsewhere, why not for a case like this?

**Comment by ZacSweers** [comment]
You're writing a complex initialiazer, KotlinPoet tries to solve for common cases but cannot account for every case. It cares more about correctness. Once you leave the top level entry points (addStatement, beginControlFlow, etc) and start using more raw APIs like `addCode()`, you are more or less on your own for formatting.

If you care a lot about the formatting about your generated code and are willing to pay a performance cost, you can post-process the generated code with the formatter of your choice (ktfmt, ktlint, etc).

**Comment by afollestad** [comment]
> You're writing a complex initialiazer, KotlinPoet tries to solve for common cases but cannot account for every case. It cares more about correctness. Once you leave the top level entry points (addStatement, beginControlFlow, etc) and start using more raw APIs like `addCode()`, you are more or less on your own for formatting.
> 
> 
> 
> If you care a lot about the formatting about your generated code and are willing to pay a performance cost, you can post-process the generated code with the formatter of your choice (ktfmt, ktlint, etc).

Gotcha - makes sense 👍

**Comment by JakeWharton** [comment]
For multiline named invocations I do this:
https://github.com/cashapp/redwood/blob/fbc94532f7f0b8f231f42ad2f858652a4efa9b0d/redwood-tooling-codegen/src/main/kotlin/app/cash/redwood/tooling/codegen/composeProtocolGeneration.kt#L144-L149

Which yields:

```kotlin
val factories = EmojiSearchWidgetFactories(
      emojiSearch = ProtocolEmojiSearchWidgetFactory(bridge, json, mismatchHandler),
      redwoodLayout = ProtocolRedwoodLayoutWidgetFactory(bridge, json, mismatchHandler),
      redwoodTreehouseLazyLayout = ProtocolRedwoodTreehouseLazyLayoutWidgetFactory(bridge, json, mismatchHandler))
```

which is Good Enough™.

**Comment by afollestad** [comment]
> For multiline named invocations I do this: https://github.com/cashapp/redwood/blob/fbc94532f7f0b8f231f42ad2f858652a4efa9b0d/redwood-tooling-codegen/src/main/kotlin/app/cash/redwood/tooling/codegen/composeProtocolGeneration.kt#L144-L149
> 
> Which yields:
> 
> ```kotlin
> val factories = EmojiSearchWidgetFactories(
>       emojiSearch = ProtocolEmojiSearchWidgetFactory(bridge, json, mismatchHandler),
>       redwoodLayout = ProtocolRedwoodLayoutWidgetFactory(bridge, json, mismatchHandler),
>       redwoodTreehouseLazyLayout = ProtocolRedwoodTreehouseLazyLayoutWidgetFactory(bridge, json, mismatchHandler))
> ```
> 
> which is Good Enough™.

Ah clever! Thanks @JakeWharton! Good enough indeed, and saves a line 😂
