### ISSUE TITLE
Float literal generates a double literal

### ISSUE THREAD

**Issue by DonRobo** [square/kotlinpoet#1478]
**Describe the bug**
Using `%L` to generate float literals produces double literals instead

**To Reproduce**
Using a `CodeBlock.Builder` do `builder.addStatement("%L", 1.0f)`

**Expected behavior**
It should generate a float literal "1.0f" or "1f"

Instead it produces "1.0", a double literal. Since Kotlin does not automatically convert between floats and doubles this will fail if a float is expected.

**Comment by JakeWharton** [comment]
Per https://square.github.io/kotlinpoet/#l-for-literals,

Literals are like calling `toString()` and do not prefix or postfix based on type. If you have a float, append an `f` after the literal marker.
