### ISSUE TITLE
Annotation use site target support

### ISSUE THREAD

**Issue by JakeWharton** [square/kotlinpoet#150]
```kotlin
@field:Foo
```

**Comment by JakeWharton** [comment]
Probably just a nullable enum on AnnotationSpec?

**Comment by Egorand** [comment]
@JakeWharton should work. Should the following be supported?

```kotlin
class Example {
  @set:[Inject VisibleForTesting]
  var collaborator: Collaborator
}
```

https://kotlinlang.org/docs/reference/annotations.html#annotation-use-site-targets

**Comment by JakeWharton** [comment]
That's an output optimization at best. Not something we express in the API.

We can get away with `@set:Inject @set:VisibleForTesting` for now.
