### ISSUE TITLE
Infinite loop in CodeWriter.generateImportAliases

### ISSUE THREAD

**Issue by tadfisher** [square/kotlinpoet#1518]
**Describe the bug**

Ambiguous import aliases can result in the call to `CodeWriter.generateImportAliases` failing to return.

**To Reproduce**

I've narrowed this down in the debugger. The call to `generateImportAliases` passes these arguments:

- `simpleName`: `"Round"`
- `qualifiedNames`: `setOf(MemberName("androidx.compose.ui.graphics.StrokeCap.Companion.Round"), MemberName("androidx.compose.ui.graphics.StrokeJoin.Companion.Round"))`
- `packageName`: `CodeWriter$Companion$withCollectedImports$suggestedMemberImports$2@10685`
- `capitalizeAliases`: `false`

This results in the `while` loop repeating forever, clearing `aliasNames` and writing both qualified names to the same key `"androidxComposeUiGraphicsRound"`. This fails the length check, which expects there to be a unique alias for both qualified names.

**Expected behavior**

`generateImportAliases` should take the containing class names into account, so there isn't a collision between nested types with the same name in the same package.

**Comment by Egorand** [comment]
Thanks! Yeah, the generation logic only looked at the package names, I submitted a fix to use canonical names instead: https://github.com/square/kotlinpoet/issues/1519.
