### ISSUE TITLE
Add ability to annotate a file

### ISSUE THREAD

**Issue by Egorand** [square/kotlinpoet#154]
Add support for 

```kotlin
@file:JvmName("TacoUtils")

package com.squareup.tacos
```

**Comment by Egorand** [comment]
I can work on a PR during the weekend.

**Comment by JakeWharton** [comment]
Sounds good. We'll look to do a 0.4 next week with all these changes so
this would be nice to have.

**Comment by JakeWharton** [comment]
f2297ef330a538e971168d53a436818f13a0b9b5
