### ISSUE TITLE
Omit modifier for override parameters in constructor and it's override function

### ISSUE THREAD

**Issue by Omico** [square/kotlinpoet#1548]
![image](https://github.com/square/kotlinpoet/assets/14316223/e4e9c7a5-559e-4e0a-9d46-bf6c3e15e81e)

Explicit API mode is set as strict.

Also, override function as well.

**Comment by JakeWharton** [comment]
Dupe of #1301

**Comment by JakeWharton** [comment]
Sorry I read the screenshot and not the title. Thought it was about `public` members on an `internal` type.

**Comment by Omico** [comment]
No worries! Please review it carefully. Hope I didn't mess up the tests.
