### ISSUE TITLE
TypeSpec for Kotlin object can emit abstract functions

### ISSUE THREAD

**Issue by drawers** [square/kotlinpoet#1556]
**Describe the bug**
The current validation logic in `TypeSpec.kt` does not prevent emitting the following code:

```kotlin
object Foo {
    abstract fun bar()
}
```

**To Reproduce**

Failing test:

```kotlin
  @Test fun abstractFunForbiddenInObject() {
    val type = TypeSpec.objectBuilder("Taco")

    assertThrows<IllegalArgumentException> {
      type.addFunction(
        FunSpec.builder("eat")
          .addModifiers(ABSTRACT)
          .build(),
      )
        .build()
    }.hasMessageThat().isEqualTo("non-abstract type Taco cannot declare abstract function eat")
  }
```

**Expected behavior**
An exception similar to when we add an abstract function to a non-abstract class.

**Additional context**
I'm trying to fix #1525 which would involve moving validation logic from inside `PropertySpec.kt` into `TypeSpec.kt`. When I was doing this, I noticed some of the other logic in `TypeSpec.kt` has drifted.

**Comment by JakeWharton** [comment]
Note that we don't try and replicate 100% of the Kotlin compiler's validation on things like this. There's much more invalid Kotlin you can generate with KotlinPoet than valid Kotlin, and that's generally okay. Most of the validations are local to a single spec and rarely deal with cross-spec things (although sometimes we have to).

If we can validate it easily, then sure let's do it. But if not, the Kotlin compiler is the final arbiter of validity and it will catch such an error.

**Comment by drawers** [comment]
Thanks for the explanation @JakeWharton 

I think I can fix these two issues I raised but I don't want to make `TypeSpec.kt` too complex.

In the context of fixing #1525 which prevents KotlinPoet from emitting useful code, do you think the best solution would be to eliminate the checks?

https://github.com/square/kotlinpoet/blob/27b28a7209eeec51e3e44e94849e9d89a9be81f0/kotlinpoet/src/main/java/com/squareup/kotlinpoet/PropertySpec.kt#L60

Was thinking of moving the checks into `TypeSpec.kt`

**Comment by JakeWharton** [comment]
No the check is already there and fixing it is easy. Might as well keep! Plus it means the exception happens earlier and is easier to fix.
