### ISSUE TITLE
Split platform-specific helper into their own artifacts.

### ISSUE THREAD

**Issue by JakeWharton** [square/kotlinpoet#157]
Thinking `kotlinpoet` and `kotlinpoet-jvm`, the latter of which has all the `java.*` things like `Class` things, `TypeElement` things, `TypeMirror` things, and #105.

**Comment by JakeWharton** [comment]
This would let someone use the library for Kotlin generation from a native tool or JS tool on node.js, should they want to do so.

**Comment by JakeWharton** [comment]
I think a good start is at least getting them into separate files. Have 90% of this locally.

**Comment by Egorand** [comment]
There's a lot of `@JvmField` and `@JvmStatic` usages to help provide more Java-friendly API. Would be good to remove them from the main library, and supply Java-friendly API with `kotlinpoet-jvm`.

**Comment by Egorand** [comment]
@JakeWharton have something to push?

**Comment by Egorand** [comment]
Closing this in favor of #304
