### ISSUE TITLE
If there are two classes with the same name in a file you cannot use an inner type of one of those classes

### ISSUE THREAD

**Issue by AlecStrong** [square/kotlinpoet#1578]
I'm encountering this in SQLDelight, if my file needs to use two classes with the same name then it will use the package to come up with aliases. I've created the failing test [here](https://github.com/cashapp/sqldelight/compare/astrong/2023-05-27/kotlinpoet-bug?expand=1)

That test demonstrates the code I am expecting to generate, however kotlinpoet has this diff:

```diff
diff (-expected +actual):
    @@ -15,14 +15,14 @@
     
     public class MyViewQueries(
       driver: SqlDriver,
    -  private val soupBaseAdapter: DbSoupBase.Adapter,
    -  private val soupAdapter: DbSoup.Adapter,
    +  private val soupBaseAdapter: DbSoupBase,
    +  private val soupAdapter: DbSoup,
     ) : TransacterImpl(driver) {
       public fun <T : Any> forSoupToken(soup_token: String, mapper: (
         token: String,
         soup_token: String,
    -    soup_broth: ChickenSoupBase.Broth?,
    -    soup_name: ChickenSoup.SoupName?,
    +    soup_broth: ChickenSoupBase?,
    +    soup_name: ChickenSoup?,
       ) -> T): Query<T> = ForSoupTokenQuery(soup_token) { cursor ->
         mapper(
           cursor.getString(0)!!,
```

If you click into the test case and look at the expected generated code, you'll see the Soup and SoupBase types clash so get import aliased with their packages (ChickenSoup vs DbSoup). Everywhere an inner type of one of those types is used in the generated code, it removes the inner type entirely.

**Comment by ZacSweers** [comment]
I believe this is fixed on the main branch, can you try the latest snapshot?

**Comment by AlecStrong** [comment]
yep, it is.

**Comment by ZacSweers** [comment]
Thanks for confirming!

**Comment by AlecStrong** [comment]
Will there be a 1.13.3 or am I stuck waiting for 1.14? Is there a workaround I could just add to SQLDelight for now so we're unblocked from releasing?

**Comment by ZacSweers** [comment]
Egor's going to cut a 1.14.0 next week 👍
