### ISSUE TITLE
Rename clazz parameter to `class`?

### ISSUE THREAD

**Issue by NightlyNexus** [square/kotlinpoet#161]
It's a tiny thing, but autocomplete will show the right name without the ticks and keyword workarounds.
<img width="273" alt="screen shot 2017-06-29 at 9 32 19 pm" src="https://user-images.githubusercontent.com/4032667/27721041-9a387bea-5d12-11e7-950d-07fa8c3fd8b2.png">

Would you consider a PR?

**Comment by JakeWharton** [comment]
Go for it
