### ISSUE TITLE
Broken functions in scripts

### ISSUE THREAD

**Issue by bipokot** [square/kotlinpoet#1620]
**Describe the bug**
Functions in generated script (via `FileSpec.scriptBuilder`) get `public` modifier which is prohibited for local functions in Kotlin scripts.

**To Reproduce**
```kotlin
fun main() {
    val funSpec = FunSpec.builder("foo")
        .apply { returns(UNIT) }
        .build()
    val fileSpec = FileSpec.scriptBuilder("dummy")
        .apply { addFunction(funSpec) }
        .build()

    println(fileSpec.toString())
    
    // public fun foo() {
    //}

    //ERROR: Modifier 'public' is not applicable to 'local function'
}
```

**Expected behavior**
- don't add implicit `public` modifier to functions in script body
OR
- allow to switch off `explicit API` compatibility mode

**Additional context**
KotlinPoet 1.14.2

**Comment by JakeWharton** [comment]
First option should be pretty easy

**Comment by Egorand** [comment]
@bipokot wanna send us a PR?

**Comment by Egorand** [comment]
I created the following script using [kscript](https://github.com/kscripting/kscript):

```kotlin
#!/usr/bin/env kscript

public fun foo() {
}
```

And I run it as follows:

```
chmod +x test.kts
./test.kts
```

The script executes without any errors. So I think having `public fun`s in a script works fine? Is there any documentation on which modifiers Kotlin prohibits in scripts?

**Comment by JakeWharton** [comment]
What about regular Kotlin scripting though?

**Comment by Egorand** [comment]
Hmm, I wasn't aware regular scripting vs kscript support different syntax, but will try executing that script without kscript to see if it works.
