### ISSUE TITLE
Add KotlinFile.Builder.skipKotlinLangImports

### ISSUE THREAD

**Issue by NightlyNexus** [square/kotlinpoet#163]
`import kotlin.String` and others are redundant.
Doesn't matter much for generated code but might be nice to have parity with `skipJavaLangImports`.

**Comment by JakeWharton** [comment]
Do they show as unused in the IDE? I'm tempted to try and not do this
feature and to take a stand against people wanting it. What's wrong with a
little specificity to disambiguate potential collisions?

**Comment by NightlyNexus** [comment]
They don't show as unused.
Yep, I agree!
👍

not worth parity with skipJavaLangImports.
