### ISSUE TITLE
Check for Kotlin keywords.

### ISSUE THREAD

**Issue by NightlyNexus** [square/kotlinpoet#164]
FunSpec.builder("void") fails. FunSpec.builder("fun") will generate.
I don't know of a Kotlin version of `SourceVersion.isName`.

Since it'll generate code that won't compile, I don't know if this check adds much value, anyway.

**Comment by JakeWharton** [comment]
Asked in the Kotlin Slack months ago and there weren't plans to add a
method like that at this time.

**Comment by NightlyNexus** [comment]
👍
Close this?

**Comment by JakeWharton** [comment]
We can hardcode a list.
