### ISSUE TITLE
Conflicting imports generated in 1.13.0+

### ISSUE THREAD

**Issue by JoelWilcox** [square/kotlinpoet#1648]
**Describe the bug**
When there is a simple name conflict between two imports and one of them is an inner class, the resulting alias that gets created for the inner class can conflict with other imports. This issue was encountered with code generated with Anvil.

**To Reproduce**
Failing test that catches this: https://github.com/square/anvil/compare/main...joel.conflicting-imports-test
The relevant source snippet:
```kotlin
      package com.squareup.test
      
      import javax.inject.Inject
      
      class InjectClass @Inject constructor() {
        interface Factory {
          fun doSomething()
        }
      }

      class InjectClassFactory @Inject constructor(val factory: InjectClass.Factory)
```

With KotliinPoet 1.12.0 this results in the following code being generated:
```kotlin
package com.squareup.test

import com.squareup.test.InjectClass.Factory
import com.squareup.test.InjectClassFactory
import javax.inject.Provider
import kotlin.Suppress
import kotlin.jvm.JvmStatic

public class InjectClassFactory_Factory(
  private val factory: Provider<Factory>,
) : dagger.`internal`.Factory<InjectClassFactory> {
  public override fun `get`(): InjectClassFactory = newInstance(factory.get())

  public companion object {
    @JvmStatic
    public fun create(factory: Provider<Factory>): InjectClassFactory_Factory =
        InjectClassFactory_Factory(factory)

    @JvmStatic
    public fun newInstance(factory: Factory): InjectClassFactory = InjectClassFactory(factory)
  }
}
```

Starting with KotlinPoet 1.13.0 and up to the latest 1.14.2 release, we see the following generated:
```kotlin
package com.squareup.test

import com.squareup.test.InjectClassFactory
import javax.inject.Provider
import kotlin.Suppress
import kotlin.jvm.JvmStatic
import com.squareup.test.InjectClass.Factory as InjectClassFactory
import dagger.`internal`.Factory as InternalFactory

public class InjectClassFactory_Factory(
  private val factory: Provider<com.squareup.test.InjectClass.Factory>,
) : InternalFactory<InjectClassFactory> {
  override fun `get`(): InjectClassFactory = newInstance(factory.get())

  public companion object {
    @JvmStatic
    public fun create(factory: Provider<com.squareup.test.InjectClass.Factory>):
        com.squareup.test.InjectClassFactory_Factory =
        com.squareup.test.InjectClassFactory_Factory(factory)

    @JvmStatic
    public fun newInstance(factory: com.squareup.test.InjectClass.Factory): InjectClassFactory =
        InjectClassFactory(factory)
  }
}
```

Previously `InjectClass.Factory` would be imported and `dagger.internal.Factory` would be used in its fully-qualified form. Now we end up with the following three imports where the conflict occurs:
```kotlin
import com.squareup.test.InjectClassFactory
import com.squareup.test.InjectClass.Factory as InjectClassFactory
import dagger.`internal`.Factory as InternalFactory
```

It looks like this change is likely related to https://github.com/square/kotlinpoet/pull/1355

**Expected behavior**
I would expect KotlinPoet to check for import conflicts before generating the code and adjust any problematic aliases, even just by adding a number to one of the aliases. (e.g. in the above code the `InjectClassFactory` alias could be `InjectClassFactory2`)

**Additional context**
Did my best to check through the release notes and see if there's any change we should make on the Anvil side but didn't see anything. I'm also not sure if it's possible to force fully qualified references to be used for certain types, as that could be a work-around for this. But even if that's possible, it felt like it wouldn't be an ideal long-term solution. 

If it's helpful, we do our [code generation related to this test here](https://github.com/square/anvil/blob/1ffbd4a8a0b47e797fb8da14ffd87d556fff7b01/compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/InjectConstructorFactoryGenerator.kt#L59).

**Comment by ZacSweers** [comment]
@Egorand this was the issue I was seeing too but wasn't able to reliably repro

**Comment by Egorand** [comment]
@jamesalee213 & I tried to re-create the test case in a unit test and we didn't get any auto-generated import aliases, which is strange. Can you please take a look to see what we're missing? 

https://github.com/square/kotlinpoet/commit/6e132b3f5661dc011395d48ceaee495e7a287ae9
