### ISSUE TITLE
Kotlinpoet does not stringify negative numbers correctly for swedish locales

### ISSUE THREAD

**Issue by magnus-lundberg-discovery** [square/kotlinpoet#1657]
**Describe the bug**
Kotlinpoet uses the users default locale, not a fixed locale when stringifying numbers. For Swedish locale this means it will not use a correct minus sign and as such not generate valid Kotlin code

**To Reproduce**
Run this test with the computer in Swedish locale:

```
    @Test fun parseTest() {
        val i = -42
        val s = CodeBlock.of("val i = %L", i)
        TestCase.assertEquals("val i = -42", s.toString())
    }
```
The test will fail

**Expected behavior**
Kotlinpoet sets the minusSign here:
```
    private fun formatNumericValue(o: Number): Any? {
      val format = DecimalFormatSymbols().apply {
        decimalSeparator = '.'
        groupingSeparator = '_'
      }
```

**Additional context**
None

**Comment by Egorand** [comment]
Interesting, thanks! Guess hardcoding the sign would prevent you from being able to generate a Swedish minus sign, if you ever want to, but it's consistent with how the library currently works?

**Comment by magnlun** [comment]
I think so since it hard codes thousands separator and decimal symbol to be consistent over locales. The only reason I found this was that I depend on SQLDelight which is very broken for swedish locales at the moment :)

**Comment by hfhbd** [comment]
@Egorand Any time schedule to publish a new release containing this fix?

**Comment by Egorand** [comment]
Probably within the next few weeks!
