### ISSUE TITLE
Add FileSpec output path

### ISSUE THREAD

**Issue by scottjasso** [square/kotlinpoet#1719]
**Is your feature request related to a problem? Please describe.**
I'm writing a gradle plugin to generate code from some source files, using gradle's `InputChanges` API. 

* When a source file is added, I create the FileSpec for that file and call `writeTo(outputDirectory)`. 
* When a source file is removed, I want to delete the corresponding generated file. However, I have to calculate the generated file's relative path myself, because `writeTo` hides the details of that. 

**Describe the solution you'd like**
An API like `FileSpec.relativePath` that gives the same relative path that `writeTo(File)` adds to the base directory.
Then I can call something like `outputDirectory.resolve(fileSpec.relativePath).delete()`

**Describe alternatives you've considered**
I can write my own `FileSpec` extension.

**Additional context**
The details aren't too complex to copy myself, I'm just worried that it could potentially get out of sync.

**Comment by scottjasso** [comment]
@JakeWharton I don't think that works. That gives the path _after writing_. I want to know the path without calling writeTo().

**Comment by JakeWharton** [comment]
Yes I misread the issue. Seems reasonable.

**Comment by scottjasso** [comment]
Thank you!
