### ISSUE TITLE
Document artifactId change for non-Gradle builds

### ISSUE THREAD

**Issue by vatbub** [square/kotlinpoet#1732]
**Describe the bug**
I added kotlinPoet as a dependency with maven like so:
```xml
 <dependency>
    <groupId>com.squareup</groupId>
    <artifactId>kotlinpoet</artifactId>
    <version>1.15.1</version>
    <scope>test</scope>
</dependency>
```
After syncing, IntelliJ fails to resolve any classes. After doing some troubleshooting, I ended up unzipping the jar-file that maven downloaded and it seems that the jar only contains metadata and the `MANIFEST.MF`, but is otherwise empty:

![grafik](https://github.com/square/kotlinpoet/assets/13379225/1c631de5-ef94-4e5e-a70f-71087f9fb1a7)

I then downloaded the Jar from Maven Central manually using the URL provided in the documentation:
[https://search.maven.org/remote_content?g=com.squareup&a=kotlinpoet&v=LATEST](https://search.maven.org/remote_content?g=com.squareup&a=kotlinpoet&v=LATEST)

After unzipping the downloaded Jar, the result is the same, though.

Only versions 1.15.0 and 1.15.1 seem to be affected, version 1.14.2 works fine.

**To Reproduce**
1. Download the Jar either using maven or using the URL as described above
2. Unzip the retrieved Jar file
3. Observe that the Jar only contains a metadata-json file and `MANIFEST.MF`

**Expected behavior**
The Jar file should contain the package `com.squareup.kotlinpoet` and its classes.

Cheers :)

**Comment by JakeWharton** [comment]
You will need to use the kotlinpoet-jvm artifactId now that the library has taken its first step towards supporting multiple platforms.

I'll leave this open for us to update the documentation.
