### ISSUE TITLE
Generic super interface

### ISSUE THREAD

**Issue by Janglinator** [square/kotlinpoet#1746]
Is there a way to generate the following?

```
class MyClass: MySuperclass<User> {
    ...
}
```

I can't seem to find a way to generate this.

**Comment by Janglinator** [comment]
Update:

I managed to generate the type using type projections:

```
        val genericizedDaoType = Dao::class.createType(
            arguments = listOf(KTypeProjection.invariant(User::class.createType()))
        ).asTypeName()
```

I am still curious if there's a better suggested method.

**Comment by Egorand** [comment]
Questions on usage are welcome, but please use either [Discussions](https://github.com/square/kotlinpoet/discussions) or [Stackoverflow](https://stackoverflow.com/questions/tagged/kotlinpoet). The issue tracker is, well, for issues.
