### ISSUE TITLE
Ksp function times lose nullability

### ISSUE THREAD

**Issue by robertfmurdock** [square/kotlinpoet#1758]
**Describe the bug**
In 1.15.2, getting the type of a property that happens to be a nullable function type produces the function type without the nullability.

**To Reproduce**

Simplest way is to checkout this code:

https://github.com/robertfmurdock/jsmints/commit/e8ecd671c0d2021b46319471d291fe709a72a0b0

Update kotlin poet to 1.15.2, and run `./gradlew :libraries:minreact-plugin-test:compileKotlinJs`

You'll see that where getting the typename by poet resolution before produced a nullable type, the new version does not.

**Expected behavior**

When a function type is nullable, that should be retained.

**Comment by ZacSweers** [comment]
Is this fixed by #1756

**Comment by robertfmurdock** [comment]
Sounds like it would be!

**Comment by ZacSweers** [comment]
👍 we'll try to release a fix soon

**Comment by Egorand** [comment]
1.15.3 was released earlier today! Please re-open the issue if you're still observing it in the new version.

**Comment by robertfmurdock** [comment]
confirmed it upgraded smoothly without breaking my new tests. well done!
