### ISSUE TITLE
Can we add IDE highlighting to addStatement or similar statements

### ISSUE THREAD

**Issue by zsqw123** [square/kotlinpoet#1774]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Adding IDE highlighting ability to `addStatement` or similar statements when writing codes by using `@Language` annotation for better writing experience, just like this:  

![image](https://github.com/square/kotlinpoet/assets/49520432/a70c538d-ed00-4d77-ac6a-d7ea7f12b847)

Code here:

```kotlin
fun FunSpec.Builder.betterAddStatement(
    @Language("kotlin") format: String, vararg args: Any
): FunSpec.Builder = apply {
    body.addStatement(format, *args)
}

fun FunSpec.Builder.foo() {
    // before highlighting
    addStatement("val customList: List<String> = listOf(arg1, arg2)")
    // after highlighting
    betterAddStatement("val customList: List<String> = listOf(arg1, arg2)")
}
```

Of course, I want to change the member function, not the extension function, here is just an example

**Describe alternatives you've considered**
No replacement

**Comment by Egorand** [comment]
That's a cool idea, though I'm not sure how useful it'll be in the general sense... It looks like the compiler expects strings annotated with `@Language("kotlin")` to be properly-structured code, here are the errors I see in one of the unit tests that uses `addStatement()`:

![image](https://github.com/square/kotlinpoet/assets/1186186/0e70344d-f82a-4409-9cc1-a90849d6e7ba)

So I wonder if in most cases it'll be more annoying than helpful?

**Comment by zsqw123** [comment]
For top level declaration issue, Although we can use the prefix feature to avoid the problem of top level functions, but it seems to be annoying to the `%` symbol
![image](https://github.com/square/kotlinpoet/assets/49520432/7c9635a6-2443-4653-bd22-aa9e21eb54f9)

**Comment by zsqw123** [comment]
I will close this issue, it seems to be really difficult to solve the problem of grammar highlighting currently due to some syntax check for it

**Comment by Egorand** [comment]
Yeah, if the IDE wasn't as strict about grammar checks it would've been more worthwhile.
