### ISSUE TITLE
kotlin.* imports in generated classes

### ISSUE THREAD

**Issue by andreypfau** [square/kotlinpoet#1775]
**Describe the bug**
When using ClassName("kotlin", ANY_CLASS) it provides `import kotlin.ANY_CLASS` in result file

**To Reproduce**
```kotlin
addAnnotation(
    AnnotationSpec.builder(ClassName("kotlin", "JvmName"))
        .useSiteTarget(AnnotationSpec.UseSiteTarget.GET)
        .addMember("%S", "foo")
        .build()
)
```
in final result in file:
<img width="256" alt="image" src="https://github.com/square/kotlinpoet/assets/97797573/c12d5418-4592-4f89-8319-9f9db1a00d04">

**Expected behavior**
no imports for `kotlin.ANY_CLASS`

**Comment by ZacSweers** [comment]
By default kotlin imports everything, including the default package. This has been discussed as far back as #361, please consider searching the issue tracker or discussions before filing bug reports.

Your example import is also wrong, as `@JvmName` is in the `kotlin.jvm` package, not `kotlin.`.

Lastly - you _can_ manually add default imports via `FileSpec.Builder.addDefaultPackageImport()`: https://square.github.io/kotlinpoet/1.x/kotlinpoet/kotlinpoet/com.squareup.kotlinpoet/-file-spec/-builder/add-default-package-import.html
