### ISSUE TITLE
Support expression bodies + control flow

### ISSUE THREAD

**Issue by Egorand** [square/kotlinpoet#180]
I was trying to do this:

```kotlin
FunSpec.builder("toppingPrice")
  .addParameter("topping", String::class)
  .beginControlFlow("return when (topping)")
  .addStatement("%S -> 1", "beef")
  .addStatement("%S -> 2", "lettuce")
  .addStatement("%S -> 3", "cheese")
  .addStatement("else -> throw IllegalToppingException(topping)")
  .endControlFlow()
  .build()
```

expecting this:

```kotlin
fun toppingPrice(topping: String) = when (topping) {
  "beef" -> 1
  "lettuce" -> 2
  "cheese" -> 3
  else -> throw IllegalToppingException(topping)
}
```

but got this:

```kotlin
fun toppingPrice(topping: String) {
  return when (topping) {
    "beef" -> 1
    "lettuce" -> 2
    "cheese" -> 3
    else -> throw IllegalToppingException(topping)
  }
}
```

Is this a valid use case for `beginControlFlow()`?

**Comment by JakeWharton** [comment]
Any idea what the problem is here? Is it the "$[" that gets put into the
CodeBlock before the "return" preventing the match?

**Comment by Egorand** [comment]
@JakeWharton looks like it, `EXPRESSION_BODY_PREFIX` is `"%[return "`

**Comment by Egorand** [comment]
More precisely, `beginControlFlow()` not adding `"%["` to the CodeBlock prevents the match. In the example above, CodeBlock starts with `"return when (topping)"`.

**Comment by Egorand** [comment]
Would it make more sense to recognize single expression functions at construction time, rather than during emission? I'll experiment with this idea and maybe push some code.

**Comment by swankjesse** [comment]
As-is it’s not particularly reliable.
