### ISSUE TITLE
callSuperConstructor does not generate code for its parameters

### ISSUE THREAD

**Issue by jfarrisbk** [square/kotlinpoet#1818]
**Describe the bug**
I am trying to generate a class that extends a base class. The base class has a constructor with a single parameter. The generated class should also have a single constructor parameter that is passed to the base class.  However the generated code does not pass the parameters to the super constructor.

**To Reproduce**
The class is generated with the following:
```
val baseClass = ClassName.bestGuess("com.company.something.BaseFoo")
val classBuilder = TypeSpec.classBuilder(generatedClassName)
    .superclass(baseClass)
    .primaryConstructor(
        FunSpec.constructorBuilder()
            .callSuperConstructor(CodeBlock.of("%L", "param"))
            .addParameter(
                name = "param",
                type = ClassName.bestGuess("com.company.something.BaseFoo.FooProp")
            )
            .build()
    )
```

This generates:
```
public class GeneratedClass(
    param: BaseFoo.FooProp,
) : ExtendedPreviewSnapshotTest() {
...
}
```

**Expected behavior**
That the param passed in `callSuperConstructor` would be applied.
```
public class GeneratedClass(
    param: BaseFoo.FooProp,
) : ExtendedPreviewSnapshotTest(param) {
...
}
```

**Comment by JakeWharton** [comment]
Yeah it looks like a bug that we drop that on the floor silently.

However, you can achieve what you want with `addSuperclassConstructorParameter` which is the function you are searching for. This goes on the `TypeSpec` builder, not the `FunSpec` builder.

Here's an example:

https://github.com/square/kotlinpoet/blob/9120a65935b3fe0f4576e16901f0cdf612df329b/kotlinpoet/src/commonTest/kotlin/com/squareup/kotlinpoet/TypeSpecTest.kt#L3833-L3848
