### ISSUE TITLE
Integration with okio's file system

### ISSUE THREAD

**Issue by saket** [square/kotlinpoet#1837]
**Is your feature request related to a problem? Please describe.**

I'm writing tests for verifying my codegen using `kotlinpoet`. The tests are using an in-memory file system using `okio` which is preventing me from using `FileSpec#writeTo(path.toFile())` as the file doesn't actually exist on the disk. I'm working this around using `FileSpec#writeTo(Appendable)` by manually adapting an `okio.BufferedSink` into an `Appendable`. Could `okio` handle this for me instead?

**Describe the solution you'd like**

```kotlin
class FileSpec {
  fun writeTo(fileSystem: FileSystem, path: okio.Path)
}
```

**Describe alternatives you've considered**

Offering an overload for `writeTo(OutputStream)` could also be an option, but it wouldn't allow `kotlinpoet` for [auto-creating](https://github.com/square/kotlinpoet/blob/a76ddaf36163bf416f4beeb28dc6a77232d6c6d1/kotlinpoet/src/commonMain/kotlin/com/squareup/kotlinpoet/FileSpec.kt#L108) parent directories.

**Comment by saket** [comment]
TIL about JimFS, thank you. I can use that.

**Comment by JakeWharton** [comment]
We also expose the relative path that a `FileSpec` will be written to as of 1.15.0: https://github.com/square/kotlinpoet/pull/1720.

This should make it trivial to write a three-liner extension yourself. Something like:
```kotlin
fun FileSpec.writeTo(fs: okio.FileSystem, dir: okio.Path): okio:Path {
  val out = dir.resolve(relativePath)
  fs.writeText(out, toString()) // Or whatever Okio's file system APIs are...
  return out
}
```

**Comment by saket** [comment]
Yea that's fair. I wasn't sure about using `toString()` because I was (over?)thinking about its memory usage in comparison to a buffered writer.
