### ISSUE TITLE
Redundant visibility modifier added on interfaces

### ISSUE THREAD

**Issue by j-roskopf** [square/kotlinpoet#1880]
**Describe the bug**

When generating an interface, redundant `public` modifier is added to nested types. I see in the documentation, that compatibility with explicit API mode is desired, but this modifier is not required for explicit API mode compatibility. 

**To Reproduce**

```kotlin
TypeSpec.interfaceBuilder("PageAction")
  .addModifiers(KModifier.INTERNAL)
  .addType(TypeSpec.objectBuilder("Run").build())
  .build()
```

Results in:

```kotlin
internal interface PageAction {
  public object Run
}
```

But `public` visibility modifier is redundant.

**Expected behavior**
I'd expect the public visibility modifier to not be added.

![Screenshot 2024-04-12 at 7 26 27 AM](https://github.com/square/kotlinpoet/assets/7951665/088a2cca-a3de-4816-aa63-946d7ca95933)

**Comment by JakeWharton** [comment]
This has nothing to do with `sealed`, but is instead a property of `interface` whose members and nested types are always `public`.

**Comment by j-roskopf** [comment]
That makes sense! The original info was more limiting than it needed to be. It extends beyond interfaces though to classes etc though, no?

```
internal class Class {
  private val _flow: MutableStateFlow<String> =
    MutableStateFlow("")

  public val flow: StateFlow<String>
    get() = _flow.asStateFlow()
}
```

Where `flow` is unnecessarily public. Just want to try and understand the full scope, seems like a fun first issue to try and tackle

**Comment by JakeWharton** [comment]
Ah, indeed. This is once again #1301 then!
