### ISSUE TITLE
Option to disable line wrapping

### ISSUE THREAD

**Issue by felixwiemuth** [square/kotlinpoet#1887]
**Is your feature request related to a problem? Please describe.**
Line-wrapping can cause invalid code; while the [documentation](https://square.github.io/kotlinpoet/functions/#spaces-wrap-by-default) suggests to use non-breaking spaces to prevent this, this is cumbersome and error-prone (one might oversee situations like a simple `return x`).

Related but more complicated: #1138 (custom limit for line length).

**Describe the solution you'd like**
Regarding that generated code is not meant to be read (and even without line-wrapping, with default formatting it should generally read well), the option to completely disabling line-wrapping would be a simple solution. I am not aware of a line-length limit from the Kotlin compiler, which of course would be an issue.

**Describe alternatives you've considered**
A workaround is defining this extension function on `String` to replace all spaces with non-breaking spaces and applying it on all code-strings passed to Kotlinpoet.
```kotlin
fun String.nbs() = replace(' ', '·')
```
If I am correct, this should prevent all line-breaking which could cause invalid code.
This could also be a user option for Kotlinpoet (automatically replacing all spaces in user-provided code with non-breaking spaces) but then only code provided as strings is not wrapped; an option to disable line-wrapping completely would be the cleaner solution.

**Comment by JakeWharton** [comment]
#1314 tracks changing this. Please voice your opinion there. I'm not a huge fan of adding arbitrary options which create a ton of knobs, but in this case it would be an easy way to start getting this functionality in the hands of users (myself included).
