### ISSUE TITLE
Line Break Issue  causing compilation error

### ISSUE THREAD

**Issue by rulogarcillan** [square/kotlinpoet#1918]
**Describe the bug**
I am experiencing an issue with KotlinPoet's automatic line wrapping when generating code. The specific problem occurs with the following code:

```kotlin
internal val LocalThemeSpacing: ProvidableCompositionLocal<ThemeSpacing> = staticCompositionLocalOf { ThemeSpacing() }
```

KotlinPoet inserts a line break at the word `staticCompositionLocalOf` when it reaches 100 characters, resulting in code like this:

```kotlin
internal val LocalThemeSpacing: ProvidableCompositionLocal<ThemeSpacing> = staticCompositionLocalOf
{ ThemeSpacing() }
```

This causes a compilation error in Kotlin because it cannot interpret the block correctly. The code should be generated keeping `{ ThemeSpacing() }` on the same line as `staticCompositionLocalOf` or moving the entire `staticCompositionLocalOf` expression to the next line, like this:

```kotlin
internal val LocalThemeSpacing: ProvidableCompositionLocal<ThemeSpacing> =
    staticCompositionLocalOf { ThemeSpacing() }
```

**Expected behavior**
I expect KotlinPoet to keep the expression `{ ThemeSpacing() }` on the same line as `staticCompositionLocalOf` or move the entire `staticCompositionLocalOf` expression to the next line to avoid compilation errors.

**How to reproduce**
This is a small playground to generate a file similar to mine:

```kotlin
// Define class names
val PROVIDABLE_COMPOSITION_LOCAL = ClassName("androidx.compose.runtime", "ProvidableCompositionLocal")
val THEME_SPACING = ClassName("com.example.theme", "ThemeSpacing")

fun createPropertySpec(): PropertySpec {
    return PropertySpec.builder(
        "LocalThemeSpacing",
        PROVIDABLE_COMPOSITION_LOCAL.parameterizedBy(THEME_SPACING),
        KModifier.INTERNAL
    )
        .initializer("staticCompositionLocalOf { ThemeSpacing() }")
        .build()
}

fun main() {
    val propertySpec = createPropertySpec()

    val fileSpec = FileSpec.builder("com.example", "Theme")
        .addProperty(propertySpec)
        .build()

    // Define the directory to save the file
    val outputDir = Paths.get("/Users/XXXXXXXXX") // Change this to your desired directory
    fileSpec.writeTo(outputDir)
}
```

**Additional context**
- KotlinPoet version: 1.17.0
- Kotlin version: 1.9.21
- Operating System: [please specify your operating system]

This issue affects the generation of code that relies on precise line breaks to maintain the validity of Kotlin code. I would appreciate it if you could review this behavior and consider an adjustment to handle these cases correctly.

This is an example class to show that if you import the Compose and Kotlin libraries, this file does not compile and it is exactly the output I receive:

```kotlin
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.ProvidableCompositionLocal
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp


@Immutable
public data class ThemeRadius(public val radius00: Dp = 0.dp)

internal val LocalThemeRadius: ProvidableCompositionLocal<ThemeRadius> = staticCompositionLocalOf
  { ThemeRadius() }
```

**Comment by Egorand** [comment]
Please see [Spaces wrap by default!](https://square.github.io/kotlinpoet/functions/#spaces-wrap-by-default). In your case, you'd need to specify that one of the spaces in your input is non-wrapping:

```kotlin
.initializer("staticCompositionLocalOf·{ ThemeSpacing() }")
```

Feel free to reopen the issue if this suggestion doesn't help!
