### ISSUE TITLE
KSAnnotation.toAnnotationSpec() fails if the KSAnnotation is a typealias to another Annotation

### ISSUE THREAD

**Issue by milis92** [square/kotlinpoet#1945]
**Describe the bug**

Consider following scenario:
```kotlin
annotation class SomeAnnotation
typealias SomeOtherAnnotation = SomeAnnotation

@SomeOtherAnnotation
fun doSomething() {
}
```
Calling `KSAnnotation.toAnnotationSpec()` on the `doSomething` function annotations, KSP will throw:

```
e: java.lang.ClassCastException: class com.google.devtools.ksp.impl.symbol.kotlin.KSTypeAliasImpl cannot be cast to class com.google.devtools.ksp.symbol.KSClassDeclaration (com.google.devtools.ksp.impl.symbol.kotlin.KSTypeAliasImpl and com.google.devtools.ksp.symbol.KSClassDeclaration are in unnamed module of loader 'app')
	at com.squareup.kotlinpoet.ksp.AnnotationsKt.toAnnotationSpec(Annotations.kt:48)
	at com.squareup.kotlinpoet.ksp.AnnotationsKt.toAnnotationSpec$default(Annotations.kt:35)...
```

**Expected behavior**
- I would expect this to work, without errors.
- `KSAnnotation.toAnnotationSpec()` should return resolved annotation

**Additional context**
https://github.com/square/kotlinpoet/blob/79ec8a42447a94db5b738fa303c8d433ad459bcb/interop/ksp/src/main/kotlin/com/squareup/kotlinpoet/ksp/Annotations.kt#L48

This seems like it should be a safe cast to KSClassDeclaration

**Comment by ZacSweers** [comment]
Thanks for the report, I've got a branch with a fix in the works
