### ISSUE TITLE
map kotlin.FunctionX types in KSType.toTypeName()

### ISSUE THREAD

**Issue by F43nd1r** [square/kotlinpoet#1971]
**Is your feature request related to a problem? Please describe.**
KSP `KSType.toTypename()` does not map `kotlin.FunctionX` types to `LambdaTypeName`.
Relevant code: https://github.com/square/kotlinpoet/blob/b3d17acba0fedee264996998dafcb08585afb1b6/interop/ksp/src/main/kotlin/com/squareup/kotlinpoet/ksp/KsTypes.kt#L89-L91

This leads to issues in generated code, especially with receivers.

**Describe the solution you'd like**
I'd like `KSType.toTypeName()` to map from `kotlin.FunctionX` types to `LambdaTypeName`, just like it already is done for `KmType.toTypeName()`. 
Relevant code: https://github.com/square/kotlinpoet/blob/b3d17acba0fedee264996998dafcb08585afb1b6/interop/kotlin-metadata/src/main/kotlin/com/squareup/kotlinpoet/metadata/specs/KmTypes.kt#L103-L134

**Describe alternatives you've considered**
Alternative is to manually post-process the result of `toTypeName` and do the mapping myself.

**Additional context**
I'm implementing an annotation processor which supports both KSP and KAPT, so I'm using KSType or KmType respectively and it'd be great if the APIs would behave the same.

**Comment by ZacSweers** [comment]
PR welcome!

**Comment by F43nd1r** [comment]
Started to implement this, but then I noticed it seems the current behaviour for KSP is intended:
https://github.com/square/kotlinpoet/blob/b3d17acba0fedee264996998dafcb08585afb1b6/interop/ksp/test-processor/src/main/kotlin/com/squareup/kotlinpoet/ksp/test/processor/TestProcessor.kt#L189-L190

I was able to use `KSTypeReference.toTypeName()` in my case. 

Still a bit unfortunate that KSP and KM don't behave the same, but it's rooted in the information available in each case.
Seems like with KM you can never know if a FunctionN was actually a lambda type in source or not, so I guess just mapping them always is as good as it can be.

Then I was trying to add parameter name support to the existing functionality, but it seems like there is [a KSP2 bug](https://github.com/google/ksp/issues/2056).

**Comment by ZacSweers** [comment]
Ah, yeah we'd prefer correctness over style in this case. Happy to revisit if it's possible down the line
