### ISSUE TITLE
Support adding a superinterface for TypeSpec by constructor parameter delegation

### ISSUE THREAD

**Issue by prestongarno** [square/kotlinpoet#198]
I can't find anything about this in the docs, but I'm currently accomplishing this by string replace after building the types. Something like 

`TypeSpec::addSuperinterface(parameter: ParameterSpec)`

to generate a class with the `: <Type> by <constructor parameter>` signature

**Comment by Egorand** [comment]
That would be nice to have! Wanna submit a PR? I'm thinking about smth as simple as `addDelegate(delegateName: String)`

**Comment by prestongarno** [comment]
My bad, didn't see your comment until now. I added it as a `ParameterSpec`, I'll link it once I push my changes, let me know what you think
