### ISSUE TITLE
Don't emit paramtere type

### ISSUE THREAD

**Issue by wooky** [square/kotlinpoet#200]
If I have a statement like
```kotlin
val test: String = "Hello world!"
```
the compiler is smart enough to figure out that it's a string without having to specify `: String` above. I think parameter types should be optional for cases like these.

**Comment by Egorand** [comment]
There was a discussion on this in #99

**Comment by JakeWharton** [comment]
Solving this generally is non-trivial and since being explicit is never a bad thing, we have no plans to support this at this time.
