### ISSUE TITLE
`toClassName` throws exception

### ISSUE THREAD

**Issue by vendelieu** [square/kotlinpoet#2016]
**Describe the bug**
Using `toClassName` within ksp processor and in new version it returns error because of `check(arguments.isEmpty())`.

**To Reproduce**

Source:
```kotlin
interface TestInterface<T : Any>

@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.SOURCE)
annotation class MyAnnotation

data class TestEntity(val value: Int)

@MyAnnotation
class TestClass : TestInterface<TestEntity>
```

KSP Processor:
```kotlin
getSymbolsWithAnnotation(MyAnnotation.qualifiedName!!).filterIsInstance<KSClassDeclaration>()
                .getAllSuperTypes()
                .first { it.toClassName() == TestInterface::class.asClassName() }
```

```
[ksp] java.lang.IllegalStateException: KSType 'TestInterface<TestEntity>' has type arguments, which are not supported for ClassName conversion. Use KSType.toTypeName().
```

**Expected behavior**
in 1.18.1 version everything works fine :)

**Comment by ZacSweers** [comment]
This is WAI. `toClassName()` is only for types you know are not generic

**Comment by vendelieu** [comment]
> This is WAI. `toClassName()` is only for types you know are not generic

so basically more likely behav in previous version was wrong :/

I should use toTypeName? My goal is to know is interface is used by class doesn't matter which generic is used

**Comment by Egorand** [comment]
Curious what could've caused the regression, perhaps the difference in KSP versions?

**Comment by vendelieu** [comment]
> Curious what could've caused the regression, perhaps the difference in KSP versions?

actually with same ksp version but with previous kotlinpoet version everything works just fine :)
