### ISSUE TITLE
Can't create constructor with no body

### ISSUE THREAD

**Issue by Egorand** [square/kotlinpoet#208]
Noticed while working on #207. Technically, constructors without a body are allowed:

```kotlin
class Taco {
  constructor(a: Int)
}
```

However, there's no way to prevent `FunSpec` from adding an empty body, i.e. the following:

```kotlin
FunSpec.constructorBuilder()
    .addParameter("a", Int::class)
    .build()
```

will produce:

```kotlin
constructor(a: kotlin.Int) {
}
```

If needed, empty body can be added with `addCode("")`.

**Comment by JakeWharton** [comment]
Sounds like another reason to have a ConstructorSpec then?

**Comment by JakeWharton** [comment]
Maybe not: there's a need for functions with no bodies: https://github.com/square/kotlinpoet/issues/209

**Comment by Egorand** [comment]
I guess we can use `abstract` for functions inside a `header` type, plus maybe add a check inside the `TypeSpec.Builder` that every function inside that type is `abstract`. Logic for recognizing an empty constructor is different though, so I would still try the split, will see how that goes.
