### ISSUE TITLE
Default interface method implementation

### ISSUE THREAD

**Issue by AlecStrong** [square/kotlinpoet#210]
```kotlin
interface Foo {
  fun bar(): Int = 10
}
```

ideal api
```kotlin
interfaceSpec.addFun(FunSpec.builder("bar")
          .returns(column.type())
          .addStatement("return 10") // IDK if single line returns are supported
          .build())
```

current exception:

`must have modifier [ABSTRACT]`

which is probably reasonable, but if I add that then I get

`abstract function bar cannot have code`

**Comment by AlecStrong** [comment]
on second thought it might be more reasonable to write 

```kotlin
interfaceSpec.addFun(FunSpec.builder("bar")
          .addModifier(OPEN)
          .returns(column.type())
          .addStatement("return 10") // IDK if single line returns are supported
          .build())
```

since OPEN implys overwritable & implemented

**Comment by Egorand** [comment]
@AlecStrong which version do you use? I was fixing smth like this in #196, let me quickly check if your test case passes with 0.5.0-SNAPSHOT

**Comment by AlecStrong** [comment]
im using 0.4.0

**Comment by Egorand** [comment]
Yep, snapshot should work, one-liners also supported. Not sure about `open`, from Kotlin's perspective it's redundant, and from the library perspective it's enough to know there's a body to recognize the method as default.

**Comment by AlecStrong** [comment]
awesome, i'll confirm it works on my branch. Thanks dude!

**Comment by AlecStrong** [comment]
hype! works great! https://github.com/square/sqldelight/pull/651/files#diff-4c2b009b26e73cc5a67476450cecebcfR42

**Comment by Egorand** [comment]
Great stuff! Happy to help on SqlDelight generating Kotlin, gonna take a closer look at that PR!
