### ISSUE TITLE
Fix new line emission after single-expression functions

### ISSUE THREAD

**Issue by Egorand** [square/kotlinpoet#213]
According to the style guide, there should be an empty line between functions. `TypeSpec` emits a `\n` character in between the functions, but there should be another `\n` to get the empty line. Standard functions that have `{}` around the body do emit `\n` at the end, but single-expression functions don't, so currently the body has to contain `\n` as the last character. Simply appending `\n` at the end when emitting single-expression functions won't solve it, as there can already be a `\n` at the end of the body (standard functions are guaranteed to have `}` as the last character), so we'll have to do a check to avoid duplicate `\n`.

**Comment by Egorand** [comment]
I wonder if `FunSpec` should fully manage its empty line emission, rather than relying on `TypeSpec` or `KotlinFile` to finish the job. That way we reduce duplication but potentially introduce problems in contexts where the empty line between functions is not needed (are there any?)

**Comment by swankjesse** [comment]
I think it’s actually already doing the right thing. If you’re generating statements, you’re responsible for terminating those statements with `\n`. Otherwise the newlines or `}` characters get misplaced. This isn’t unique to expression bodies.

```
  @Test fun expressionBodyAndNewline() {
    val source = KotlinFile.builder(tacosPackage, "Taco")
        .addFunction(FunSpec.builder("commentStatement")
            .returns(String::class)
            .addComment("This comment prevents an expression body!")
            .addStatement("return %S", "commentStatement")
            .build())
        .addFunction(FunSpec.builder("commentCodeNoNewline")
            .returns(String::class)
            .addComment("This comment prevents an expression body!")
            .addCode("return %S", "commentCodeNoNewline")
            .build())
        .addFunction(FunSpec.builder("statement")
            .returns(String::class)
            .addStatement("return %S", "statement")
            .build())
        .addFunction(FunSpec.builder("codeNoNewline")
            .returns(String::class)
            .addCode("return %S", "codeNoNewline")
            .build())
        .addFunction(FunSpec.builder("noop")
            .returns(Unit::class)
            .build())
        .build()
    assertThat(source.toString()).isEqualTo("""
        |package com.squareup.tacos
        |
        |import kotlin.String
        |import kotlin.Unit
        |
        |fun commentStatement(): String {
        |  // This comment prevents an expression body!
        |  return "commentStatement"
        |}
        |
        |fun commentCodeNoNewline(): String {
        |  // This comment prevents an expression body!
        |  return "commentCodeNoNewline"}
        |
        |fun statement(): String = "statement"
        |
        |fun codeNoNewline(): String = "codeNoNewline"
        |fun noop(): Unit {
        |}
        |""".trimMargin())
  }
```

I think users should supply a `\n` at the end of every statement in KotlinPoet, just as they supply a `;\n` with every statement in JavaPoet. The last statement in the function isn’t special!
