### ISSUE TITLE
Format multiline constructors (and methods) according to style guide

### ISSUE THREAD

**Issue by AlecStrong** [square/kotlinpoet#218]
https://kotlinlang.org/docs/reference/coding-conventions.html

```kotlin
data class Person(
    override val id: Int, 
    override val name: String,
    override val surname: String
)
```

instead of 

```kotlin
data class Person(override val id: Int, override val name: String,
    override val surname: String)
```

as a developer its desirable because it makes testing generated code easier - if only one param changes the error diff is less cluttered.

**Comment by Egorand** [comment]
Nice! The doc says "Classes with a few arguments can be written in a single line", and defining what "few" means is up to the developer, so it's gonna be harder in our case. Should we go for separate lines when there's more than 1 parameter?

**Comment by AlecStrong** [comment]
the practise ive gone with is if the parameter list would wrap lines. im also fine with > 1 parameter
