### ISSUE TITLE
readme code dun work

### ISSUE THREAD

**Issue by AlecStrong** [square/kotlinpoet#220]
hey i copy paste readme and says filespec dont exist

**Comment by AlecStrong** [comment]
ill see myself out

**Comment by JakeWharton** [comment]
![](http://vignette2.wikia.nocookie.net/soniczombie/images/0/0a/Nightmare_fuel.png/revision/latest?cb=20150702141720)

**Comment by AlecStrong** [comment]
![shrek-farquaad-thumb2-web](https://user-images.githubusercontent.com/1675456/30121101-ba7eb862-92f8-11e7-89cf-533d8905179c.jpg)
