### ISSUE TITLE
Switch from j.l.m.Modifier to KVisiblity and friends?

### ISSUE THREAD

**Issue by JakeWharton** [square/kotlinpoet#23]
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.reflect/-k-visibility/index.html

`Modifier` has things like `static` which aren't in Kotlin, it lacks `internal`, and there's things like `const` and `override` to contend with. We might want to do `KVisibility` + our own `KModifier`.

**Comment by swankjesse** [comment]
All done with `KModifier`.
