### ISSUE TITLE
Support parameterized functions.

### ISSUE THREAD

**Issue by NightlyNexus** [square/kotlinpoet#244]
`FunSpec.builder("foo").addParameter("foo", TypeVariableName.of("T", emptyList(), null)).build()`
makes
```kotlin
fun foo(foo: T) {
}
```

Should it make the following? Is there a way to make the following at all yet?
```kotlin
fun <T> foo(foo: T) {
}
```

**Comment by JakeWharton** [comment]
It shouldn't be automatic because it might be a class type parameter, but
there should be a builder method to add it.

**Comment by NightlyNexus** [comment]
👍
Should the parameter should also allow `reified` but only if the function is `inline`? Not that the first pass has to include that, but that seems tricky (ordering builder functions on FunSpec).

**Comment by Egorand** [comment]
`addTypeVariable()` is supported for `FunSpec`: [TypeVariableNameTest.kt](https://github.com/square/kotlinpoet/blob/master/src/test/java/com/squareup/kotlinpoet/TypeVariableNameTest.kt). 

I can add `reified` support. Regarding the check for `inline`, we can either make it in `build()`, or leave it to the user to validate. I'll go with the first option, and we can drop it later if not needed.

**Comment by JakeWharton** [comment]
I think we can let the Kotlin compiler validate it.
