### ISSUE TITLE
Check packageName components for keywords

### ISSUE THREAD

**Issue by mannodermaus** [square/kotlinpoet#247]
The following will generate an invalid package name because of the `in` keyword in one of its components:

```kotlin
@Test fun keywordInPackageName() {
  val source = FileSpec.builder("com.squareup.in", "California")
      .build()
  assertThat(source.toString()).isEqualTo("""
      |package com.squareup.in
      |
      |""".trimMargin())
}
```

Would it be advisable to automatically adjust the emitted code to include the grave accents around keywords (i.e. ``` package com.squareup.`in` ```)? If not, should we extend the [existing sanity checks in FileSpec.Builder](https://github.com/square/kotlinpoet/blob/4b0e6e2b714bfbee559498c4f14db2c4e6605a41/src/main/java/com/squareup/kotlinpoet/FileSpec.kt#L177) to validate the `packageName` components at initialization time as well, and fail quickly on reserved keywords?

**Comment by JakeWharton** [comment]
Yeah we should emit backticks.

**Comment by mannodermaus** [comment]
I'll prepare a PR shortly.

**Comment by JakeWharton** [comment]
Thanks!

**Comment by mannodermaus** [comment]
Raised as #248

**Comment by hotchemi** [comment]
Wow really nice work!
