### ISSUE TITLE
Add support for renamed imports

### ISSUE THREAD

**Issue by Egorand** [square/kotlinpoet#253]
Should be able to generate the following:

```kotlin
import java.lang.String as JString
import kotlin.String as KString

val a: JString = JString("a")
val b: KString = "b"
```

**Comment by JakeWharton** [comment]
Can you file the bug separately from the feature request? The example
should work as-is.

**Comment by Egorand** [comment]
I figured that my example is broken, one has to use `java.lang.String::class.java` to be able to import `java.lang.String`, and the library handles it correctly. I'll update the description to leave just the feature request part.
