### ISSUE TITLE
Function type variables do not line wrap

### ISSUE THREAD

**Issue by saik0** [square/kotlinpoet#255]
```kotlin
val t = TypeVariableName("T")

val file = FileSpec.builder("", "Foo")
        .addFunction(FunSpec.builder("foo")
                .addTypeVariables(generateSequence { t }.take(100).asIterable())
                .build())
        .build()

file.writeTo(System.out)
```

outputs:
```kotlin
fun <T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T> foo() {
}

```

**Comment by JakeWharton** [comment]
I'm not sure we want to wrap these even if they surpass the column limit.

Is this just a hypothetical case or do you actually have methods with enough type parameters to exceed the column limit.

**Comment by saik0** [comment]
Came across it when generating N-ary zips. Just a suggestion, it's all the same to kotlinc of course =)

**Comment by JakeWharton** [comment]
I tried it in IntelliJ and it doesn't wrap them either. I'd be curious what the JetBrains folk have to say about the wrapping rules when something like this happens.

**Comment by Egorand** [comment]
I don't think we'll ever be fixing this. Style guide doesn't offer advice on this scenario, so we'll just stick to the current behavior.
