### ISSUE TITLE
Generating lambdas with parameters

### ISSUE THREAD

**Issue by saik0** [square/kotlinpoet#257]
Is there some function for generating `{ foo, bar -> ... }` similar to `beginControlFlow`? If not what should it be?

**Comment by JakeWharton** [comment]
Right now you could use `%>` and `%<` to cause automatic indent after the `{` and before the `}` characters, respectively, but it's definitely not great. We should come up with something.

**Comment by swankjesse** [comment]
This works now.

```
beginControlFlow("list.forEach { element ->")
```
