### ISSUE TITLE
Improve formatting of property initializers

### ISSUE THREAD

**Issue by Egorand** [square/kotlinpoet#259]
There are different formatting rules for property initializers, few examples below:

```kotlin
val a = "Hello !"
    .trim()
    .toLong()

val b = """
  a
  b
  c
  """

val c = { x: Int, y: Int ->
  x + y
}
```

Current implementation wraps the entire initializer in a statement, applying double indentation to every new line, hence the last example will be formatted as:

```kotlin
val c = { x: Int, y: Int ->
      x + y
    }
```

**Comment by Egorand** [comment]
Using `%[%L%]` is clearly incorrect, so I suggest we remove it and go with just `%L`. From there we can go two ways:

- (simple, bad) Leave it to the user to define proper formatting if needed
- (hard, good) Recognize different types of code blocks (such as chained method calls, multiline strings, lambda expressions) and apply specific formatting rules

**Comment by swankjesse** [comment]
I think (simple, bad) is probably better.

**Comment by Egorand** [comment]
Fair. I'll prepare a PR

**Comment by Egorand** [comment]
Based on #260 and #261, the direction to go would probably be to improve the indentation rules for statements: we should be able to recognize statement type and pick correct indentation strategy.

**Comment by swankjesse** [comment]
Stalling this for now. May revisit later!
