### ISSUE TITLE
Provide some escape hatch to allow generating funs using Java keywords as name

### ISSUE THREAD

**Issue by helpermethod** [square/kotlinpoet#262]
While Kotlin seems perfectly fine to use Java keywords in method names (as long as you escape them in backticks) it seems `FunSpec` is not.

I'm currently migrating an XML-based DSL to Kotlin (basically a 1:1 conversion) which makes use of Java keywords.

Would be lovely if I could somehow disable the check for reserved keyword.

**Comment by JakeWharton** [comment]
Got a stacktrace? What version are you using?

**Comment by helpermethod** [comment]
Sample code

```kotlin
FunSpec
	.builder("if")
	.build()

Stacktrace

> Exception in thread "main" java.lang.IllegalArgumentException: not a valid name: if
>     at com.squareup.kotlinpoet.FunSpec$Builder.<init>(FunSpec.kt:180)
>     at com.squareup.kotlinpoet.FunSpec$Companion.builder(FunSpec.kt:361)

I'm currently using version 0.5.0.

**Comment by Egorand** [comment]
That would be great to have, now that we've got package name escaping (#248) and `Util.escapeIfKeyword()` function. Wanna submit a PR?

**Comment by helpermethod** [comment]
@Egorand I'll give it a try ;).

**Comment by helpermethod** [comment]
I guess adding an additional boolean parameter with default value could do the trick, something like

    FunSpec.builder(name = "if", withEscaping = true)

where `withEscaping` is set to `false` by default.

That way, no backward-incompatible is introduced.

What do you think?

**Comment by Egorand** [comment]
In #248, escaping happens implicitly, so I'd say that would be the way to go to keep the behavior consistent. Another argument for that is that `FunSpec.builder("if", withEscaping = false)` will never produce compilable code, so it hardly makes sense. 

`FunSpec.builder("if")` doesn't work in 0.5.0, so we're not breaking anybody's code in any case.
