### ISSUE TITLE
LambdaTypeName parameter names

### ISSUE THREAD

**Issue by JakeWharton** [square/kotlinpoet#269]
```kotlin
(name: String) -> Unit
```

This also works, but is weird
```kotlin
fun ((name: String) -> Unit).whatever() = Unit
```

**Comment by Egorand** [comment]
Is it for documentation purposes only? Don't see any practical reason. Should we support it?

**Comment by JakeWharton** [comment]
Sort of. When you implement the type you get the semantic name for free.
It's the same reason you would name an argument in a SAM type in Java.

**Comment by Egorand** [comment]
Yeah, makes sense. I'll look into it
