### ISSUE TITLE
Escape parameter name in ParameterSpec which is also a Kotlin keyword

### ISSUE THREAD

**Issue by helpermethod** [square/kotlinpoet#293]
Hi,

I'm currently migrating an XML based DSL to a Kotlin based one and the problem is that Kotlin / Java keywords are used all over the place.

One place where this haunts me is the generation of Parameter names.

Would it be possible to automatically escape parameter names like in #262?

I could submit a PR if you'd like.

**Comment by Egorand** [comment]
Sounds good! See no reason not to have it.
