### ISSUE TITLE
the retract of each line is not a TAB instead of a Space

### ISSUE THREAD

**Issue by fly7632785** [square/kotlinpoet#301]
Hi，It seems the retract of each line is just a Space 
It means I need to format it each time when I generate it.
```
class OtherFragment : BaseMenuToolbarFragment() {
  @Inject // one space distance
  lateinit var presenter: OtherPresenter

  lateinit var binding: OtherFragmentBinding
```
when I format it with AS
```
class OtherFragment : BaseMenuToolbarFragment() {
    @Inject // one tab distance 
    lateinit var presenter: OtherPresenter

    lateinit var binding: OtherFragmentBinding
```
Is that normal?
or any solution else ?

**Comment by JakeWharton** [comment]
You can change the indent on `FileSpec.Builder`. in general, you shouldn't care that much about the format of generated code. We do a best effort to make it readable but it will never exactly match every style nuance (and it definitely will never emit tabs by default!).

**Comment by Egorand** [comment]
0.7.0-SNAPSHOT switched to 4-space indentation
