### ISSUE TITLE
How to generate a .kt file in actual generated output folder?

### ISSUE THREAD

**Issue by Muyangmin** [square/kotlinpoet#310]
Sorry I know this is a stupid question, but I'm a newbie and struggled for this question over than 24 hrs.

### Description
I've implemented a processor (via Kotlin) extends AbstractProcessor and I want to generate a Kotlin class named `Contract.kt`, like this: 
```Kotlin
class Contract{
  class Activity1 {
    companion object {
      const val SCHEME: String = "page/1"
    }
  }
}
```
when I use the following:
```Kotlin
        FileSpec.builder(packageName, className)
                .addComment("This class is generated for router contract, do not modify.")
                .addType(topLevelClass.build())
                .build()
                .writeTo(System.out)
```
it works fine, what output in console is expected. But when I try to change "System.out" to `build` folder,  I get a series of exceptions. **I don't know how to pass argument for `writeTo(Path/File/Appendable)` methods.**

### What I've tried
I found [JavaPoet](https://github.com/square/javapoet) has an api `writeTo(Filer)`, but this method is unavailable in `KotlinPoet`.

I tried to read [Filer documentaion- Oracle Java SE 7](https://docs.oracle.com/javase/7/docs/api/javax/annotation/processing/Filer.html), and use following:
```Kotlin
val writer = mFiler.createSourceFile("$className.kt")
FileSpec./*...*/.writeTo(writer())

writer.close()
```
But I got a lots of compile errors about "missing semicolon" and "Illegal expressions", since it do **create files , but was "kt.java"**.

I also tried `Filer#createClassFile()` and `File.createTempFile()`, but none of them works as expected.

Also tried to search on Google and StackOverflow, but failed.

I believe I'm doing something wrong but I don't know where, could someone help me?

**Comment by oldergod** [comment]
You can have a look at [kotlinpoet/FileWritingTest.kt](https://github.com/square/kotlinpoet/blob/master/src/test/java/com/squareup/kotlinpoet/FileWritingTest.kt) for an idea on how to write your `FileSpec` to disk.

If you still struggle to get it working, please ask a question on [StackoverFlow](https://stackoverflow.com) and only hours will pass before you receive help!

**Comment by JakeWharton** [comment]
It sounds like the question is specifically about how to do it in an
annotation processor running inside kapt to which I don't know if it's
possible.

**Comment by Muyangmin** [comment]
Thanks very much for your reply @oldergod @JakeWharton 👍 .

In fact before I opened this issue I did have read [FileWritingTest](https://github.com/square/kotlinpoet/blob/master/src/test/java/com/squareup/kotlinpoet/FileWritingTest.kt). It uses `Jimfs`, which is a in memory file system, but what I'm look for is actual project path.  Anyway, thanks for your attention.

## Resolusion

Finally I seemed find out a solution, I found that [Filer](https://docs.oracle.com/javase/7/docs/api/javax/annotation/processing/Filer.html) can actually create "auxiliary resource files" and I can **sepecify its location**(this is important):

```Kotlin
    val kotlinFileObject = filer.createResource(StandardLocation.SOURCE_OUTPUT,
            packageName, "$className.kt")
    val writer = kotlinFileObject.openWriter()
    //...
```

This finally generates a `.kt` file in the `{app}/build/generated/source/kapt/debug` folder. And it can be recognized and compile into apk by `kotlin-apt` plugin.
```Groovy
apply plugin: 'kotlin-kapt'

dependencies {
    kapt project(":XXX-compiler")
}
```

---

## Discusion
It seems to be a little misnomer: I tell filer to create a **"resource file"** which has a suffix `.kt`, but its actual location and usage is source file.  In fact in decompiled `JavacFiler` I found this: 
```Java
public JavaFileObject createSourceFile(CharSequence var1, Element... var2) throws IOException {
    return this.createSourceOrClassFile(true, var1.toString());
}

public JavaFileObject createClassFile(CharSequence var1, Element... var2) throws IOException {
    return this.createSourceOrClassFile(false, var1.toString());
}

private JavaFileObject createSourceOrClassFile(boolean var1, String var2) throws IOException {
    //...
    String var5 = var1?".java":".class";
}
```
It hard coded source file extension as ".java". So maybe this is the only way to create `.kt` file? :confused::stuck_out_tongue_closed_eyes:

One thing I still not understand is that, this generated file cannot work well with builtin `kapt` (that is, do not `apply 'kotlin-kapt'`). It can be referenced by other code normally in the IDE, but when I try to build apk or run apk will failed.
