### ISSUE TITLE
How often are new snapshot versions published?

### ISSUE THREAD

**Issue by helpermethod** [square/kotlinpoet#314]
Hi,

I've tried depending on the snapshot repository only to realize the latest version is pretty old. Shouldn't snapshot versions be updated on each accepted PR?

**Comment by JakeWharton** [comment]
They should be published automatically, yes. I'll take a look today.

**Comment by helpermethod** [comment]
Thank you very much!

**Comment by oldergod** [comment]
The [latest SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/squareup/kotlinpoet/) is `0.7.0-SNAPSHOT` which has been uploaded the 31th of december, which itself is the last time code has been pushed to the `master` branch under the `src` repository.

**Comment by helpermethod** [comment]
Yes, seems to work correctly, sorry. I was looking for a commit  which hasn't been merged yet.

Guess the issue can be closed. Sorry for the confusion!
