### ISSUE TITLE
Support `dynamic` for Kotlin JS

### ISSUE THREAD

**Issue by ScottPierce** [square/kotlinpoet#321]
There doesn't seem to be any direct support for the `dyanmic` type for Kotlin JS. You can hack it together using something like:

```Kotlin
val DYNAMIC = ClassName("", "dynamic")
```

It would be nice if kotlinpoet provided support for it out of the box though.

**Comment by Egorand** [comment]
`dynamic` is just a special "type", so would support for `dynamic` consist of just having `val DYNAMIC = ClassName("", "dynamic")` declared somewhere in the library?

**Comment by ScottPierce** [comment]
I'm not 100% sure honestly. It covers the only use case that I've come across so far for dynamic, and would meet my need.
