### ISSUE TITLE
Support for KType

### ISSUE THREAD

**Issue by evgeny-pasynkov** [square/kotlinpoet#325]
when overriding KFunction, it's paramters and return types are KType

**Comment by JakeWharton** [comment]
What can't you do?

**Comment by evgeny-pasynkov** [comment]
I'm building an implementation proxy class for Kotlin interface.
I have KFunction<*> and building the stub declaration for it. 
Say, I have following interface in Kotlin:

```
interface I {
    suspend fun f(): Array<String>
}
```

When trying to build method stub, the KFunction<*>.returnType is KType, not KClass, thus none of the overloads for FunSpec.builder(...).returns suits

**Comment by JakeWharton** [comment]
So you want an `asTypeName()` extension on `KType` which produces a `ParameterizedTypeName`?

**Comment by evgeny-pasynkov** [comment]
Exactly!

**Comment by Egorand** [comment]
@evgeny-pasynkov interested in submitting a PR?

**Comment by evgeny-pasynkov** [comment]
Sure, will do my best next week

**Comment by JakeWharton** [comment]
Thanks!
