### ISSUE TITLE
Get nullability from javax.lang.model.element.Element

### ISSUE THREAD

**Issue by pavelshackih** [square/kotlinpoet#330]
Hi!

I'm trying to convert `javax.lang.model.element.Element` to `com.squareup.kotlinpoet.TypeName` from `name` field:
```
data class Bean(val name: String?)
...
val typeName = element.asType().asTypeName()
```
But `typeName.nullable` returns `false`. How can I get nullability type information in this case?

Thank you!

**Comment by swankjesse** [comment]
I don’t think the Java type knows. It’s possible we could look at a potential _usage_ of that type and inspect for a `@Nullable` annotation.

**Comment by pavelshackih** [comment]
Thank you!

Fixed it by extension:
```
fun Element.asTypeName(): TypeName {
        val annotation = this.getAnnotation(Nullable::class.java)
        val typeName = this.asType().asTypeName()
        return if (annotation == null) typeName.asNullable() else typeName
    }
```
