### ISSUE TITLE
Incorrect super constructor call for anonymous object declaration

### ISSUE THREAD

**Issue by sandwwraith** [square/kotlinpoet#332]
Given `open class Foo(val name: String)`, this code:

```kotlin
val ts = TypeSpec.anonymousClassBuilder().apply {
    superclass(Foo::class)
    addSuperclassConstructorParameter("%S", "name")
}.build()

FileSpec.builder("", "a").addType(ts).build().writeTo(System.out)
```
 produces `object : Foo() { }` instead of expected `object : Foo("name") {}`

But if I call `anonymousClassBuilder("%S", "name")`, result will be `object : Foo("name") {}`. Since method parameter called `typeArgumentsFormat` I suppose this also a wrong behaviour and output should be `object : Foo<name>() {}` (and probably method parameter type should be `TypeName` instead of `CodeBlock`).

Note if the described behaviour is correct, it's impossible to produce construction like `object : Bar<String>("some string") {}` given `open class Bar<T: Any>(val content: T)`

**Comment by NightlyNexus** [comment]
>it's impossible to produce construction like object : Bar<String>("some string") {}

How about this?
```kotlin
val anonymousClass = TypeSpec.anonymousClassBuilder()
    .superclass(ParameterizedTypeName.get(ClassName("com.example", "Bar"), String::class.asClassName()))
    .addSuperclassConstructorParameter("%S", "some string")
    .build()
```

That said, I _think_ the `anonymousClassBuilder(typeArgumentsFormat: String, vararg args: Any)` overload is redundant given `addSuperclassConstructorParameter`. If I'm correct, the overload should be removed, and `addSuperclassConstructorParameter` should be made to work with anonymous classes.

I'll send a PR tonight for discussion.
