### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by Egorand** [square/kotlinpoet#337]
JavaPoet's README is very extensive and describes a ton of use-cases. KotlinPoet's README should do the same for 1.0.

**Comment by helpermethod** [comment]
Hi,

what I also would love to see is some kind of cookbook, maybe as part of the Wiki. Would gladly contribute to such a thing.

**Comment by Egorand** [comment]
I moved over the content of JavaPoet's README, adopted it for KotlinPoet and added a few more topics which are specific to KotlinPoet. Closing this for now.

@helpermethod if there are additional things you'd like to see covered - please open issues or submit PRs, I'd be happy to make README more helpful.
