### ISSUE TITLE
Wildcard import not allowed

### ISSUE THREAD

**Issue by wulf0r** [square/kotlinpoet#349]
I am a bit suprised that I am getting 

`java.lang.IllegalArgumentException: Wildcard imports are not allowed` 

from a codegen library. I mean it really necessary to do code style policing at that level? By the way, why is the function called `addStaticImport` anyways? `static` is not really  a thing in Kotlin.

**Comment by JakeWharton** [comment]
It's more about ensuring the generated code will compile. Wildcard imports are the fastest way to breaking KotlinPoets automatic imports from working correctly.

**Comment by JakeWharton** [comment]
Plus because it's generated code you tend to know every type you interact with. It's no different than why wildcard imports aren't needed when you use an IDE. You're not managing the list, the tool is.

**Comment by Egorand** [comment]
I agree with the name change though, Kotlin has no static imports, so it should just be `addImport()`. I'll push a PR shortly.
