### ISSUE TITLE
Support multiline comments in FileSpec

### ISSUE THREAD

**Issue by Egorand** [square/kotlinpoet#358]
Add `FileSpec.addKDoc()`

**Comment by NightlyNexus** [comment]
I wasn't sure what to call the API.
Is it still called KDoc when it's only a mutiline comment?

**Comment by Egorand** [comment]
Hmm, a multiline comment before the package statement would indeed be a multiline comment, not a KDoc.

**Comment by swankjesse** [comment]
If it doesn't show up in the rendered HTML it probably isn't KDoc.

**Comment by shaishavgandhi05** [comment]
I'm interested in taking a crack at this. Is this around adding multi-line support to the `addComment` API in `FileSpec`?

**Comment by Egorand** [comment]
I actually can't recall what exactly this was about. @NightlyNexus IIRC you raised this issue, do you remember what the use case was?

**Comment by shaishavgandhi05** [comment]
I've been looking at this one and it seems like it would be a breaking change if we want to support multi-line comment via `addComment` (since `addKdoc` was discarded because of it's misrepresentation).
Right now, we just prepend every comment with `//`. We would possibly replace it with the usual:
```kotlin
/**
 * Comments here
 */
```

Does that seem acceptable?

**Comment by JakeWharton** [comment]
Wouldn't `split("\n").joinToString("\n") { "// $it" }` work?

**Comment by shaishavgandhi05** [comment]
I thought license headers have to be of format:
```
/**
 * COPYRIGHT 
 */
```

**Comment by Egorand** [comment]
What if we picked the right style based on how many lines are added to the comment `CodeBlock`? `/** */` if multiple lines and `//` if a single line?

**Comment by JakeWharton** [comment]
Is there a reason `/* */` is preferred? It's weird to switch types.

**Comment by Egorand** [comment]
I guess `/* */` is more conventional for copyright headers.

**Comment by JakeWharton** [comment]
Don't agree
