### ISSUE TITLE
Don't add default imports to generated files

### ISSUE THREAD

**Issue by gabrielhuff** [square/kotlinpoet#361]
Not sure if this was already tackled, but currently any generated code will include [default imports](https://kotlinlang.org/docs/reference/packages.html#default-imports), for instance:

```kotlin
...
import kotlin.Boolean
import kotlin.Int
import kotlin.collections.Map
...
```

Can we remove them?

**Comment by JakeWharton** [comment]
No. They disambiguate types of the same name which might be in scope. And since they don't hurt anything by being there, there's really no point in removing them.

**Comment by lsuski** [comment]
Maybe they don't hurt much but imagine this scenario
1. Optimize imports on commit enabled
2. Generate some classes
3. Commit - default imports are removed by Intellij
4. Generate again - it seems that something changed but not - you need to manually optimize imports on root generated package to see if something really changed

I think that there could be option to disable or choose what default imports will be included

**Comment by Egorand** [comment]
Normally you will not be putting generated code under source control.

**Comment by JakeWharton** [comment]
And if you were that behavior seems fine because they're not being regenerated on every build so you wouldn't get constantly dirty files/
