### ISSUE TITLE
Custom CodeWriter?

### ISSUE THREAD

**Issue by wakingrufus** [square/kotlinpoet#363]
I was hoping to use this library to generate code with html markup in order to get syntax highlighting when using poet to generate code from the html dsl. Is it currently possible to override the code writer to achieve this?

**Comment by JakeWharton** [comment]
Not really, no. How would you deal with the fact that function bodies are
opaque to KotlinPoet?

**Comment by wakingrufus** [comment]
Hmm. I didn't look that far into it. I am new to *Poet. I found myself writing a rudimentary DSL for generating that code, and realized that probably something like this probably already exists, and found kotlinpoet.
