### ISSUE TITLE
How to implement Comparable?

### ISSUE THREAD

**Issue by Fleshgrinder** [square/kotlinpoet#364]
How is it possible to implement `Comparable` for the class that is currently being generated?

There is the `ParameterizedTypeName.get(Comparable::class, ?)` method but it is unclear how the second parameter could be passed. The only thing available while generating a class is the `ClassName` of it.

Minimal example:

```kotlin
    FileSpec.builder("com.fleshgrinder", "KotlinPoet").apply {
        val className = ClassName("com.fleshgrinder", "KotlinPoet")
        addType(TypeSpec.classBuilder(className).apply {
            addSuperinterface(ParameterizedTypeName.get(Comparable::class, Any::class))
        }.build())
    }.build().writeTo(System.out)
```

Which generates:

```kotlin
package com.fleshgrinder

import kotlin.Any
import kotlin.Comparable

class KotlinPoet : Comparable<Any>
```

What I would like to have:

```kotlin
package com.fleshgrinder

class KotlinPoet : Comparable<KotlinPoet>
```

**Comment by Egorand** [comment]
Thanks for your question! However, please prefer [StackOverflow](https://stackoverflow.com/questions/tagged/kotlinpoet) for questions on usage. 

I've moved your question to StackOverflow: https://stackoverflow.com/questions/50296075/how-to-implement-comparable-in-kotlinpoet

**Comment by JakeWharton** [comment]
Invoke `asClassName()` on the `Comparable::class` which will allow you to use the `ParameterizedTypeName.get` overload that accepts two `ClassName`s instead of two `KClass` references.
