### ISSUE TITLE
How to use FunSpec.overriding?

### ISSUE THREAD

**Issue by Fleshgrinder** [square/kotlinpoet#365]
The `FunSpec` class has the very handy `overriding` method, however, it is unclear how this can be used while generating code.

Minimal example:

```kotlin
    FileSpec.builder("com.fleshgrinder", "KotlinPoet").apply {
        val className = ClassName("com.fleshgrinder", "KotlinPoet")
        addType(TypeSpec.classBuilder(className).apply {
            addFunction(FunSpec.builder("toString").apply {
                addModifiers(KModifier.OVERRIDE)
                addStatement("""return "KotlinPoet"""")
            }.build())
        }.build())
    }.build().writeTo(System.out)
```

Which generates:

```kotlin
class KotlinPoet {
    override fun toString() = "KotlinPoet"
}
```

The output it generates is perfect but the code to generate it is not.

```kotlin
FunSpec.overriding(Any::toString).apply {
    addStatement("""return "KotlinPoet"""")
}.build()
```

**Comment by Egorand** [comment]
Thanks for your question! However, please prefer StackOverflow for questions on usage.

I've moved your question to StackOverflow: https://stackoverflow.com/questions/50296204/how-to-use-funspec-overriding-in-kotlinpoet
