### ISSUE TITLE
Make packageName in FileSpec.Builder public

### ISSUE THREAD

**Issue by Fleshgrinder** [square/kotlinpoet#366]
The [`packageName` member in the `FileSpec.Builder` class](https://github.com/square/kotlinpoet/blob/master/src/main/java/com/squareup/kotlinpoet/FileSpec.kt#L172) is currently `internal` and thus not accessible from the outside. This is pretty annoying because one needs to declare a constant for the package name or repeat the same string over and over again. Having access to this member would remove this necessity.

```kotlin
FileSpec.build("com.fleshgrinder", "KotlinPoet").apply {
    val someClass = ClassName(packageName, "SomeClass")
    val anotherClass = ClassName(packageName, "AnotherClass")
    // ...
}.build().writeTo(Sytem.out)
```

It might be a good idea to directly open up the `name` as well since this might also help to reduce the amount of repetition in certain situations, e.g.:

```kotlin
FileSpec.build("com.fleshgrinder", "KotlinPoet").apply {
    val `class` = ClassName(packageName, name)
    // ...
}.build().writeTo(Sytem.out)
```

There is no harm in making them public since both properties are `val` anyways.

**Comment by Egorand** [comment]
Agree, that's a valid use-case. Wanna contribute a PR?
