### ISSUE TITLE
Impossible to define inline val

### ISSUE THREAD

**Issue by Fleshgrinder** [square/kotlinpoet#368]
The [`inline` modifier in `KModifier` is defined as `Target.FUNCTION`](https://github.com/square/kotlinpoet/blob/master/src/main/java/com/squareup/kotlinpoet/KModifier.kt#L55) only. This means that it is impossible to create an inline property.

I could have created a PR that adds `Target.PROPERTY`, however, it is not clear if this is the best approach. An inline property always requires a getter because there is nothing to inline otherwise. Hence, it might be better to create a `addInlineProperty` that requires a getter to be passed in as well. I'd know how to achieve this but it would be against the current Java-like builder pattern where the caller has to take care of everything.

Should I simply add `Target.PROPERTY`?

**Comment by Egorand** [comment]
Check out [`PropertySpecTest`](https://github.com/square/kotlinpoet/blob/1d08e1adba6194f23790c9bd72bc8d7f521c0e40/src/test/java/com/squareup/kotlinpoet/PropertySpecTest.kt#L21) to see how this is designed to work: we don't allow marking properties with `inline`, so if you need the getter to be `inline` - add the modifier to getter's `FunSpec`. If you mark both accessors as `inline` - we'll render the property as `inline`.

**Comment by Fleshgrinder** [comment]
Are these actually equivalent?

```kotlin
class Test {
    inline val a get() = "a"
    val a inline get() = "a"
}
```

Decompiling the generated class files suggests so but it looks weird.

**Comment by Egorand** [comment]
For a `val`, yes. For a `var`, these are equivalent:

```kotlin
class Test {
  inline var a
    get() = "a"
    set(a) { ... }

  var a
    inline get() = "a"
    inline set(a) { ... }
}
```

**Comment by Fleshgrinder** [comment]
OK, thanks for your help.

**Comment by Egorand** [comment]
You're welcome!
