### ISSUE TITLE
Add tests for toBuilder()

### ISSUE THREAD

**Issue by Egorand** [square/kotlinpoet#374]
Similar to #371, we need `toBuilder()` tests for other types

**Comment by mc-lovin** [comment]
Working on this 🙂

**Comment by Egorand** [comment]
We'll also need `toBuilder()` tests for:
- `FunSpec`
- `CodeBlock`
- `TypeAliasSpec`
- `AnnotationSpec`
- `ParameterSpec`
- `FileSpec`
- `PropertySpec`

**Comment by Egorand** [comment]
Fixed by #389
