### ISSUE TITLE
Better TypeName API

### ISSUE THREAD

**Issue by swankjesse** [square/kotlinpoet#382]
Creating ’em isn’t particularly idiomatic.

**Comment by JakeWharton** [comment]
![screen shot 2018-05-31 at 3 19 29 pm](https://user-images.githubusercontent.com/66577/40803219-0e3a1838-64e6-11e8-9619-0e9bb82ad362.png)

**Comment by Egorand** [comment]
Spoke to @swankjesse, a few notes:
- Variance shouldn't be a property of `TypeVariableName`, it's a property of the Spec, so the API should be smth like `TypeSpec.addTypeVariable("T", variance = IN)`
- `*` should be a constant (of `WildcardTypeName`?)
- More fluent `ParameterizedTypeName` creation APIs, e.g. `Map::class.plusParameter(String::class, variance = OUT).plusParameter(String::class)`

**Comment by Egorand** [comment]
@JakeWharton is this good to close?

**Comment by Egorand** [comment]
There's been good feedback on `parameterizedBy()` and `plusParameter()`, so I'm closing this. Feel free to reopen if there's anything to improve.
