### ISSUE TITLE
Collection-like operator behaviors

### ISSUE THREAD

**Issue by JakeWharton** [square/kotlinpoet#39]
Give all the builders `plusAssign` so that we can do things like:
```kotlin
typeBuilder += MethodSpec.builder().stuff().build()
```

**Comment by scottmeschke** [comment]
I would be interested in tackling this one, if no one else has taken it on.

**Comment by scottmeschke** [comment]
Plus assign always needs to return Unit, where as plus doesn't have those restrictions.

Kinda sucks not to be able to chain our operators with plusAssign

builder += someMethodSpec += anotherMethodSpec.

However, plus doesn't seem right as I would expect plus to returning a new thing with immutable objects, not modifier the left-side operand.

**Comment by swankjesse** [comment]
@scottmeschke wanna give it a go for a single method? I wanna make sure we’re all happy with the API before we roll it out everywhere!

**Comment by scottmeschke** [comment]
sure thing. I can do it on one of the builders. 

just need to know if we want the chaining with + or the unit return on +=
would also be good to know if where we want them?

could declare operator functions in the types themselves,
or as extension functions in a separate file or bottom of specific files

**Comment by swankjesse** [comment]
Tough question. What do other APIs do? We don’t want to be special.

**Comment by scottmeschke** [comment]
doing it now it seems messy in the class, a bunch of plus or plusAssign methods muddy up the readability. I'll go with a separate file.

**Comment by scottmeschke** [comment]
```
package com.squareup.kotlinpoet

import java.util.*
import javax.lang.model.element.Modifier

/** Operator overloads for concise building. */

/** ParameterSpec operators */

@JvmName("plusAssignAnnotationSpecs")
operator fun ParameterSpec.Builder.plus(annotationSpecs: Iterable<AnnotationSpec>): ParameterSpec.Builder {
    return addAnnotations(annotationSpecs)
}

operator fun ParameterSpec.Builder.plus(annotationSpec: AnnotationSpec): ParameterSpec.Builder {
    return addAnnotation(annotationSpec)
}

operator fun ParameterSpec.Builder.plus(annotation: ClassName): ParameterSpec.Builder {
    return addAnnotation(annotation)
}

@JvmName("plusAssignKModifiers")
operator fun ParameterSpec.Builder.plus(modifiers: Iterable<KModifier>): ParameterSpec.Builder {
    return addModifiers(modifiers)
}

operator fun ParameterSpec.Builder.plus(jvmModifiers: Iterable<Modifier>): ParameterSpec.Builder {
    return jvmModifiers(jvmModifiers)
}

fun example(){
    val cartParamBuilder = ParameterSpec.builder(type = ShoppingCart, name = "shoppingCart") + jsonFieldAnnotationSpec + KModifier.INTERNAL
    val expirationDateParamBuilder = ParameterSpec.builder(type = Date::class, name = "expirationDate") + jsonFieldAnnotationSpec + KModifier.INTERNAL

     //With more code
    val updateFunSpecBuilder = FunSpec.builder("update") + cartParam.build() + expirationDateParam.build() + updateCodeBlock
}

```

There is some awkwardness because of the build() method.
Also there will be a little awkwardness with JVM naming clashes with inheritance and the method signature.

Not sure what to do with .build() awkwardness.

Use plus assign with some useless parameter feels bad.
Use +a or one of the unary operators feels wierd too.

**Comment by swankjesse** [comment]
I gotta learn the Kotlin idioms for creating fancy models like this. The `plus` approach seems a bit like trying to use operator overloading because we can, not because it’s a great fit.

**Comment by scottmeschke** [comment]
Yeah. Could I think actually would be better to do += /plusAssign so you can

```
val typeSpec = with(TypeSpec.builder(stuff)) {
 += something
 += somethingElse
 += lastThing
 build()
}

Think that is consise, += makes more sense then the plus (even if you lose the method chaining), and it's easy to ready. 
Seems to be the direction Jake was mentioning in the DSL issue that's open.

**Comment by ronshapiro** [comment]
`plusAssign` seems weird to me, as the builders are mutable, and no reassignment needs to be done normally. but `plus` also seems like a bad idea on a mutable object.

Normally `x + y` as it's own statement would look very bizarre.

Especially since += can't return anything besides Unit, this seems unnecessary to me. The builders are very clear (but maybe I just haven't written enough Kotlin to want this).

**Comment by scottmeschke** [comment]
Builders are clear.

But it would be nice to combine the operators and the with/apply/let standard library functions to give you a nice mini-dsl. 
Saves a lot of repetition. 

But totally up to library owners and contributors whether it is a desired feature or not.

**Comment by JakeWharton** [comment]
Yeah it's too early to decide. Let's focus on output correctness first.

**Comment by JakeWharton** [comment]
There's three issues about the API. Closing this as a dupe.
