### ISSUE TITLE
KModifier class does not have an object keyword 

### ISSUE THREAD

**Issue by niniloveyou** [square/kotlinpoet#414]

**Comment by JakeWharton** [comment]
Object is not a modifier so that's expected, yes. Can you phrase the issue as a problem you are having instead of a contextless statement?

**Comment by niniloveyou** [comment]
When I want to create a singleton class

`override fun generateKotlinFile(entity: SingletonEntity): List<CodeFile> {
        val classSpec = KotlinTypeSpec.classBuilder(entity.className!!)
                .addModifiers()
                .build()

        val fileSpec = FileSpec.builder(entity.packageName, entity.className!!).build()
        return arrayListOf(CodeFile(entity.packageName, fileSpec))
    }`

**Comment by niniloveyou** [comment]
When I want to create a singleton class, like this
```
override fun generateKotlinFile(entity: SingletonEntity): List<CodeFile> {
        val classSpec = KotlinTypeSpec.classBuilder(entity.className!!)
                .addModifiers()
                .build()

        val fileSpec = FileSpec.builder(entity.packageName, entity.className!!).build()
        return arrayListOf(CodeFile(entity.packageName, fileSpec))
    }
```

**Comment by Egorand** [comment]
Use `TypeSpec.objectBuilder()` to create an object, check out [Objects](https://github.com/square/kotlinpoet#objects) for an example.

**Comment by niniloveyou** [comment]
@JakeWharton @Egorand thank you all,  I should take a closer look at Api
