### ISSUE TITLE
Generating multiline lambda function 

### ISSUE THREAD

**Issue by mc-lovin** [square/kotlinpoet#416]
``` 
val unknownFields = reader.decodeMessage { tag ->
                when (tag) {
                    1 -> name = ProtoAdapter.STRING.decode(reader)
                    2 -> id = ProtoAdapter.INT32.decode(reader)
                    3 -> email = ProtoAdapter.STRING.decode(reader)
                    4 -> phone.add(PhoneNumber.ADAPTER.decode(reader))
                    else -> UnkownFieldsBuilder.UNKNOWN_FIELD
                }
            }
```

What would be the best way to generate this ? Can we use a combination of begin / end control flow statements ?

**Comment by swankjesse** [comment]
Yep. Moshi has an example that might help.
https://github.com/square/moshi/blob/master/kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/AdapterGenerator.kt#L185

**Comment by mc-lovin** [comment]
@swankjesse in the first statement, there is some code in the same line where we begin control flow
`reader.decodeMessage { tag ->` in this case `tag -> ` iirc I tried manually generating code for the first control flow and then using the begin / end control flow for the when statement it didn't turn out to be good

**Comment by Egorand** [comment]
What if we introduced 
```
fun beginControlFlow(controlFlow: String, vararg variableNames: String)
```
which, if called like this
```
beginControlFlow("reader.decodeMessage", "tag")
```
would give you
```
reader.decodeMessage { tag ->
```
?
