### ISSUE TITLE
Allow creating TypeVariableName with no bounds and default to Any?

### ISSUE THREAD

**Issue by Egorand** [square/kotlinpoet#420]
Currently 

```TypeVariableName("T", bounds = *emptyArray<TypeName>())```

 fails with 

```java.lang.IllegalArgumentException: T has no bounds``` 

An option would be to not crash but to default bounds to `Any?`.

**Comment by hzsweers** [comment]
I can take a crack at this

**Comment by Egorand** [comment]
@hzsweers still interested in tackling this?

**Comment by Egorand** [comment]
Yeah, pretty much.
