### ISSUE TITLE
No way to get ParameterizedTypeName in RC1

### ISSUE THREAD

**Issue by shaishavgandhi05** [square/kotlinpoet#424]
In 0.7.0, you could do `ParameterizedTypeName.get()` which I see is now made `internal`. It seems that the newer API is to do something like `ClassName("kotlin", "Int").plusParameter(..)`. 

However, this extension has internal access (since it's not declared top level?). You can replicate this by creating a package under the test folder.
`com.yourname.example`

```kotlin

package com.shaishavgandhi.example

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.ParameterizedTypeName
import com.squareup.kotlinpoet.parameterizedBy
import org.junit.Test

class ParameterizedTypeTest {

    @Test fun test() {
        val typeName = ClassName("kotlin", "Int").parameterizedBy()  // Doesn't compile
    }
}
```

**Comment by shaishavgandhi05** [comment]
As I understand it, moving the extensions to top level functions will fix this. Happy to send a PR!

**Comment by Egorand** [comment]
There's no visibility problem, the functions are public, and we want them inside the companion object for Java interop. You're likely hitting the issue with IDEA where it will not auto-import an extension function that's inside a companion object. You'll have to add the import manually:

```kotlin
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.plusParameter
```

and it should work fine from there. Please let me know if this worked for you, happy to help.

**Comment by shaishavgandhi05** [comment]
Yup that works! Thanks!

On a side note, this might be hard to find since a lot of people might be using IntelliJ/Android Studio. Should we consider adding an extra top-level declaration (while also keeping the companion object one for Java interop) or something similar that will show those suggestions?

**Comment by JakeWharton** [comment]
Vote for https://youtrack.jetbrains.com/issue/KT-15286

**Comment by shaishavgandhi05** [comment]
Ahh interesting! That's a shame. Have cast my vote. 

Would it help in the meantime to possibly add a small sample in the Readme for ParameterizedTypeName?

**Comment by Egorand** [comment]
Can do!

**Comment by shaishavgandhi05** [comment]
Thanks!
