### ISSUE TITLE
API to reference top-level Kotlin entities, including package name

### ISSUE THREAD

**Issue by benjamin-bader** [square/kotlinpoet#433]
It would be great to be able to have a reference to a top-level fun or property from another file, and use it like we currently use TypeNames.  I don't know a good name for such a reference - `TopLevelReference` seems excessively vague, whereas `PropertyOrFunReference` is too Springy.  I'm totally open to better ideas!

This hypothetical reference would let us do something like:

```kt
val reference = Reference("com.foo.bar", "doSomething")
val function = FunSpec.builder("somethingElse")
    .returns(String::class)
    .addStatement("return %R()", reference)
    .build()

println(FileSpec.builder("com.example", "Example")
    .addFunction(function)
    .build())
```

and, hopefully, `CodeWriter` would handle the imports just as it does for `%T` placeholders today:

```kt
// Example.kt
package com.example

import com.foo.bar.doSomething

fun somethingElse(): String = doSomething()
```

At first, I thought this might be accomplished by using a `FunSpec` with the name I wanted, but as it happens `FunSpec` doesn't take a package name.  There doesn't seem to be any way in the current API to do this.

**Comment by benjamin-bader** [comment]
After writing the example, it strikes me that there isn't really any difference in use between this and `TypeName`, which makes me think that they're instances of the same concept, in part.

**Comment by benjamin-bader** [comment]
You know, I wonder if... we can just (ab)use a ClassName for this?  I'm not thrilled at the prospect, but it should probably work as-is.

**Comment by JakeWharton** [comment]
That's true, although the prospect of doing so makes me a bit queasy. The fact that it works out of the box is pretty funny though. Since functions can be named the same as types and are imported as such, perhaps we should actually considering changing the name of that type...

**Comment by swankjesse** [comment]
I think TypeName is also semantic: you can't declare a particular function or property as a return type for example.

But we could model a FullyQualifiedName thing that types, functions and properties could all implement.

**Comment by benjamin-bader** [comment]
I like `FullyQualifiedName`.  Are you thinking that it would be an interface implemented by `ClassName`, along with prospective types like `PropertyName` and `FunName`?

**Comment by Egorand** [comment]
@benjamin-bader sounds like a plan! Interested in taking a crack on this?

**Comment by benjamin-bader** [comment]
I'm interested, yes, but unfortunately time for coding outside of $dayjob is scarce these days.  I'm happy to try to squeeze it in, but it might be a week or two.  If you have a tighter timeline for this, please feel free to delegate to someone else.

**Comment by Egorand** [comment]
No timeline, doesn't block anything that we do. I'm happy to wait - all yours!
