### ISSUE TITLE
Cannot add superinterface to object

### ISSUE THREAD

**Issue by breandan** [square/kotlinpoet#434]
I have an object that extends a class like so:

`object MyObject: SuperInterface("...")`

Here is the KotlinPoet code:

```
TypeSpec.objectBuilder("MyObject")
              .addSuperinterface(ClassName("", "SuperInterface"), "...")
```
I receive the error:

`delegating to constructor parameter requires not-null constructor`

However, Kotlin objects may not have a constructor.

**Comment by JakeWharton** [comment]
Interfaces do not have constructors. You want supertype.

**Comment by breandan** [comment]
SuperInterface is actually class, I'm just using the KotlinPoet naming convention `addSuperinterface(...)`. How do you add a supertype to an object?

**Comment by breandan** [comment]
Nevermind, I figured out what I was was doing wrong. Here's the solution:

```
TypeSpec.objectBuilder("MyObject")
              .superclass(ClassName("","SuperInterface"))
              .addSuperclassConstructorParameter("\"...\"")
```
