### ISSUE TITLE
Adding type variable to property

### ISSUE THREAD

**Issue by alex2069** [square/kotlinpoet#437]
Kotlin: 1.2.60
KotlinPoet: 1.0.0-RC1

I'm trying to create something akin to:

```kotlin
private inline val <T : Any> KClass<T>.someFunction
    get() = stuff as T
```

I have this so far:
```kotlin
val prop = PropertySpec.builder("someFunction", TypeVariableName("T"), KModifier.PRIVATE)
    .receiver(KClass::class.asTypeName().parameterizedBy(TypeVariableName("T")))
    .getter(
        FunSpec.getterBuilder()
            .addModifiers(KModifier.INLINE)
            .addStatement("return %L", "stuff as T")
            .build()
    )
    .build()
```

Which generates:
```kotlin
private val kotlin.reflect.KClass<T>.someFunction: T
    inline get() = stuff as T
```

But without the property type variable `T` is unresolved. I tried putting it on the getter `FunSpec` but it was disallowed for getters (not surprising).

I would expect something like `.addTypeVariable(TypeVariableName("T", ANY))` to be available on the `PropertySpec` builder (or I'm just blind and missed something).

**Comment by JakeWharton** [comment]
This isn't supported. That's some crazy shit! Feel free to send a PR if you're up for it. Otherwise I suspect someone will get to it in the next week or so.
