### ISSUE TITLE
Allow inline on `PropertySpec`

### ISSUE THREAD

**Issue by alex2069** [square/kotlinpoet#438]
Kotlin: 1.2.60
KotlinPoet: 1.0.0-RC1

After wasting more time than I should've digging through the sources to no avail and eventually checking for issues and running across #368 - I finally discovered I needed to add it at the `FunSpec` level. I feel it should be permitted on the `PropertySpec` as well.

Some arguments for it:
- It feels extremely unintuitive that you can't declare a property as I feel most people would use it - that is `private inline val ...`.
- Throwing `IllegalArgumentException: unexpected modifier INLINE for PROPERTY` made me think it was an unimplemented feature.
- I suspect that many are unaware that you can inline the get/set methods individually (or maybe it's just me but I'd completely forgotten you could do so).
- It forces you to declare it twice for `var` adding yet more lines of code `.addModifiers(KModifier.INLINE)` to what could be an already large builder compared to `builder(..., KModifier.PRIVATE, KModifier.INLINE)` at the property declaration line.
- And although a bit of an unusual scenario, it forced me to take a `FunSpec` I was reusing, convert it back to a builder, add the inline modifier, and build it again (not the end of the world, but it felt a bit clunky when I feel it could've just been done on the property).

During testing I noticed you could add `inline` to the property _and_ the get/set at the same time (I'm guessing the property level declaration is just syntactic sugar for function level) - so it's fine if someone does it at all of them (though a bit weird heh).

**Comment by JakeWharton** [comment]
I thought there was another issue that discussed this, but I can't find it. Maybe it was in person or over chat.

In general KotlinPoet's (and JavaPoet's) philosophy is that you write the code to generate something more specific than what you would actually write and rely on the library to emit a more concise form when it is possible. This is an example of that. Another one is a constructor parameter, property, and property initializer collapsing into constructor property syntax.

The backing idea here is that when you change something, the generated code automatically de-sugars. For example, in the constructor param, property, and initializer case, when you rename the constructor param, rename the property, or change the initializer to something more complex, the library falls back to separating out those into individual syntactic elements automatically. You don't have to change a bunch of your code from generating a constructor property to generating a constructor argument, property, and initializer.

In this case, the idea is that if, for whatever, reason, you remove `inline` from one of the two functions the library automatically alters the generated code to support this without you having to change any other generating code. Or, conversely, if you have a non-inline setter and an inline getter but you change the setter to inline you automatically see the more concise syntax in the generated output. You didn't have to move where you declared `inline`.

I'll grant that here the value seems much less than the constructor property case. At the very least we should fix the error message to guide you in the right direction. I don't know whether we want to change our stance here though. I'll let others weigh in.
