### ISSUE TITLE
java.lang.IllegalArgumentException: Unexpected type mirror

### ISSUE THREAD

**Issue by chiara79** [square/kotlinpoet#446]
Hi, I would like to generate a class from an interface.
My interface is:

**Product.kt:** 
```
@MyCustomAnnotation
interface Product {
    fun getProducts(): Single<List<Product>>
}
```

**Generator.kt:**
This is the code used to generate the method:
```
 val name = element.simpleName.toString() // getProducts()
 val function = FunSpec.builder(name)
                    .returns(element.asType().asTypeName())
                    .addModifiers(KModifier.OVERRIDE)
                    .build()
```

When I run the app I get this error:
```
java.lang.IllegalArgumentException: Unexpected type mirror ()io.reactivex.Single<java.util.List<com.example.com.Product>>
```

Where is the error? :/
 I tried as described [here](https://github.com/square/kotlinpoet/issues/236), but it does not work.

The version is: 1.0.0-RC1

**Comment by Egorand** [comment]
I haven't worked with `javax.lang.model` framework much, but I feel like `element.asType()` isn't the right thing to do here, given that `element` represents a function. What worked for me is casting `element` to `ExecutableElement` and creating the `TypeName` for the return type via `element.returnType.asTypeName()`. Let me know if this is an appropriate solution.
