### ISSUE TITLE
How to create Nullable types as fun parameters or return types?

### ISSUE THREAD

**Issue by ka05** [square/kotlinpoet#450]
There appears to be no way to create a nullable type at all here. 

Additionally, ( this should probably be a separate issue ) there appears to be no way to setup default parameter values for a fun.

**Comment by ka05** [comment]
I apologize, I found that you need to do the following:

```
SomeClass::class.asTypeName().asNullable()
```

Heres a simple example:

```
val type = SomeClass::class.asTypeName().asNullable()

val funDeclaration = FunSpec.builder("getFullName")
            .returns(String::class)
            .addParameter("firstName", String::class)
            .addParameter("middleName", String::class.asTypeName().asNullable())
            .addParameter("lastName", String::class)
            .addStatement("return \"$firstName $middleName $lastName\"")
            .build()
```

Will close the issue, however I still would like to know how to setup default values for a parameter if possible?

**Comment by ka05** [comment]
Perhaps someone could add a nullable example to the readme? Mine may not be the most practical but your welcome to use that if you would like.

**Comment by maxpilotto** [comment]
Was this removed? I'm using KP 1.5.0 and there's no `asNullable()`. 
I resolved it by using the `copy()` method from the `TypeName` class

```
Any::class.asTypeName().copy(true)
```
