### ISSUE TITLE
Properties in constructor parameter lists can have the vararg modifier

### ISSUE THREAD

**Issue by evanchooly** [square/kotlinpoet#457]
This code:

```kotlin
val variable = TypeSpec.classBuilder("Variable")
    .primaryConstructor(FunSpec.constructorBuilder()
        .addParameter(ParameterSpec.builder("name", String::class, VARARG).build())
        .build())
    .addProperty(PropertySpec.builder("name", String::class).initializer("name").build())
    .build()
```

should produce:

```kotlin
class Variable(vararg val name: String)
```

Everything works up to the `FileSpec.Builder.build()` invocation.  `constructorProperties()` copies over the `ParameterSpec` options to `PropertySpec` instances and the `addModifier()` call rejects the `VARARG` `KModifier` on the property.

I have an incoming PR to address this and which will likely warrant a little discussion.

**Comment by Egorand** [comment]
Nice catch!
