### ISSUE TITLE
Cannot set a property initializer to a CodeBlock with a (lambda) statement

### ISSUE THREAD

**Issue by alex2069** [square/kotlinpoet#462]
Trying to generate a property with a lambda initializer:
```kotlin
val property: SomeTypeAlias = { arg ->
    println("arg=$arg")
}
```

Using:
```kotlin
val param = ParameterSpec.builder("arg", ANY).build()
val initializer = CodeBlock.builder()
    .beginControlFlow("{ %L ->", param)
    .addStatement("println(\"arg=\$%N\")", param)
    .endControlFlow()
    .build()
println("initializer=\n$initializer")

val lambdaTypeName = ClassName.bestGuess("com.example.SomeTypeAlias")
val property = PropertySpec.builder("property", lambdaTypeName)
    .initializer(initializer)
    .build()
println("property=\n$property")
```

The code block output is correct:
```kotlin
{ arg: kotlin.Any ->
    println("arg=$arg")
}
```

But when it comes time to output the property I get: `Unexpected error: java.lang.IllegalStateException: statement enter %[ followed by statement enter %[`

I can change the `addStatement` to just `add` and it works, but it results in the closing bracket being on the same line as the last line `println("arg=$arg")}`

Tried removing the lambda part with just the `println`:
```kotlin
CodeBlock.builder()
    .addStatement("println(\"hello world\")", param)
    .build()
```
Which also fails with the same error (though not sure if the above is "legal" - in fact not sure if the lambda declaration is the correct way to do it either TBH).

**Comment by Egorand** [comment]
This is a tough one. FWIW, passing that lambda to `ParameterSpec` via `defaultValue()` would yield the same result. Gonna try to figure out a fix.
