### ISSUE TITLE
Arguments types for control flow aren't imported

### ISSUE THREAD

**Issue by alex2069** [square/kotlinpoet#463]
When generating a lambda and passing in parameter specs for the arguments, the types are not imported and are instead fully qualified at use-site:
```kotlin
val lambdaTypeName = ClassName.bestGuess("com.example.hello.SomeTypeAlias")
val param = ParameterSpec.builder("arg", TypeName::class).build()
FileSpec.builder("com.example", "Test.kt").addType(
    TypeSpec.classBuilder("Hello").addProperty(
        PropertySpec.builder("property", lambdaTypeName).initializer(
            CodeBlock.builder()
                .beginControlFlow("{ %L ->", param)
                .endControlFlow()
                .build()
        ).build()
    ).build()
).build()
```

Generates:
```kotlin
package com.example

import com.example.hello.SomeTypeAlias

class Hello {
    val property: SomeTypeAlias = { arg: com.squareup.kotlinpoet.TypeName ->
    }

}
```

**Comment by JakeWharton** [comment]
`%T` is for a type. `%L` is for a literal which will always emit the FQCN.

**Comment by alex2069** [comment]
Ah, I thought it would know it was a parameter and treat it like as a function parameter. So it should be done as this?
```.beginControlFlow("{ %N: %T ->", param, param.type)```

**Comment by Egorand** [comment]
Yes, that's the correct way to generate a **lambda expression**. `LambdaTypeName` is for creating **lambda types**.
