### ISSUE TITLE
Configurable line feed character?

### ISSUE THREAD

**Issue by Fleshgrinder** [square/kotlinpoet#464]
Generating files on Windows leads to `\r\n` and on Linux to `\n`. Having the ability to control this behavior for generated files would be much appreciated. 😊

**Comment by swankjesse** [comment]
Any practical consequence of this? It's my understanding that Windows will take `\n` pretty much everywhere now.
https://www.theregister.co.uk/2018/05/08/windows_notepad_unix_linux_macos/

**Comment by Egorand** [comment]
Unclear if we need this or not, closing.

**Comment by swankjesse** [comment]
Practical consequences of this? Like, which Windows apps are upset about UNIX linefeeds?

**Comment by Fleshgrinder** [comment]
This has nothing to do with an application not being able to cope with the line feeds. This is about the code you check in. Teams often have developers with different operating systems and all of them might generate and check-in code. This leads to the situation where they have to keep an eye out for line feeds. Sure, they can use git or dos2unix but it would be favorable if one could simply configure `\n` and be done with it. Nobody needs to even think about it, as it should be with generated code.
