### ISSUE TITLE
How to generate closure type as function argument?

### ISSUE THREAD

**Issue by ka05** [square/kotlinpoet#466]
```kotlin
override fun makeAsyncCall(callback: ((Any?) -> Any?)?) {

}
```

**Comment by JakeWharton** [comment]
See `LambdaTypeName`.

Example: https://github.com/square/kotlinpoet/blob/38adcb449df75bc2b766ff14a3d0915c7ab7dc18/src/test/java/com/squareup/kotlinpoet/LambdaTypeNameTest.kt#L32-L38

**Comment by Egorand** [comment]
Please avoid using Issues for usage questions (we've got a [Stackoverflow](https://stackoverflow.com/questions/tagged/kotlinpoet) tag for that), these are for bug reports and feature requests.

**Comment by JakeWharton** [comment]
What's most frustrating is we lack the time to provide sufficient documentation since it's almost entirely volunteer time working on this. Also GitHub could do far better here by separating out discussion from issues.

**Comment by Egorand** [comment]
Also, you're almost certain to find examples for any use case in the unit tests, we've got a lot of them.

**Comment by ka05** [comment]
Thanks @Egorand, I will focus my attention toward the unit tests moving forward. My only complaint is that without knowing the library some of the examples 

@JakeWharton, that is a great idea! You are totally right, GitHub should have a discussion section for each repo. They could create something that resembles a forum tied into each repo ( like the issues and wiki sections ). Im sure there would have to be some restrictions, but it would certainly help the efficiency of those filtering through issues, and allow for other outlets of ideas and communication. 
( Probably not the best place to discuss this, though I guess that kind of re-enforces the point )

Then for creating issues, they could add categories to select from, sort of like creating tickets in JIRA. 
I know there are "Labels", but they don't necessarily work the same way.
Some examples could be: 

- Bug / Issue
- New Feature / Enhancement
- Documentation Request
- Question / Answers

( You guys would know better which types would be effective as you deal with this much more than I do but here are just some I can think of. )

It would be awesome if someone would refine and pursue this! I would but I have no idea where to start.
