### ISSUE TITLE
Escape parameter name in PropertySpec which is also a Kotlin keyword

### ISSUE THREAD

**Issue by emrul** [square/kotlinpoet#476]
If I have a piece of code like this:
```
PropertySpec.builder("object", ...)
```
I get a "not a valid name: object" error.

This is similar to #263 #293 - could we have KotlinPoet automatically escape these so the name of the generated property becomes, for example \`object\`?

**Comment by Egorand** [comment]
Sure! Wanna submit a PR?

**Comment by emrul** [comment]
Of course, was quite simple since the escaping was already being done in code emitter so just removed the checks and added a couple of tests to verify.
