### ISSUE TITLE
Allow imports of default-package top-level members.

### ISSUE THREAD

**Issue by kenzierocks** [square/kotlinpoet#480]
I'm using KotlinPoet in my tests of [`ts2kt`](https://github.com/Kotlin/ts2kt)'s output. One of the problems I have is that it often generates a file with this contents:
```
external var bigInt: bigInt.BigIntegerStatic = definedExternally
```
Note the lack of `package` declaration. This can be used in Kotlin by importing it with `import bigInt`, but there's no API to do this in KotlinPoet, as the current APIs all require some sort of package context, which doesn't exist here.

I'm currently hacking around it by emitting to a `StringBuilder` then injecting my imports, but I think allowing this (possibly by adding #433's `FullyQualifiedName`?) would be helpful for writing Kotlin that works with JS libraries.

**Comment by JakeWharton** [comment]
You haven't shown how you are generating the code. Perhaps a failing test
case?

**Comment by kenzierocks** [comment]
https://gist.github.com/kenzierocks/a970e4e4c9603032247839ac8c2d3640

Problem is with `bigInt(input)`. I've tried using a `ClassName`, but that either emits nothing (if I do `ClassName(packageName = "", simpleName = "bigInt")` or invalid code `import bigInt.` (if I do `ClassName(packageName = "bigInt", simpleName = "")`). I've also tried adding the import using `FileSpec#addImport`, but those also require package context.

Note that I'm not actually adding tests to `ts2kt`, I'm just testing some of the output as part of another project. I don't really have control over how the original files are generated, I'm just using them.

**Comment by Egorand** [comment]
If I get your problem right, you want no `package` declaration and correct `import` declarations. Here's what works for me:

```kotlin
@Test fun test() {
  val BigInteger = ClassName.bestGuess("bigInt.BigInteger")
  val spec = FileSpec.builder("", "Test.kt")
      .addFunction(FunSpec.builder("add5ToInput").apply {
        addParameter("input", Int::class)
        returns(BigInteger)
        addStatement("val inputBigInt = bigInt(input)")
        addStatement("return inputBigInt.add(5)")
      }.build())
      .build()
  assertThat(spec.toString()).isEqualTo("""
    |import bigInt.BigInteger
    |import kotlin.Int
    |
    |fun add5ToInput(input: Int): BigInteger {
    |    val inputBigInt = bigInt(input)
    |    return inputBigInt.add(5)
    |}
    |""".trimMargin())
}
```

If this is not what you're looking for, please share the code that you're running, the output that you get and the output that you expect.

**Comment by Egorand** [comment]
Okay, gotcha. I tried `addImport(packageName = "", names = "bigInt")` and it generates `import .bigInt`, which is incorrect. As you mentioned, #433 should make the experience better, but for now I can supply a small patch to make the code above work.

**Comment by Egorand** [comment]
Taking another look at it: you don't actually need to import `bigInt`, as it's in the same package, why do you want this?

**Comment by kenzierocks** [comment]
It's not in the same package. It's in the default package, my code is in the `testsrc` package.

**Comment by Egorand** [comment]
Fair, indeed you can import top-level vals/funs declared in the default package - wasn't sure it's possible. I'll try to get a PR up soon-ish, however - contributions are always welcome, so feel free to submit a fix if you like!
