### ISSUE TITLE
Always wrap spaces

### ISSUE THREAD

**Issue by swankjesse** [square/kotlinpoet#485]
We should always wrap spaces. Whitespace is almost always insignificant.

In the rare cases where it is (such as when a string literal is hardcoded in a KotlinPoet string), we should permit a Unicode character like `·` to designate. In this example the space after `return` wraps, and the · is rendered with a space.

```
    val taco = TypeSpec.classBuilder("Taco")
        .addFunction(FunSpec.builder("toString")
            .addModifiers(KModifier.PUBLIC, KModifier.FINAL, KModifier.OVERRIDE)
            .returns(String::class)
            .addStatement("return \"yummy·taco\"")
            .build())
        .build()
```

**Comment by JakeWharton** [comment]
> Whitespace is almost always insignificant

This is not true for binary operators whose symbols are reused for unary operators. Most notable is plus and minus.

If you wrap `val foo = 4 + 3` at 12 columns you get a broken program.

**Comment by swankjesse** [comment]
Good catch. We'll need to never break after a unary operator.

**Comment by Egorand** [comment]
@JakeWharton Still, I guess most spaces are safe to wrap. So we're switching from having to put `%W` everywhere to having to put `·` in very specific cases.

**Comment by JakeWharton** [comment]
Maybe. You'll have to write quite the parser to solve cases like `"""a string with ${anExpression(with, spaces, "and a nested string")}"""`.

I think I'd rather build an AST-like CodeBlock tree so that unwrappable expressions became opaque to the code generator.
