### ISSUE TITLE
Replace ASCII escapes with fancy Unicode symbols

### ISSUE THREAD

**Issue by swankjesse** [square/kotlinpoet#486]
I find the `%[` things hard to read in source code. Using Unicode characters instead might be more readable. That would bring us here:

 * `⇥` increases the indentation level.
 * `⇤` decreases the indentation level.
 * `«` begins a statement. For multiline statements, every line after the first line is double-indented.
 * `»` ends a statement.

**Comment by Egorand** [comment]
Since this is a breaking change, we should consider adding it in prior to 1.0.

**Comment by cwwwu** [comment]
I can work on making the changes for this
