### ISSUE TITLE
lateinit var with private setter doesnt work

### ISSUE THREAD

**Issue by friedrich-goetze** [square/kotlinpoet#494]
Here's my approach:
```kotlin
PropertySpec.varBuilder("foo", String::class, LATEINIT)
    .setter(FunSpec.setterBuilder()
        .addModifiers(PRIVATE)
        .build()
    ).build()
```
I would expect the following kotlin code to be generated:

```kotlin
lateinit var foo: String
    private set
```
But I get:
```java
java.lang.IllegalStateException: set() can have only one parameter
        at com.squareup.kotlinpoet.FunSpec$Builder.build(FunSpec.kt:339)
        ...
```

**Comment by friedrich-goetze** [comment]
Adding the parameter without any code also doesn't work. It would generate this code:
```kotlin
lateinit var foo: String
    private set(value) { }
```
But then the kotlin compiler complains:
```
'lateinit' modifier is not allowed on properties with a custom getter or setter
```

**Comment by Egorand** [comment]
This is interesting, didn't know that was valid syntax. @cwwwu wanna take a look?

**Comment by cwwwu** [comment]
Will take a look at this, @Egorand

**Comment by shaishavgandhi05** [comment]
If @cwwwu is swamped, I can take a look at it.

**Comment by cwwwu** [comment]
I've finally had some time this week to look at this and should have a pull request out for addressing this in the next day or two 😄
