### ISSUE TITLE
Add support for inline classes

### ISSUE THREAD

**Issue by Egorand** [square/kotlinpoet#504]
https://kotlinlang.org/docs/reference/inline-classes.html

**Comment by shaishavgandhi05** [comment]
This is already kinda possible with something like:
```kotlin
@Test fun inlineClass() {
    val guacamole = TypeSpec.classBuilder("Guacamole")
        .addModifiers(INLINE)
        .primaryConstructor(FunSpec.constructorBuilder()
            .addParameter("avacado", String::class)
            .build())
        .build()

    assertThat(guacamole.toString()).isEqualTo("""
      |inline class Guacamole(avacado: kotlin.String)
      |""".trimMargin())
  }
```

This obviously doesn't account for all the different rules with inline classes like single parameter constructors, no secondary constructors, no `init` blocks etc.

**Comment by Egorand** [comment]
True, we don't disallow `inline` on types. Would be great though if we did the validation too.

**Comment by shaishavgandhi05** [comment]
https://github.com/Kotlin/KEEP/blob/master/proposals/inline-classes.md

This is also a good design doc for inline classes.
