### ISSUE TITLE
Prevent imports of "kotlin.jvm.functions.FunctionX"

### ISSUE THREAD

**Issue by TAGC** [square/kotlinpoet#508]
I'm trying to use KotlinPoet to transform functions into "nodes" via annotation processing. For example, this function:

```kotlin
@ElementaryNode
fun <T> tee(input: T, action: T.() -> Unit): T {
    input.action()
    return input
}
```

Is transformed into the following node:

```kotlin
package com.mycompany.testmaster

import com.mycompany.testmaster.model.InputPort
import com.mycompany.testmaster.model.Node
import com.mycompany.testmaster.model.OutputPort
import kotlin.Unit
import kotlin.jvm.functions.Function1

class Tee<T> : Node {
    val input: InputPort<T> = TODO("implement input port property")

    val action: InputPort<Function1<in T, Unit>> = TODO("implement input port property")

    val output: OutputPort<T> = TODO("implement output port property")
}
```

However, I get a warning that I should be using `kotlin1.Function` instead of `kotlin.jvm.functions.Function`. 

This is the code I use to build the `InputPort` properties:

```kotlin
val inputPorts = definition.inputPorts.map {
    val portDataType = it.type.asTypeName()
    val portType = InputPort::class.asTypeName().parameterizedBy(portDataType)

    PropertySpec.builder(it.name, portType)
            .initializer("TODO(\"implement input port property\")")
            .build()
}
```

In the case of the function being passed as a parameter to `tee`, `it.type.asTypeName` is `kotlin.jvm.functions.Function1<in T, kotlin.Unit>`.

Can KotlinPoet be configured somehow to output the correct Function types, or will I need to add in code to edit the file after it's generated and manually remove the import statement?

**Comment by Egorand** [comment]
Looks like Kotlin compiler replaces occurrences of `kotlin.Function1` with `kotlin.jvm.functions.Function1`, hence this is what your annotation processor sees. This issue is similar to #86 and #236. For now we don't have a solution for replacing types, so I guess for now your best bet is to post-process the output, replacing `kotlin.jvm.functions.Function1` imports with `kotlin.Function1`.

**Comment by TAGC** [comment]
Ah okay, thanks. I wrote some ugly regex replacement hacks and I'll stick with that for now.
