### ISSUE TITLE
@receiver Kdoc overloads

### ISSUE THREAD

**Issue by shaishavgandhi05** [square/kotlinpoet#509]
In the spirit of covering the major [tags](https://kotlinlang.org/docs/reference/kotlin-doc.html#block-tags) in KDoc, this would be a good addition. Extension functions are pretty widely used and we should provide overloads similar to `returns` that adds documentation to it. 

Additionally, if I understand correctly, the project aims to emulate the Android Kotlin style guide. That guide mentions the following
```
Block tags
Any of the standard “block tags” that are used appear in the order @constructor, @receiver, 
@param, @property, @return, @throws, @see, and these never appear with an empty description. 
When a block tag doesn’t fit on a single line, continuation lines are indented 8 spaces from 
the position of the @.
```

In that spirit, we should add the `@receiver` tag before `@param` or `@return`. 

Happy to send a PR if this is something that you think is a good addition to KotlinPoet.

**Comment by Egorand** [comment]
Yep, see no reason not to add it!
