### ISSUE TITLE
Better API for creating primary constructor properties

### ISSUE THREAD

**Issue by Egorand** [square/kotlinpoet#515]
This is what we do right now:
```kotlin
val flux = FunSpec.constructorBuilder()
    .addParameter("greeting", String::class)
    .build()

val helloWorld = TypeSpec.classBuilder("HelloWorld")
    .primaryConstructor(flux)
    .addProperty(PropertySpec.builder("greeting", String::class)
        .initializer("greeting")
        .addModifiers(KModifier.PRIVATE)
        .build())
    .build()
```
emitting:
```kotlin
class HelloWorld(private val greeting: String)
```

This is overly verbose for a frequently used feature (data and inline classes require this kind of properties). Discoverability of this feature is also not great, it's documented in README, but it's not easy to find by poking through the code. We should come up with API that will make it easier to declare such properties, potentially generating primary constructor, parameter and property via a single call.

**Comment by Egorand** [comment]
I've been writing a bunch of those lately, and it feels really cumbersome for such a ubiquitous feature - and inline classes add to the mix. I think we might provide more intuitive APIs for certain language features if they simplify working with the library (like we did for JVM-specific annotations).

**Comment by jpink** [comment]
You can create you own extension method or helper class which does the trick.

**Comment by dimsuz** [comment]
As per @jpink's suggestion built this simple extension, it works nicely for me:

```kotlin
internal fun TypeSpec.Builder.primaryConstructor(vararg properties: PropertySpec): TypeSpec.Builder {
  val propertySpecs = properties.map { p -> p.toBuilder().initializer(p.name).build() }
  val parameters = propertySpecs.map { ParameterSpec.builder(it.name, it.type).build() }
  val constructor = FunSpec.constructorBuilder()
    .addParameters(parameters)
    .build()

  return this
    .primaryConstructor(constructor)
    .addProperties(propertySpecs)
}
```
Usage:
```kotlin
TypeSpec.classBuilder("MyClass")
  .primaryConstructor(PropertySpec.builder("operations", operationsType)
    .addModifiers(KModifier.PRIVATE)
    .build()
  )
```

**Comment by andromedcodes** [comment]
> As per @jpink's suggestion built this simple extension, it works nicely for me:
> 
> ```kotlin
> fun TypeSpec.Builder.primaryConstructor(vararg properties: PropertySpec): TypeSpec.Builder {
>   val propertySpecs = properties.map { p -> p.toBuilder().initializer(p.name).build() }
>   val parameters = propertySpecs.map { ParameterSpec.builder(it.name, it.type).build() }
>   val constructor = FunSpec.constructorBuilder()
>     .addParameters(parameters)
>     .build()
> 
>   return this
>     .primaryConstructor(constructor)
>     .addProperties(propertySpecs)
> }
> ```
> 
> Usage:
> 
> ```kotlin
> TypeSpec.classBuilder("MyClass")
>   .primaryConstructor(PropertySpec.builder("operations", operationsType)
>     .addModifiers(KModifier.PRIVATE)
>     .build()
>   )
> ```

You can't set initializer on a property any more.
