### ISSUE TITLE
Javadoc artifact is empty in 1.0.0-RC3

### ISSUE THREAD

**Issue by swankjesse** [square/kotlinpoet#552]
With the switch to Gradle we lost docs in our Maven Central artifacts.

**Comment by hzsweers** [comment]
I could bring in the modified `gradle-mvn-push.gradle` that we use in AutoDispose if you want? @charlesdurham made a nice PR that makes it support dokka really well

**Comment by hzsweers** [comment]
Oh I just realized this is using the releasing plugin, which is still missing dokka support

**Comment by Egorand** [comment]
We need that PR in the plugin! I'll ping the maintainers to see if Dokka support is coming soon.

**Comment by hzsweers** [comment]
there's an open issue for it iirc (AFK)

**Comment by Egorand** [comment]
https://github.com/vanniktech/gradle-maven-publish-plugin/issues/21
Not a release blocker, we can use `gradle-mvn-push.gradle` for publishing artifacts until that issue is resolved.

**Comment by Egorand** [comment]
Fixed by #604
