### ISSUE TITLE
FileSpec addImport(className: ClassName, vararg names: String) crashes when no names are provided

### ISSUE THREAD

**Issue by gilgoldzweig** [square/kotlinpoet#555]
If I try to add an import to FileSpec with only the className it will throw an exception

for example: 
`fileBuilder.addImport(ClassName(myPackageName, mySimpleName))`  It will throw `java.lang.IllegalArgumentException: names array is empty`  

but if I'll do this 
`fileBuilder.addImport(myPackageName, mySimpleName)`  everything is fine

I looked at the code and you have two requirements 

```
require(names.isNotEmpty()) { "names array is empty" } //This one causes the issue
require("*" !in names) { "Wildcard imports are not allowed" }
```

I'm using version 1.0.0-RC3

**Comment by Egorand** [comment]
What's your use case? There's no good reason for importing plain `ClassName`s manually, provided you're using `%T`. Use `addImport()` if you want to import static/top-level functions or properties.

**Comment by gilgoldzweig** [comment]
I'm a creation a file filled with small class that contains pretty much the same info 
And they all use a specific class and I need to import it, now I don't want to import it for every class I want to import it once in the file

**Comment by Egorand** [comment]
Can you share the code? Most cases don't require you to import types manually.

**Comment by gilgoldzweig** [comment]
This is the classs I'm generating
```
import android.view.View
import android.widget.LinearLayout
import android.widget.TextView
import goldzweigapps.com.gencycler.GencyclerHolder
import goldzweigapps.com.gencycler.R
import java.lang.IllegalArgumentException
import kotlin.Int

/**
 * Generated ViewHolder created based on [R.layout.java_profile_type]
 */
class JavaProfileContainerViewHolder(view: View) : GencyclerHolder(view) {
    val root: LinearLayout = findView(R.id.root)

    val typeOneOneText: TextView = findView(R.id.type_one_one_text)

    val subroot: LinearLayout = findView(R.id.subroot)

    val typeSubOneTwoText: TextView = findView(R.id.type_sub_one_two_text)

    val typeSubOneThreeText: TextView = findView(R.id.type_sub_one_three_text)

    val typeOneTwoText: TextView = findView(R.id.type_one_two_text)

    val typeOneThreeText: TextView = findView(R.id.type_one_three_text)

    val typeOneFourText: TextView = findView(R.id.type_one_four_text)
}

/**
 * Generated ViewHolder created based on [R.layout.item_empty]
 */
class Profile2ContainerViewHolder(view: View) : GencyclerHolder(view)

/**
 * Generated ViewHolder created based on [R.layout.kotlin_profile_type]
 */
class ProfileContainerViewHolder(view: View) : GencyclerHolder(view) {
    val root: LinearLayout = findView(R.id.root)

    val typeThreeOneText: TextView = findView(R.id.type_three_one_text)

    val typeThreeTwoText: TextView = findView(R.id.type_three_two_text)

    val typeThreeThreeText: TextView = findView(R.id.type_three_three_text)

    val includedJavaProfile: View = findView(R.id.included_java_profile)
}

/**
 * Generated ViewHolder created based on [R.layout.kotlin_profile_type]
 */
class Profile3ContainerViewHolder(view: View) : GencyclerHolder(view) {
    val root: LinearLayout = findView(R.id.root)

    val typeThreeOneText: TextView = findView(R.id.type_three_one_text)

    val typeThreeTwoText: TextView = findView(R.id.type_three_two_text)

    val typeThreeThreeText: TextView = findView(R.id.type_three_three_text)

    val includedJavaProfile: View = findView(R.id.included_java_profile)
}
```

**Comment by Egorand** [comment]
I meant I wanted to see your KotlinPoet code, could you please share that as well?

**Comment by gilgoldzweig** [comment]
Yeah sure, here is the link for the specific file, it's not completely ready yet but it's getting there
https://github.com/gilgoldzweig/Gencycler/blob/dev/compiler/src/main/java/goldzweigapps/com/compiler/generators/ViewHolderGenerator.kt

**Comment by Egorand** [comment]
Thank you, I'll take a look!

**Comment by Egorand** [comment]
Yeah, I see the point, however, we don't support importing types manually, so you should go with the `%T` notation whenever you're relying on the importing mechanism. I guess the API of `addImport()` could be more restrictive to better communicate that it expects a member name along with the `ClassName`.
