### ISSUE TITLE
RC3: Function calls with a lambda parameter can produce incorrect code due to wrong line wrapping

### ISSUE THREAD

**Issue by frko** [square/kotlinpoet#557]
The following usage of lambda's will generate non compiling kotlin code.

The line-wrapping is wrongfully applied between the invoked method name and the brace that's starts the lambda parameter notation. 

```
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.TypeSpec.Companion.classBuilder
import com.squareup.kotlinpoet.asTypeName

println(
    FileSpec.builder("A", "B")
        .addFunction(
            FunSpec.builder("CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC")
                .beginControlFlow("""return "".apply {""")
                .addStatement("""println("D")""")
                .endControlFlow()
                .build()
        )
        .build()
)
```

generates

```
fun CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC() = "".apply
        {
    println("D")
}
```

**Comment by Egorand** [comment]
Spaces can now wrap by default, use the non-wrapping space character - `·` - to avoid this:
```kotlin
.beginControlFlow("""return "".apply·{""")
```

**Comment by frko** [comment]
@Egorand Thank you for your swift reply.

**Comment by frko** [comment]
I also notice line wrap will occur between a constructor parameter name and it's type definition. Is this intentional? Preferable the whole parameter definition ( or all of them ) would wrap to new lines.

**Comment by Egorand** [comment]
Yeah, auto-wrapping spaces is a new feature, and we have to take a pass and add non-wrapping spaces in places that shouldn't wrap - thanks for identifying those! Please feel free to file issues for wrapping inconsistencies.

**Comment by frko** [comment]
@Egorand would you prefer a ticket per occurrence or rather some sort of container ticket?

**Comment by Egorand** [comment]
I'd prefer an issue per occurrence
