### ISSUE TITLE
val property = "something" // followed by a line comment

### ISSUE THREAD

**Issue by jmfayard** [square/kotlinpoet#561]
Hello! 

In my Gradle plugin `buildsSrcVersions`,  I need to generate  [code like this](https://github.com/jmfayard/buildSrcVersions/blob/55b3f0b5f8dd3f6d9136cd97ee209ed2d75c4518/doc/Versions.kt)

```
objet Versions {
    val okio = "2.0.0" // available: "2.1.0"
}
```

I didn't find an API to add a line comment so I abused the initialized block to do this.  Something like this:

```kt
fun generateProperty(name: String, currentVersion: Int, available: Int) =
    PropertySpec.builder(name, String::class)
        .initializer(CodeBlock.of("%S %L", currentVersion, " // available: \"$available\""))
        .build()
```

It usually works but breaks done when the name is long

```
objet Versions {
    val with_a_very_long_name_I_get_a_line_break = "2.0.0" // available: 
              "2.1.0"
}
```
Compile-error because the line-comment was broken in two parts. 

What is a better way to do that?

**Comment by swankjesse** [comment]
Use `·` instead of space to prevent line wrapping.

We aren't going to add APIs for precise positioning of comments, but your approach is fine.

**Comment by jmfayard** [comment]
That solves my problem, thanks @swankjesse !

**Comment by kezhenxu94** [comment]
> We aren't going to add APIs for precise positioning of comments, but your approach is fine.

@swankjesse any status? :)

**Comment by Egorand** [comment]
@kezhenxu94 status of what?

**Comment by kezhenxu94** [comment]
> @kezhenxu94 status of what?

"add APIs for precise positioning of comments", do we have this API now?

**Comment by Egorand** [comment]
> We aren't going to add APIs for precise positioning of comments

**Comment by kezhenxu94** [comment]
> > We aren't going to add APIs for precise positioning of comments

Oh I'm sorry, forgive me
