### ISSUE TITLE
Generate function with access to private fields of existing class

### ISSUE THREAD

**Issue by manuelhuber** [square/kotlinpoet#562]
Hello,

I want to build an annotation processor that generates a public "non-mutable class" getter function of a private "mutable class" field (e.g. returning a `LiveData<T>` version of a `MutableLiveData<T>` field). So in the function I need access to the private field which I can't do via Class extensions.

What I want to write:
```
class MyClass {
  @WithGetNonMutable
  private val popup: MutableLiveData<PopupTO?> = MutableLiveData()
}
```
What I want to generate

```
class MyClass {
  private val popup: MutableLiveData<PopupTO?> = MutableLiveData()

  fun getPopup(): LiveData<PopupTO?> = popup
}
```
Generating the function with the correct return type is no problem - but I don't know how to return the private variable `popup`. What's the easiest way to add a function to class like this?

**Comment by Egorand** [comment]
Looks like `addStatement("return popup")` is all you need. Also, please use StackOverflow for usage questions.
