### ISSUE TITLE
How to generate code when I am building my application?

### ISSUE THREAD

**Issue by TioCoding** [square/kotlinpoet#564]
Hello, I'm new using kotlinpoet and I've been reading the documentation and it seems like a great library, but I could not find an example to solve my problem.

I have a dependency `lib-domain-0.1.jar` in which I have business objects for example:

```Kotlin

package pe.com.business.domain

data class Person(val id: Int? = null, val name: String? = null)
...
..
package pe.com.business.domain

data class Departament(val id: Int? = null, val direction: String? = null)
...
..
.
```

And I want to build a new dependency called `lib-domain-fx-0-1.jar` where it has the same domains but with JavaFx properties (With tornadofx) for example:

```Kotlin
package pe.com.business.domainfx
import tornadofx.*

class Person {
  val idProperty = SimpleIntegerProperty()
  var id by idProperty
  
  val nameProperty = SimpleStringProperty()
  var name by nameProperty
}
...
..
package pe.com.business.domainfx
import tornadofx.*

class Departament {
  val idProperty = SimpleIntegerProperty()
  var id by idProperty
  
  val directionProperty = SimpleStringProperty()
  var direction by directionProperty
}
...
..
.
```

My question is, how can I generate these files in `lib-domain-fx-0-1.jar` by simply compiling my application with a `gradle build`? I have seen several examples in which they use @Annotations and two different modules in the same project, but that is not what I need :(. I need to convert all classes of `lib-domain-0.1.jar` to the JavaFx version with TornadoFX in another project (`lib-domain-fx-0.1.jar`)

Thanks and regards.

**Comment by Egorand** [comment]
Thanks for your question! Please use StackOverflow for usage questions, this issue tracker is mainly for bug reports and feature requests.

**Comment by TioCoding** [comment]
Sorry for the open issue, I just did not want my question to be ignored in StackOverflow :disappointed: , and to have a faster response and even more from those working with Kotlinpoet. I created the question in StackOverflow:

https://stackoverflow.com/questions/53856476/how-to-generate-code-with-kotlinpoet-when-i-am-building-my-application-gradle

I hope you can help me thanks.

Regards.

**Comment by Egorand** [comment]
Thank you! As I mentioned, usage questions don't belong on issue tracker. We're monitoring the "kotlinpoet" tag on StackOverflow and trying to answer every question, along with people who use KotlinPoet and are active on StackOverflow.
