### ISSUE TITLE
Add WildcardTypeName example

### ISSUE THREAD

**Issue by LouizFC** [square/kotlinpoet#574]
As obvious as WildcardTypeName class usage is, I wasted a good portion of time trying to find it.

I think the name itself is not intuitive. I am familiarized with Java, but when in Kotlin the first thing that comes to my mind when using "in and out" is "variance" not "wildcard". 

I think it would be good to add some example using WildcardTypeName just so people can find this class more easely

**Comment by Egorand** [comment]
Thanks for the feedback, an extra piece of documentation is definitely helpful. Good point on the type name, indeed it goes back to JavaPoet's `WildcardTypeName` which is used to generate stuff like `? extends Number`. We should look for a better name.

**Comment by Egorand** [comment]
Closed with #575
