### ISSUE TITLE
Add VariableSpec

### ISSUE THREAD

**Issue by ansman** [square/kotlinpoet#593]
It would be great if there was a way to add local variables, similar to `PropertySpec`.

**Comment by Egorand** [comment]
You can use `PropertySpec` to declare local variables: https://github.com/square/kotlinpoet/pull/317/files

**Comment by ansman** [comment]
Nice, perhaps this should have a dedicated API in `FunSpec.Builder` (`addLocalVariable(propertySpec: PropertySpec): Builder`)?
