### ISSUE TITLE
Long comments inside FunSpec are wrapped and left uncommented on the second line

### ISSUE THREAD

**Issue by bishopmatthew** [square/kotlinpoet#594]
Long comments added to a FunSpec.builder with addComment get wrapped, but they don't carry the comment prefix over to the second line. Here's a quick failing test case showing the problem:

```kotlin
  @Test fun longComment() {
    val taco = TypeSpec.classBuilder("Taco")
        .addFunctions(Arrays.asList(
            FunSpec.builder("getAnswer")
                .addModifiers(KModifier.PUBLIC)
                .returns(Int::class)
                .addComment("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.")
                .addStatement("return %L", 42)
                .build()))
        .build()
    assertThat(toString(taco)).isEqualTo("""
        |package com.squareup.tacos
        |
        |import kotlin.Int
        |
        |class Taco {
        |    fun getAnswer(): Int {
        |        // Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
        |        // ut labore et dolore magna aliqua.
        |        return 42
        |    }
        |}
        |""".trimMargin())
  }
```

I looked for a second to see if I could figure out what's doing the wrapping (or if there was an easy way to turn it off or get to continue the comment?) but didn't see anything. If anyone could point me in the right direction I could try to fix it.

**Comment by Egorand** [comment]
Whoops! Check out #584 which solves a similar issue

**Comment by Egorand** [comment]
Ah, I think it might be a trickier in this case.. I'll take a closer look today

**Comment by bishopmatthew** [comment]
Thanks! Yeah I don't think I would have figured out the way you did that.

**Comment by Egorand** [comment]
For now it'll at least make sure generated code is correct, but won't auto-wrap long comments. That's tricky to get right, but not impossible - feel free to take a stab at it if you feel like it!
