### ISSUE TITLE
Line breaking can produce invalid code

### ISSUE THREAD

**Issue by hzsweers** [square/kotlinpoet#598]
Ran into this while trying to update a project here: https://github.com/hzsweers/copydynamic/pull/10

Code where this emits from: https://github.com/hzsweers/copydynamic/blob/b7ac90b06b78cebb0a22b6787b685eef93e512da/copydynamic/src/main/kotlin/io/sweers/copydynamic/CopyDynamicProcessor.kt#L251

```kotlin
@Generated(
    value = ["io.sweers.copydynamic.CopyDynamicProcessor"],
    comments = "https://github.com/hzsweers/copydynamic"
)
internal fun CopyDynamicTest.InternalFoo.copyDynamic(copyBlock: InternalFooDynamicBuilder.() ->
    Unit): CopyDynamicTest.InternalFoo = InternalFooDynamicBuilder(this).also { copyBlock(it) }.run
    { copy(bar = bar) }
```

That fails to compile because it doesn’t associate ` { copy(bar = bar) }` with the `.run` at the end of the prev line

**Comment by Egorand** [comment]
Yep, spaces are now wrapping by default, use `·` instead to add a non-wrapping space, e.g. `.also·{ copyBlock(it) }.run·{ copy(bar = bar) }`.

**Comment by fmrsabino** [comment]
One more scenario where this can happen (breaking strings):

```kotlin
codeBlock.addStatement(
    "if ($TOPIC_ARG_NAME.first() != $EVENT_ID_PROPERTY_NAME) throw %1T(\"topics[0] does not match event id\")",
    IllegalArgumentException::class
)
```

Produces the following invalid code because of the line break:

```
if (topics.first() != EVENT_ID) throw IllegalArgumentException("topics[0] does not
                        match event id")
```

Using `·` solves the problem.

**Comment by Egorand** [comment]
@fmrsabino In this case I'd suggest using `%S` for the string argument, this will prevent the string from being wrapped.
