### ISSUE TITLE
Provide better support for generating Kotlin scripts

### ISSUE THREAD

**Issue by Egorand** [square/kotlinpoet#608]
Kotlin scripts can include code that's not enclosed into types/functions/property initializers, which `FileSpec.Builder` doesn't support at the moment.

**Comment by NikkyAI** [comment]
also kotlin script definitions can include default imports that do not need to be specified i nthe script anymore, might be harder to support though
maybe as by passing imports to be ignored to the builder..

their file extension is usually *.something.kts but can be anything

**Comment by JakeWharton** [comment]
ScriptSpec?

**Comment by NikkyAI** [comment]
adding a `ScriptSpec` and `ScriptSpec.Builder` would make sure that this does not break the existing .kt file generator at least

**Comment by Egorand** [comment]
I feel like `FileSpec` and `ScriptSpec` would share a lot of code, and depending on how much exactly it might just make sense to add functionality to `FileSpec`. I must admit though that I have zero experience with Kotlin scripts, but I'll check it out.

**Comment by swankjesse** [comment]
I'd like to get FileSpec to handle this.

**Comment by NikkyAI** [comment]
that would make it possible for `FileSpec` to have top level statements which as invalid in normal .kt files

and it would require being able to customize the file extension when writing to file

**Comment by Egorand** [comment]
I think this is fine. We already use `FunSpec` for constructors, and certain builder methods don't make sense for constructors, but it helps avoid duplicating all the other functionality that's shared between constructors and functions.

**Comment by NikkyAI** [comment]
about more detail on kotlin scripting: its all in this KEEP: https://github.com/Kotlin/KEEP/blob/scripting/proposals/scripting-support.md
