### ISSUE TITLE
Interface delegation doesn't work for objects

### ISSUE THREAD

**Issue by fluidsonic** [square/kotlinpoet#610]
This code checks for `isSimpleClass` which doesn't cover `object`s.
Interface delegation does work fine with `object`s in Kotlin though.

https://github.com/square/kotlinpoet/blob/d5877b03e15983e5ea48f8446728d9ce98c215f3/src/main/java/com/squareup/kotlinpoet/TypeSpec.kt#L506-L512

**Comment by Egorand** [comment]
@fluidsonic would you be interested in submitting a fix for this?

**Comment by fluidsonic** [comment]
@Egorand done
