### ISSUE TITLE
ParameterizedTypeName.get loses nullability information

### ISSUE THREAD

**Issue by jGleitz** [square/kotlinpoet#613]
```kotlin
ParameterizedTypeName.get(Any::class, true, emptyList())
```
 will return the `TypeName` for `Any`, not for `Any?`.

This is because the `nullable` parameter will be discarded if the `typeArguments` are empty in https://github.com/square/kotlinpoet/blob/master/src/main/java/com/squareup/kotlinpoet/TypeName.kt#L583 : 

```kotlin
  /** Returns a type name equivalent to type with given list of type arguments.  */
    internal fun get(
      type: KClass<*>,
      nullable: Boolean,
      typeArguments: List<KTypeProjection>
    ): TypeName {
      if (typeArguments.isEmpty()) {
        return type.asTypeName()
      }

     […]
```

**Comment by Egorand** [comment]
Can you please provide a failing test case? This is an `internal` method so I'd like to know how to trigger the issue through public API.

**Comment by jGleitz** [comment]
I’m triggering this through `KType.asTypeName()`, see #614
