### ISSUE TITLE
Compile-time constant strings incorrectly generated with trimMargin() helper

### ISSUE THREAD

**Issue by ZacSweers** [square/kotlinpoet#629]
Some places require that `%S` strings be compile-time constants, such as annotations or `const` properties. Right now, if a string has a newline char in it, kotlinpoet will convert it to a raw string template with `.trimMargin()` on the end, which will fail to compile since it's not a compile-time constant

**Comment by ZacSweers** [comment]
I've put up two proposal PRs:

Use a `%C` placeholder: https://github.com/square/kotlinpoet/pull/628
Add `constantStrings` to `CodeBlock`'s API: https://github.com/square/kotlinpoet/pull/630

`%C` makes it very explicit and low overhead for kotlinpoet, `constantStrings` makes it easier for consumers at the expense of overhead in plumbing it down

**Comment by swankjesse** [comment]
Ew. Can we ask the Kotlin folks to do this at build time?

**Comment by swankjesse** [comment]
Ie. this problem isn't really a codegen problem.

**Comment by ZacSweers** [comment]
There's a long standing youtrack for it: https://youtrack.jetbrains.com/issue/KT-17755

But it hasn't seen much activity and has been open for 3 years

**Comment by JakeWharton** [comment]
Seems like we should disable the margin string feature until it's fixed in the compiler

**Comment by Egorand** [comment]
Agree. As a workaround, pass the string as `%L` and escape it manually (e.g. `"\"hello\""`).

**Comment by ZacSweers** [comment]
#654 for the new proposal. I know this is partially addressed in a future kotlin release per https://github.com/JetBrains/kotlin/pull/2159, but also think the new solution is a reasonable (even if temporary) path forward
