### ISSUE TITLE
Escape enum values that are invalid or are Kotlin keywords

### ISSUE THREAD

**Issue by mkobit** [square/kotlinpoet#631]
I've seen a couple other issues for escaping (like https://github.com/square/kotlinpoet/issues/476, https://github.com/square/kotlinpoet/issues/293, and https://github.com/square/kotlinpoet/issues/326, https://github.com/square/kotlinpoet/issues/369), so I think this is probably in the realm of things that `kotlinpoet` should handle.

Example

```kotlin
import com.squareup.kotlinpoet.TypeSpec

fun main() {
  println(TypeSpec.enumBuilder("MyEnum")
      .addEnumConstant("thing-with-hyphen")
      .build())

  println("-".repeat(20))

  println(TypeSpec.enumBuilder("name-with-hyphen")
      .addEnumConstant("thing-with-hyphen")
      .build())

  println("-".repeat(20))

  try {
    TypeSpec.enumBuilder("continue")
        .addEnumConstant("thing-with-hyphen")
        .build()
  } catch (exception: Exception) {
    exception.printStackTrace()
  }

  println("-".repeat(20))

  try {
  println(TypeSpec.enumBuilder("MyEnum")
      .addEnumConstant("continue")
      .build())
  } catch (exception: Exception) {
    exception.printStackTrace()
  }
}

```

Output:

```
enum class MyEnum {
    thing-with-hyphen
}

--------------------
enum class `name-with-hyphen` {
    thing-with-hyphen
}

--------------------
java.lang.IllegalArgumentException: not a valid name: continue
	at com.squareup.kotlinpoet.TypeSpec$Builder.<init>(TypeSpec.kt:405)
	at com.squareup.kotlinpoet.TypeSpec$Companion.enumBuilder(TypeSpec.kt:712)
	at MkKt.main(mk.kt:17)
	at MkKt.main(mk.kt)
--------------------
java.lang.IllegalArgumentException: not a valid enum constant: MyEnum
	at com.squareup.kotlinpoet.TypeSpec$Builder.build(TypeSpec.kt:605)
	at MkKt.main(mk.kt:29)
	at MkKt.main(mk.kt)
```

It would be useful to have the enum values automatically escaped similar to other places in `kotlinpoet`.

**Comment by Egorand** [comment]
Sounds reasonable to me. Please feel free to submit a PR.

**Comment by shaishavgandhi05** [comment]
Is this change really required? We explicitly only disallow types that have reserved keywords as their name. I get that it's _possible_ to have reserved keywords as names of types but is that ever really required? For one thing, all the reserved keywords are lowercase and types _should_ start with uppercase letter (the IDE will warn you about it).

I guess what I'm grappling with is whether KotlinPoet should allow generation of code that will have a warning anyway (and a very basic one at that).

**Comment by Egorand** [comment]
Yeah, I tend to agree with @shaishavgandhi05 here. While double-tick-escaped function, property and parameter names are common, I've never seen cases of this in type or enum constant names. I think this is where we should draw the line unless there's a compelling case to do otherwise.

**Comment by mkobit** [comment]
Although I dislike the asymmetry with escaping and I think it will be difficult to try and abide by all IDE warnings in code generation, there is still the possibility being able to generate uncompilable code.

```kotlin
import com.squareup.kotlinpoet.TypeSpec

fun main() {
  println(TypeSpec.enumBuilder("MyEnum")
      .addEnumConstant("constant with space")
      .build())

  println("-".repeat(20))

  println(TypeSpec.enumBuilder("name with space")
      .addEnumConstant("thing with space")
      .build())
}
```

Output

```
enum class MyEnum {
    constant with space
}

--------------------
enum class `name with space` {
    thing with space
}
```

If escaping enum values is decided against, maybe an error could be thrown earlier instead?

**Comment by mkobit** [comment]
@Egorand and @shaishavgandhi05 (sorry for direct ping) how do you feel about what was [mentioned above](https://github.com/square/kotlinpoet/issues/631#issuecomment-470115402)?

**Comment by Egorand** [comment]
Sorry for the slow response @mkobit. 

Yeah, inconsistency in behavior is indeed a problem. I never really felt good about auto-escaping names, firstly because there didn't seem to be a good solution to apply auto-escaping everywhere, so we had to fix it up in multiple places in the codebase. Second, it's something that's easy to fix in the client code: if you suspect you'll have names containing illegal characters you can preventively escape them in your code before passing to KotlinPoet. It's hard to draw the line now that we have this behavior implemented in multiple places, so naturally if it doesn't work for some names it'll be perceived as a bug. Changing my mind again, I'd accept PRs fixing lack of auto-escaping in names going forward in order to preserve consistency. @shaishavgandhi05, what are your thoughts?

**Comment by JakeWharton** [comment]
Should escaping work everywhere provided you're using `%N`?

**Comment by Egorand** [comment]
@JakeWharton that's a good call, I think it should. The case in question though is generating types with names that need to be escaped.

**Comment by JakeWharton** [comment]
Sure but I mean if KotlinPoet escapes everywhere and you use `%N`
everywhere you should never get a compilation error from a name with a
space no matter where it's used.

**Comment by Egorand** [comment]
Yeah, the best solution I see is to implement auto-escaping for args to `%N` and use `%N` internally every time we emit names.

**Comment by mkobit** [comment]
@Egorand haven;t checked yet, but is this implicitly fixed by changes like https://github.com/square/kotlinpoet/issues/673#event-2263266786 ?

**Comment by Egorand** [comment]
Yep, I think so, since enum constants are `TypeSpec`s, their `ClassName`s should get escaped properly
