### ISSUE TITLE
How to determine if an Element is a class or a Kotlin object?

### ISSUE THREAD

**Issue by prefect4742** [square/kotlinpoet#639]
Is there a way (that I'm missing) to determine if an Element is a Kotlin object and not a class? I have an annotated object and still it says to be ElementKind.CLASS.

**Comment by JakeWharton** [comment]
That doesn't seem to be related to this library

**Comment by prefect4742** [comment]
Yep, I misread (still new at annotation processors and didn't see kotlinpoet was builf on top of a lot of stuff...).

If anyone is interested I came across https://stackoverflow.com/a/50975195/11067753 and modified it slightly (it's the element and not its parent that should be checked for INSTANCE).
