### ISSUE TITLE
Wrong Line Change Location

### ISSUE THREAD

**Issue by yuyang272999712** [square/kotlinpoet#640]
`constructorFunSpec.addStatement("obj.${it.simpleName} = $codeStr.${getBundleMethodByFieldType(fieldType)} ?: throw NullPointerException(\"Field [$it.simpleName] must not be null in [${it.enclosingElement.simpleName}]!\")",
                            bundleKey)`

generates
![image](https://user-images.githubusercontent.com/13271297/53854296-e5715480-4003-11e9-8a34-c270d46dc44b.png)

help,thanks

**Comment by Egorand** [comment]
Option 1 (recommended): Use `%S` to tell the generator that what you're passing in is a string literal that shouldn't be auto-wrapped:
```kotlin
constructorFunSpec.addStatement(
  "obj.${it.simpleName} = $codeStr.${getBundleMethodByFieldType(fieldType)} ?: throw NullPointerException(%S)",
  "Field [$it.simpleName] must not be null in [${it.enclosingElement.simpleName}]!",
  bundleKey
)
```
Option 2: Use `·` instead of ` ` for spaces that shouldn't wrap:
```kotlin
constructorFunSpec.addStatement("obj.${it.simpleName} = $codeStr.${getBundleMethodByFieldType(fieldType)} ?: throw NullPointerException(\"Field [$it.simpleName]·must·not·be·null·in·[${it.enclosingElement.simpleName}]!\")", bundleKey)
```
