### ISSUE TITLE
Applying annotation to a single statement seems to be not possible

### ISSUE THREAD

**Issue by dimsuz** [square/kotlinpoet#649]
I am trying to wrap my head around emitting code which would look like this:

```kotlin
fun operation() {
  @Supress("UNCHECKED_CAST")
  val value = otherValue as SomeClass<*>
  println(value)
}
```
So far I can't find a good way to do this without pasting literal text (which would not insert correct imports)

Neither `addStatement()` nor `CodeBlock.builder()` do not accept `AnnotationSpecs`, and there's no `%X` format modifier for annotations.

Is this not supported? 
What would you recommend to do in this situation?

**Comment by swankjesse** [comment]
`%L` ?

**Comment by shaishavgandhi05** [comment]
Hmm `%L` seems to not emit the `@`. 
```kotlin
@Test fun test() {
    val annotation = AnnotationSpec
        .builder(ClassName.bestGuess("Suppress"))
        .addMember("%S", "UNCHECKED_CAST")
        .build()
    val funSpec = FunSpec.builder("operation")
        .addStatement("%L", annotation)
        .build()

    assertThat(funSpec.toString()).isEqualTo("""
      |fun operation() {
      |    Suppress("UNCHECKED_CAST")
      |}
      |""".trimMargin())
  }
```

For now you'd have to add the `toString()` to the `annotation`.

Should this be covered by `%N`?

**Comment by dimsuz** [comment]
Yes, I've tried `%L` but it only works when emitting annotations as members of other annotations (as can be seen in `README.md`). When used in a regular statement it omits `@` causing generated code to fail compilation.

**Comment by JakeWharton** [comment]
That just seems like a bug to fix!
