### ISSUE TITLE
Provide ability to set originating element on FileSpec

### ISSUE THREAD

**Issue by technoir42** [square/kotlinpoet#657]
https://github.com/permissions-dispatcher/PermissionsDispatcher generates multiple top-level functions, properties and types per annotated element so we have to add the same originating element to every `FunSpec`, `PropertySpec` and `TypeSpec`. I think it'd make more sense to set originating element once for the whole `FileSpec` in such case.

**Comment by JakeWharton** [comment]
Files don't contribute actual API. The fact that you generate those all in the same file is an implementation detail of your processor. You could change it to generate one file per function, property, and type and your consumers would be none the wiser. It is those functions, properties, and types, however, which are the things you are creating as a result of parsing the information of an element. That is why they track originating elements but files do not.

**Comment by technoir42** [comment]
Isn't the sole purpose of the originating elements API to pass originating elements to Filer so it can associate the generated files with annotated elements?

```java
FileObject createResource​(JavaFileManager.Location location,
                          CharSequence moduleAndPkg,
                          CharSequence relativeName,
                          Element... originatingElements)
```

My other concern is that kapt might perform some redundant lookups for duplicate originating elements. Who do you think should be responsible for de-duplicating them? Kapt/Gradle or annotation processors?

**Comment by JakeWharton** [comment]
> Isn't the sole purpose of the originating elements API to pass originating elements to Filer so it can associate the generated files with annotated elements?

Yes, but this isn't an argument for or against adding them to the file spec.

> My other concern is that Kapt/Gradle might perform some redundant lookups for duplicate originating elements. Who do you think should be responsible for de-duplicating them? Kapt/Gradle or annotation processors?

You are not responsible. A single element can produce multiple files. Multiple elements can produce a single file.

**Comment by technoir42** [comment]
In my case each generated file corresponds to a single element/single source file but the element is repeated multiple times in the `originatingElements` array. This might cause Kapt to think that the processor is not isolating https://github.com/JetBrains/kotlin/blob/b2ad82b7d2bba7983a1724dfda790de6e052ffce/plugins/kapt3/kapt3-base/src/org/jetbrains/kotlin/kapt3/base/incremental/incrementalProcessors.kt#L108-L109.

So I think Kapt and perhaps Kotlinpoet should de-duplicate elements before passing them to `Filer`. The other option is to add `addOriginatingElement` for `FileSpec.Builder`.

**Comment by JakeWharton** [comment]
Adding an originating element to file spec doesn't solve the problem of duplication. If anything, it only serves to add to it. So we should just pursue ensuring kapt and Gradle for javac are behaving correctly for them and file any bugs therein. I'm not sure we want it to be KotlinPoet's job to de-duplicate
