### ISSUE TITLE
Support callable references

### ISSUE THREAD

**Issue by tadfisher** [square/kotlinpoet#663]
I frequently get tripped up generating function references due to a combination of the syntax required and how KotlinPoet handles imports.

For example, say I would like to generate a reference to the `Taco` constructor:

```kotlin
import com.example.Taco

val tacoFactory: () -> Taco = ::Taco
```

In KotlinPoet, I would try this, and it produces the expected output:

```kotlin

val TACO = ClassName("com.example", "Taco")

val file = FileSpec.builder("", "Taco.kt")
    .addProperty(
        PropertySpec.builder("tacoFactory", LambdaTypeName.get(null, emptyList(), TACO))
            .initializer("::%T", TACO)
            .build()
    )
    .build()
```

However, if Taco is a nested class, this doesn't work, because the syntax requires the `::` to come *after* the enclosing type. Replacing `TACO` above with `ClassName("com.example", "Food", "Taco")`:

```kotlin
import com.example.Food

val tacoFactory: () -> Food.Taco = ::Food.Taco      // This should be Food::Taco
```

To get this to work in the general case (e.g. for any `ClassName`, nested or not) requires a bunch of boilerplate that could be handled by KotlinPoet itself.

```kotlin
fun ClassName.constructorReference(): CodeBlock {
    val enclosingClassName = enclosingClassName()
    return if (enclosingClassName != null) {
        CodeBlock.of("%T::%L", enclosingClassName, simpleName)
    } else {
        CodeBlock.of("::%T", this)
    }
}
```

Of course, the `else` case isn't semantically correct, as it only works when KotlinPoet is able to import the type and use it without the qualifying package. I'm not sure how the above code could be modified to automatically import the non-nested type if I only use it in a constructor reference.

In addition to constructor references, there are also function and property references, which are syntactically similar to `MemberName`, but with the reference operator required before the member name in both qualified and unqualified usages. These are similarly difficult to generate if they are top-level members, as KotlinPoet wants to both emit the name and handle the import.

**Comment by Egorand** [comment]
That's interesting. How does that work with deeply nested types, e.g. `com.example.Foo.Bar.Taco`? Will the correct constructor reference look like `Foo.Bar::Taco`?

In general, KotlinPoet's API focuses on high level syntax and it doesn't provide APIs for generating function bodies or property initializers, hence I don't think we want to provide helpers for creating constructor/function/property references.

**Comment by JakeWharton** [comment]
It's pretty much a member reference and affects imports so I think it's in the wheelhouse of the project.

**Comment by tadfisher** [comment]
@Egorand Yep, `Foo.Bar::Taco` is correct.

**Comment by Egorand** [comment]
Cool, no objections to supporting it. Interested in submitting a PR @tadfisher? Would the following API cover all use cases?
```kotlin
// ClassName
fun constructorReference(): CodeBlock

// MemberName
fun reference(): CodeBlock
```

**Comment by tadfisher** [comment]
Sure, I can take a shot.

**Comment by tadfisher** [comment]
Hmm, I don't think the suggested API could be implemented where CodeWriter could import static members. How about adding a new format platceholder:

> `%R` emits a *callable* reference. A callable reference may refer to a constructor, function, or property that can be accessed in a static context. Types and members will be imported if possible. Arguments for callable references must be of type `ClassName` or `MemberName`.

**Comment by Egorand** [comment]
Implementations would still need to rely on `%T` and `%M` to allow `CodeWriter` to figure out imports, plus you'd use `%N` whenever you need a simple name for a `ClassName`. Is there something I'm missing?

**Comment by tadfisher** [comment]
How would `constructorReference()` emit `com.example::Taco`?

**Comment by Egorand** [comment]
Even if it wasn't the case, it's a method on `ClassName` so you can use `packageName` directly. I feel like adding a new placeholder for this use-case is overly complex.

**Comment by tadfisher** [comment]
Sounds good, I'll try it out.
