### ISSUE TITLE
How do you return Nothing?

### ISSUE THREAD

**Issue by hendraanggrian** [square/kotlinpoet#666]
`Nothing` always translates to `Void`. Case in point, this builder:

```kotlin
FunSpec.builder("noGetter")
    .returns(Nothing::class)
    .addStatement("throw UnsupportedOperationException()")
    .build()
```

Generates this code:

```kotlin
fun noGetter(): Void {
    throw UnsupportedOperationException()
}
```

**Comment by Egorand** [comment]
`Nothing` gets translated into `Void` in bytecode, hence reflection gives you `Void`. You can work around it by creating your own version of `Nothing`:
```kotlin
.returns(ClassName("kotlin", "Nothing"))
```

**Comment by hendraanggrian** [comment]
Quick and helpful, thanks!
