### ISSUE TITLE
Unclear support for nonstatic members

### ISSUE THREAD

**Issue by lowasser** [square/kotlinpoet#667]
The top-level documentation suggests that %M is used for "members that are accessible in a static context," suggesting it's not appropriate for instance properties or functions.  Some of the examples suggest it might be usable for instance properties, but it's not clear.

It's not at all clear how to dynamically refer to instance functions or properties that may still require escaping, e.g. because they may use reserved words like `package`.  When I use `%M` for an instance property, I often get nonsensical results like `myBuilder.com.foo.bar.baz.MyBuilder.myProperty`.  Is there an already supported approach to dynamically referring to instance members with escaping?

**Comment by lowasser** [comment]
To be clear, that code was generated from the line `.addStatement("return %L.%M", builderCode, foo.barMember())`.

**Comment by swankjesse** [comment]
Think of `%M` as members that need to be imported. If we dumped the entire path without the import we have a bug. (We might need to alias it for name collisions?!)

**Comment by lowasser** [comment]
Okay, sure.  But what should I be doing _instead_ for instance members that might need escaping and therefore can't use %L?

**Comment by lowasser** [comment]
(None of the other sections of documentation seem to cover that case explicitly.  Inventing a fake PropertySpec/FunSpec and using `%N` might work, but is that really how I'm supposed to do it?)

**Comment by Egorand** [comment]
It's a use-case we haven't considered, `%M` has been introduced for importable functions/properties (should probably review the docs to make it less confusing). What we probably want is accepting `MemberName`s as arguments for `%N`, so you'll get a properly escaped simple name.

**Comment by lowasser** [comment]
All right.  Consider this a feature request for that, then :) In the meantime, I'll try the fake PropertySpecs etc.

**Comment by JakeWharton** [comment]
`%N` not escaping also sounds like a bug

**Comment by lowasser** [comment]
%N does escape, but it seems to be intended for use to refer to code we're using KotlinPoet to generate, not for API we're simply _referencing_ from KotlinPoet generated code.

**Comment by Egorand** [comment]
Escaping isn't done through `%N` at the moment but it's something I wanna address.
