### ISSUE TITLE
superclass generates "extends" instead of ":"

### ISSUE THREAD

**Issue by ShortyFR** [square/kotlinpoet#68]
When specifying a superclass on a class builder, the generated class contains the "extends" keyword instead of ":"

val classBuilder = TypeSpec.Companion.classBuilder("Child")
classBuilder.superclass(TypeName.Companion.get(Parent::class))

Produces :
Child extends Parent

Instead of :
Child: Parent

**Comment by JakeWharton** [comment]
Fixed by #67.

**Comment by ShortyFR** [comment]
Right, sorry, missed the previous issue :(
