### ISSUE TITLE
[Question] Parameterized type by nested inner class

### ISSUE THREAD

**Issue by sav007** [square/kotlinpoet#681]
I'm probably missing something but how to create parameterized type by inner nested class?
For instance to generate this:
```
data class TestQuery<TestQuery.Data> {
    .... 
   data class Data {
     ....
   }
}
```

Trying these instructions:
```
val dataTypeName = ClassName(packageName = "", simpleName = "Query", simpleNames = *arrayOf("Data"))
val type = Query::class.asClassName().parameterizedBy(dataTypeName)
```

will emit redundant import `import TestQuery`:
```
import TestQuery

data class TestQuery<TestQuery.Data> {
    .... 
   data class Data {
     ....
   }
}
```

**Comment by Egorand** [comment]
Could you please share the complete failing test case? `data class TestQuery<TestQuery.Data>` will not compile since a type variable can't contain a `.`.

**Comment by sav007** [comment]
Sorry my bad of the sample, this is more correct:
```
data class TestQuery : Query<TestQuery.Data> {
    .... 
   data class Data {
     ....
   }
}
```

**Comment by Egorand** [comment]
I'd also be interested in seeing the code you use to generate this sample. Thank you!

**Comment by sav007** [comment]
The code was extracted from the large project but overall it looks like this:
```
interface Query<D> {
   ...
}

val dataTypeName = ClassName(packageName = "", simpleName = "TestQuery", simpleNames = *arrayOf("Data"))
val superInterfaceType = Query::class.asClassName().parameterizedBy(dataTypeName)

...

TypeSpec.classBuilder("TestQuery")
    .addSuperinterface(superInterfaceType)
...
```

**Comment by Egorand** [comment]
Here's a test case based on the code snippet you've provided that passes for me:
```kotlin
@Test fun genericParamDefaultPackage() {
  val dataTypeName = ClassName(packageName = "", simpleName = "TestQuery", simpleNames = *arrayOf("Data"))
  val superInterfaceType = Query::class.asClassName().parameterizedBy(dataTypeName)
  val file = FileSpec.builder("", "Test")
      .addType(TypeSpec.classBuilder("TestQuery")
          .addSuperinterface(superInterfaceType)
          .addProperty("foo", Int::class)
          .build())
      .build()
  assertThat(file.toString()).isEqualTo("""
    |import kotlin.Int
    |
    |class TestQuery : Query<TestQuery.Data> {
    |  val foo: Int
    |}
    |""".trimMargin())
}
```
Don't think the issue is in how we handle imports in the case of nested types.

**Comment by sav007** [comment]
I found that if you provide package name in `FileSpec.builder` than this issue occurs:
```
val dataTypeName = ClassName(packageName = "", simpleName = "TestQuery", simpleNames = *arrayOf("Data"))
    val superInterfaceType = Query::class.asClassName().parameterizedBy(dataTypeName)
    val file = FileSpec.builder("com.example", "TestQuery")
        .addType(TypeSpec.classBuilder("TestQuery")
            .addSuperinterface(superInterfaceType)
            .addType(TypeSpec.classBuilder("Data").build())
            .build())
        .build()
```

**Comment by Egorand** [comment]
In that case you need `TestQuery.Data` to also be in `com.example`, otherwise they will be imported. Unlike Java, in Kotlin you can import types declared in the default package.

**Comment by sav007** [comment]
Sorry but what do you mean by:
> In that case you need TestQuery.Data to also be in `com.example`

`Data` is a nested class in `TestQuery`, how can you include it to `com.example` package?

**Comment by Egorand** [comment]
In your example
```kotlin
val dataTypeName = ClassName(packageName = "", simpleName = "TestQuery", simpleNames = *arrayOf("Data"))
```
needs to be changed to
```kotlin
val dataTypeName = ClassName(packageName = "com.example", simpleName = "TestQuery", simpleNames = *arrayOf("Data"))
```

**Comment by sav007** [comment]
Agh, that. Ok it seems that I have to restructure the code and pass the destination package down to the compiler rather than just specify it at the end when writing generated type to file in `FileSpec`.
Thanks!
