### ISSUE TITLE
Proposal: Expand constants available for all Kotlin compiler built-ins

### ISSUE THREAD

**Issue by ZacSweers** [square/kotlinpoet#684]
Currently the available built-ins are sort of based around the original primitive types, but there are common other Kotlin compiler built-ins that are compiler intrinsics. I find myself copying these around every time I work with KotlinPoet as a result, and think they'd be a good fit to make available top-level like the other built-ins.

Examples:
- `kotlin.String`
- `kotlin.collections.List` (and set and map)
- unsigned types

**Comment by Egorand** [comment]
Sounds good! Are unsigned types still experimental, or not anymore?

**Comment by ZacSweers** [comment]
They're still experimental, but could be added when they're stable or annotated with the corresponding experimental annotation: https://kotlinlang.org/docs/reference/basic-types.html#experimental-status-of-unsigned-integers
