### ISSUE TITLE
How to set Map<String, KClass<out Any>> as property type?

### ISSUE THREAD

**Issue by ankitDev-git** [square/kotlinpoet#692]
How can I generate below line of code using Kotlinpoet?
`val myMap:Map<String, KClass<out Any>>`
I initialize myMap in init block.

**Comment by ankitDev-git** [comment]
How can I generate below line of code using Kotlinpoet?
`val myMap:Map<String, KClass<out Any>>`
I can initialize myMap in init block.

**Comment by ankitDev-git** [comment]
`Map::class.asClassName()
            .parameterizedBy(String::class.asTypeName(), KClass::class.asClassName().parameterizedBy(TypeVariableName("out Any")))`

**Comment by Egorand** [comment]
I replied to your StackOverflow question. Thanks for submitting your question there - we normally use Issues for bug reports and feature requests only.
