### ISSUE TITLE
Enum constants with spaces are not escaped properly

### ISSUE THREAD

**Issue by vlsi** [square/kotlinpoet#698]
For instance:
```
TypeSpec.enumBuilder("MyEnum")
  .addEnumConstant("test test")
  .addEnumConstant("0constants")
  .addEnumConstant("with.dots") // dots are illegal, so this should fail
  .build()
```

The first one contains space, the second one starts with digit, so both should be escaped with backticks.

**Comment by Egorand** [comment]
Interesting, that's actually two issues: first is that we don't escape constants with spaces, and second is that we incorrectly escape names with dots. The first one is easy to fix. For the second one, we make an invalid assumption that any sequence of characters can be turned into a valid name once escaped. I'll open a separate ticket for this.
