### ISSUE TITLE
Referencing class defined in same file no longer works

### ISSUE THREAD

**Issue by george-hawkins** [square/kotlinpoet#702]
Up until commit 20ef380 this Kotlin could be generated with the following Poet code:

```
package com.example

class Bar

class Foo {
    val bar: Bar = Bar()
}
```

```
@Test
fun `two classes with property`() {
    val className = ClassName("", "Bar")

    val foo = FileSpec.builder("com.example", "Foo")
        .addType(TypeSpec.classBuilder(className)
            .build())
        .addType(TypeSpec.classBuilder("Foo")
            .addProperty(PropertySpec.builder("bar", className)
                .initializer(CodeBlock.of("%T()", className))
                .build())
            .build())
        .build()

    println(foo)
}
```

As a result of commit 20ef380 this no longer works - even though `Bar` is defined in the same file as `Foo` it now appears as an additional import and you end up with:

```
package com.example

import Bar // <-- This is the problem.

class Bar

class Foo {
  val bar: Bar = Bar()
}
```

`Bar` used to be excluded from imports by this check in `CodeWriter.importableType(className: ClassName)`:

```
if (className.packageName.isEmpty()) {
  return
}
```

But this check was removed as part of PR #636.

Note that it's not the adding of class `Bar` itself that causes the addition of the incorrect import, it's the adding of property `bar`, that needs class `Bar`, that results in this.

**Comment by JakeWharton** [comment]
This seems working as intended. Bar is in com.example not the default package.

**Comment by Egorand** [comment]
Oh, Jake's right, I overlooked the package declaration. 

Since you're referencing `com.example.Bar`, you should use `ClassName("com.example", "Bar")`. `ClassName("", "Bar")` references `Bar` from the default package, hence a file in `com.example` has to import it, so the generated code is correct.
