### ISSUE TITLE
how do i generate a partial class ?

### ISSUE THREAD

**Issue by amirziarati** [square/kotlinpoet#705]
im trying to add a class with a partial modifier and i dont see a partial modifier in KModifier class. is there any other way to do this ?

**Comment by JakeWharton** [comment]
There is no `partial` modifier in Kotlin. That's a C# thing.

**Comment by amirziarati** [comment]
oh man you are right :/ i should post this on kotlin support page :/ 

i really need it so i can run something in init method of some class with annotated field without user of my library having to do this :/

any idea ?
this is how they can use it:

`@Encrypt("raw value")
lateinit var API_KEY_VALUE: String`

in generated file i have:

`fun Constants.injectDecryptedValues() {
    API_KEY_VALUE= AESEncrypter().decrypt("encrypted value");
}`

i used extnsion method and then user of annotation has to call injectDecryptedValues() in their init block like below:

`init {
        injectDecryptedValues()
    }`

any idea how can i do it for them ? i was thinking to add partial class having init block but Kotlin is not really best things of best languages as they claim :/

**Comment by Egorand** [comment]
I suggest you try [Stackoverflow](https://stackoverflow.com/questions/tagged/kotlin), or [Kotlin Community Slack](https://kotlinlang.org/community/), I don't see how your question is related to KotlinPoet.

**Comment by amirziarati** [comment]
ok thanks
