### ISSUE TITLE
Kotlinx-metadata integration

### ISSUE THREAD

**Issue by ZacSweers** [square/kotlinpoet#707]
Working doc and notes from offline conversation with @Egorand. The goal is to incorporate Kotlinx-metadata and to:

* Create ABI representations of existing code with KotlinPoet types from metadata
* Optionally offer the underlying immutable types layer (explained below)

### Incorporate immutable km types work as a separate artifact. 

Offered as a standalone public, immutable API over kotlinx-metadata's without exposing it directly. Will be used for KotlinPoet but also available for others' use as a read-only API.

* Keeping a separate artifact as there is information that cannot easily be expressed in KotlinPoet today. Some can be added (see KotlinPoet segment below), but some things are based on source and not necessarily relevant to kotlinpoet
  * jvm signatures
  * Some raw data that we wouldn't express the same way in kotlinpoet
  * Synthetic property annotation holder methods
* Artifact name tbd
* Current impl: https://github.com/ZacSweers/copydynamic/blob/master/metric/src/main/kotlin/io/sweers/metric/immutableNodes.kt
* Will shade kotlinx-metadata dependency, not exposed in public API
  * Mostly there now, just need to make flags alternative (or remove need for them)

### Add support for reading ABIs from class/kclass/metadata instances in KotlinPoet

Depending on immutable km artifact to do so, and being able to create KotlinPoet *specs representations from km types.

* TypeSpecs (supports all three)
  * `val okHttpClientType: TypeSpec = TypeSpec.fromKotlin(OkHttpClient::class)`
* FileSpec (only with class/kclass, or metadata with a package name)
* Underlying immutable km types available via `tags()` API, guaranteed to be present
  * `val kmProperty = propertySpec.tag<ImmutableKmProperty>()`
* Metadata coerced to source representation
  * For instance - in metadata, `String.() -> Unit` looks like `Function<String, Unit>`. We can coerce this to be a `LambdaTypeName` with receiver from the available metadata though, and express it idiomatically for source
    * Same for suspend functions/types and other lambdas.
* Creates compile-able ABIs. Function bodies, default value expressions, etc all stubbed with `TODO("Stub")` as needed.
* Current implementations:
  * https://github.com/ZacSweers/copydynamic/blob/master/metric/src/main/kotlin/io/sweers/metric/Metric.kt
  * https://github.com/ZacSweers/copydynamic/blob/master/metric/src/main/kotlin/io/sweers/metric/MetricKotlinPoet.kt

### Add contract (and maybe version requirement) specs to KotlinPoet

Contracts in particular are considered effectively as part of the signature of a function, and expressed in great detail in kotlin-metadata. Version requirements may not make sense in KotlinPoet, but are also expressed fully in KotlinMetadata.

Specific value to KotlinPoet - if using it as an IR, there's currently no way to read a `FunSpec`'s contract if it has one without manually trying to grep the function body's code.

### Open questions
* Name of metadata artifact
* Should the new metadata-based APIs be marked as experimental?

**Comment by swankjesse** [comment]
This is awesome!

**Comment by ZacSweers** [comment]
What do you think of actually _not_ shading kotlinx-metadata, and instead marking the kotlinpoet-km APIs as experimental? This would cover accessing them through tags as well. This way we can continue to expose `Flags` and not make unnecessary copies of its non-mutable types (enums, etc).

Something like `@ExperimentalKotlinPoetApi`?

That way this could also not necessarily be something that needs to wait for a 2.0 release

**Comment by ZacSweers** [comment]
I think this can be closed once the final naming is set up 👍

**Comment by ZacSweers** [comment]
This is done!
