### ISSUE TITLE
Use non-breaking space for beginControlFlow to prevent code breaking

### ISSUE THREAD

**Issue by neoneo** [square/kotlinpoet#712]
The space added by `beginControlFlow` sometimes causes a line break which in turn breaks code. The known workaround, to insert a non-breaking space, is not possible here.

This issue would be solved if the added space is a non-breaking space.

In the general case this was suggested in #551 but this issue is closed, in favor of tracking these issues separately.

**Comment by Egorand** [comment]
`beginControlFlow()` adds a non-breaking space (https://github.com/square/kotlinpoet/blob/32b38aea7d28ae0a91005b05f0c6541ea513760b/kotlinpoet/src/main/java/com/squareup/kotlinpoet/CodeBlock.kt#L394). IIRC it's a recent change, make sure you're using the latest version. If it still doesn't work properly - please provide a reproducible test case and we'll look at it.
