### ISSUE TITLE
[Question] How to write "instanceof" statement with kotlinPoet when dealing with generics?

### ISSUE THREAD

**Issue by bio007** [square/kotlinpoet#715]
I want to generate code like this:
```
val foo: List<Bar>
if (foo is ArrayList<*>) {
    //do something
}
```

Using poet code like this:
```
codeBlock.beginControlFlow("if (foo is %T)", parameter.asType())
codeBlock...
```

The `parameter` variable is of `VariableElement` type.

The problem is I get this:
```
if (foo is ArrayList<Bar>) {
    //do something
}
```
resulting in an error that it cannot check for instance of a erased type.

When I use `typeUtils` from `processingEnv` and wrap the `parameter` with `typeUtils.erasure` method I get this:
```
if (foo is ArrayList) {
    //do something
}
```
resulting in a different error that it's expecting type argument.

How can I generate ArrayList<*> from VariableElement with kotlinpoet?

Thanks!

**Comment by Egorand** [comment]
Two ways:

1. I believe `parameter.asType().asTypeName()` gives you a `ParameterizedTypeName`, which you can post-process like this:
```kotlin
val arrayListOfBar = parameter.asType().asTypeName()
val arrayList = arrayListOfBar.rawType
val arrayListOfStar = arrayList.parameterizedBy(STAR)
```
2. Pretty much the same with `erasure`:
```kotlin
val arrayList = typeUtils.erasure
val arrayListOfStar = arrayList.parameterizedBy(STAR)
```
Lmk if any of these worked.
