### ISSUE TITLE
Provide a simpler path for ParameterSpec creation

### ISSUE THREAD

**Issue by lowasser** [square/kotlinpoet#717]
Approximately 90% of the time I am creating `ParameterSpec`s, it takes the form `ParameterSpec.builder(name, type).build()`.  Modifiers on `ParameterSpec` are rare -- `noinline`, `crossinline`, and `vararg` are the only possibilities I can think of, and it makes sense that they're not the most common.

It makes lots of sense to provide a simpler constructor, pseudoconstructor, or factory method for this common case, instead of forcing users to go through the builder.

**Comment by JakeWharton** [comment]
For JavaPoet I've built the following: https://android.googlesource.com/platform/frameworks/data-binding/+/refs/heads/mirror-goog-studio-master-dev/compilerCommon/src/main/kotlin/android/databinding/tool/ext/javapoet_ext.kt
