### ISSUE TITLE
please give me a constructor to make ClassName with List<String>

### ISSUE THREAD

**Issue by anatawa12** [square/kotlinpoet#730]
Now I can new `ClassName` with two `String` and vararg `String`s. but I would like constructor with `List<String>`.

Of course, I know that way to make  `ClassName` with `List<String>`. but it is not good for performance:
```
val names = listOf("kotlin.collections", "Map", "Entry")
val className = ClassName(names[0], names[1], *names.drop(2).toTypedArray())
```

**Comment by JakeWharton** [comment]
This seems like a bad general-purpose API since it's not clear whether package fragments are individual strings or a single string and it's not clear whether nested types are individual strings or a single string.

Where is this data coming from and why is it in such a format?

**Comment by anatawa12** [comment]
This format comes from a java source file. I got a package name and simple names from exiting java source file.

On the other hand, I can get this format from the class file. When I read class file, I will get a string like `java/util/Map$Entry` for class discripter. I'll do `substringAfterLast('/').split('$')` to get simple names and will do `substringBeforeLast('/').replace('/', '.')` to get package name.

**Comment by JakeWharton** [comment]
I think we'd be happy to offer a converter directly from a descriptor string since it's an unambiguous format.

**Comment by anatawa12** [comment]
I think that's the best way to make ClassName from discripter. 

Could I change a request? I want to have a constructor like `constructor(packageName: String, vararg simpleNames: String)`

**Comment by anatawa12** [comment]
In my source, the package name is added after collecting simple names.

**Comment by JakeWharton** [comment]
Hmm, I lied! Descriptors are ambiguous because we cannot read the `InnerClass` attribute. So we don't know if `Foo$Bar` is `class Foo$Bar` or `class Foo { class Bar { }}`.

**Comment by anatawa12** [comment]
Sorry. I forgot that true. But It's not changed that if I get type name from source code, I'll get package name and list of smpleNames. I want to make `ClassName` from the two.

**Comment by JakeWharton** [comment]
Yeah we can fix the factory to be just package and varargs.

**Comment by anatawa12** [comment]
Should I make marge request?

**Comment by JakeWharton** [comment]
If you want. It has to be a new API with the old one marked as deprecated
with a level of hidden to maintain binary compatibility.
