### ISSUE TITLE
why not ParameterizedTypeName#enclosingType is ParameterizedTypeName? and why private

### ISSUE THREAD

**Issue by anatawa12** [square/kotlinpoet#735]
I think ParameterizedTypeName#enclosingType shoud be `ParameterizedTypeName?`. Because Users canot make enclosingType non-`ParameterizedTypeName?`.

**Comment by Egorand** [comment]
What's your use-case?

**Comment by anatawa12** [comment]
When I generate a Kotlin source code from Java.
In java, there are raw types. In Kotlin, there aren't. we use the star.
I want to convert all raw types into types with the star. like converting `Outer.Inner1<T>.Inner2` to `Outer<*>.Inner1<T>.Inner2<*>`. when doing this, I need enclosingType. If you say that "It's not usage of this API.", I should close this issue.
