### ISSUE TITLE
add type parameter for PropertySpec.toBuilder like ParameterSpec

### ISSUE THREAD

**Issue by anatawa12** [square/kotlinpoet#736]
I sometimes change Property's type but there is no way to do it.

**Comment by Egorand** [comment]
Agree, adding both `name` and `type` as parameters with default args feels appropriate. We just need to make sure we use `@JvmOverloads` to not break binary compatibility. Interested in submitting a PR?

**Comment by anatawa12** [comment]
Yes. I'll make PR tomorrow morning in Japan. (In West US, this afternoon or tonight)
