### ISSUE TITLE
add override with List for each function with vararg parameters

### ISSUE THREAD

**Issue by anatawa12** [square/kotlinpoet#737]
I often write source codes like this for many function invocations. I think it's not good for performance and it's not good readable code.
```
type.parameterizedBy(*typeArguments.toTypedArray())
```
if there is override with List, I can write like this.
```
type.parameterizedBy(typeArguments)
```

**Comment by Egorand** [comment]
Yep, that won't hurt. Wanna submit a PR?

**Comment by Egorand** [comment]
Also, I guess we'd wanna use `Collection` instead of `List` to accept other types of collections.

**Comment by anatawa12** [comment]
Yes, I do. But in Japan, It's night. So I’ll do tomorrow morning.

**Comment by anatawa12** [comment]
I think Collection is not good for some overrides. E.g. type parameters. Because the order has meaning for type parameters. Collection does not have to give meaning for order.

**Comment by Egorand** [comment]
> Yes, I do. But in Japan, It's night. So I’ll do tomorrow morning.

No worries, thanks!

> I think Collection is not good for some overrides. E.g. type parameters. Because the order has meaning for type parameters. Collection does not have to give meaning for order.

Good point!

**Comment by JakeWharton** [comment]
I would use Iterable. The reliance on order is then implied allowing sorted
sets and the like to be used.

**Comment by anatawa12** [comment]
Okay, I'll use it.

2019/07/30 9:44、Jake Wharton <notifications@github.com>のメール:

> I would use Iterable. The reliance on order is then implied allowing sorted
> sets and the like to be used.
