### ISSUE TITLE
Come up with a better artifact layout

### ISSUE THREAD

**Issue by Egorand** [square/kotlinpoet#745]
Libraries that process annotations and parse Kotlin metadata represent only a subset of KotlinPoet consumers, whereas other consumers, such as SQLDelight and Wire, have other types of input. Therefore, helpers for Metadata and Elements processing should be moved out of the main artifact, which should help keep it small and generic.

- Move recently introduced helpers for working with Kotlin metadata into a new artifact that depends on both `kotlinpoet` and `kotlinpoet-km`. **Milestone**: 1.4.
- Find good names for `kotlinpoet-km` and the new artifact. **Milestone**: 1.4.
- Move helpers for processing Elements into a new artifact. **Milestone**: 2.0.

**Comment by ZacSweers** [comment]
To make sure I'm reading this right - the elements would just be packaged into the helpers artifact in 1.4 right?

Also since they're all experimental, i think it would be find to be open to separating them from the start or 1.5

**Comment by Egorand** [comment]
Elements helpers have been in the main artifact from the very beginning, so moving them out will break compat, hence we should hold up until the next major release.

As for the metadata helpers, let's move them out before releasing 1.4. Even though they're experimental, this will reduce churn, and it's something we know we'll do anyway.

**Comment by ZacSweers** [comment]
Ahhh ok didn't realize you meant all the existing element APIs top. Sounds
good 👍
