### ISSUE TITLE
(Re)move backticks in builder output

### ISSUE THREAD

**Issue by RdeWilde** [square/kotlinpoet#746]
When outputting to Kotlin code, I get strange backticks in my code:

```
    @Serializable
    data class Payment(
        @Optional @SerialId(1) `val description`: String = "",
//                             ^
```
I get that this is for reserved keywords etc, but why does it include `val`?

I would like to see this (or no backticks at all):
```
    @Serializable
    data class Payment(
        @Optional @SerialId(1) val `description`: String = "",
//                                 ^
```

How do I change this? This is part of the code that generates the output:

```

        val classSpecBuilder = TypeSpec.classBuilder(name)
            .addModifiers(KModifier.DATA)
            .addAnnotation(ANNO_SPEC_SERIAL_SERIALIZABLE)

        val constructorSpec = FunSpec.constructorBuilder()

        descriptorProto.fieldList
            .forEach { fieldDescriptor ->

                val fieldName = camelCaseFieldName(fieldDescriptor.name).decapitalize()
                val className = fieldDescriptor.getFieldClassName(context.schema)

                val parameterBuilder = when{
                    fieldDescriptor.isMapField(context.schema) ||
                    fieldDescriptor.isRepeated -> ParameterSpec
                        .builder("val $fieldName",fieldDescriptor.getParamaterizeTypeName(context.schema))
                        // ^^^^^^^^^^^^^^^^^^^^^^^

                    else -> ParameterSpec.builder("val $fieldName",className)
                    // ^^^^^^^^^^^^^^^^^^^^^^^
                }
```

Thanks in advance,

**Comment by Egorand** [comment]
In order to declare a primary constructor parameter and declare it as a property at the same time, you'd have to create both a `ParameterSpec` and a `PropertySpec` with the same name. More info here: https://square.github.io/kotlinpoet/#constructors.

**Comment by RdeWilde** [comment]
Hi @egor-n , thanks for your fast response.

The output I got is good enough, except the backtick ` \` `character before `val`. 
Can't I just remove that and leave the rest to what it is?

See this example:
https://pl.kotl.in/z9aXEkukm

**Comment by Egorand** [comment]
You're creating a parameter called "val description", since it has a space in its name kotlinpoet escapes it. You can definitely post-process the output to remove backticks, but this functionality is outside of the scope of this library.

**Comment by RdeWilde** [comment]
That makes sense, but when I leave out the `val` it doesn't add it, though it is required for data classes. Also data classes should normally just have the parameters defined and not the properties. I search for an example of generating a data class, no luck yet.

**Comment by ZacSweers** [comment]
KotlinPoet handles generating the `val`. On mobile but a very simple data class looks like this:

```kotlin
val spec = TypeSpec.classBuilder("TestClass")
    .addModifier(KModifier.DATA)
    .addProperty(PropertySpec.builder("foo", String::class).builder()
        .initializer("foo") // To match the constructor param
        .build())
 
   .primaryConstructor(FunSpec.constructorBuilder()
        .addParameter("foo", String::class)
        .build())
    .build()
```

Generates

```kotlin
data class TestClass(val foo: String)
```

**Comment by Egorand** [comment]
@RdeWilde the link I shared earlier has an example of declaring a property as a primary constructor parameter. Data classes in fact can only declare properties inside the primary constructor, they can't have simple parameters. Follow the example and you should be fine.

**Comment by RdeWilde** [comment]
@ZacSweers @Egorand Now I get how it works, works like a charm! Thank you very much, you're my hero's ;-)

**Comment by RdeWilde** [comment]
One more question; I tried the same on an Enum:
``` 
        val enumSpec = TypeSpec.enumBuilder(name)
            .addProperty(PropertySpec.builder("number", Int::class.asClassName()).initializer("number").build())
            .primaryConstructor(FunSpec.constructorBuilder()
                .addParameter(ParameterSpec.builder("number",Int::class.asClassName())
                    .build())
                .build())        val enumSpec = TypeSpec.enumBuilder(name)
            .addProperty(PropertySpec.builder("number", Int::class.asClassName()).initializer("number").build())
            .primaryConstructor(FunSpec.constructorBuilder()
                .addParameter(ParameterSpec.builder("number",Int::class.asClassName())
                    .build())
                .build())
```

But the output lacks the `val` keyword :-( though it seems to match the example here (https://square.github.io/kotlinpoet/#enums):

```
val helloWorld = TypeSpec.enumBuilder("Roshambo")
    .primaryConstructor(FunSpec.constructorBuilder()
        .addParameter("handsign", String::class)
        .build())
// ...
    .addProperty(PropertySpec.builder("handsign", String::class, KModifier.PRIVATE)
        .initializer("handsign")
        .build())
    .build()
```

**Comment by RdeWilde** [comment]
I had to rearrange the order:
```
        val enumSpec = TypeSpec.enumBuilder(name)
            .primaryConstructor(FunSpec.constructorBuilder()
                .addParameter(ParameterSpec.builder("number",Int::class.asClassName())
                    .build())
                .build())
            .addProperty(PropertySpec.builder("number", Int::class.asClassName()).initializer("number")
                .build())
```

**Comment by Egorand** [comment]
The order shouldn't matter, if it does - it's a bug.

**Comment by RdeWilde** [comment]
I will test once I am at home, will create a new issue if it indeed is a bug.
