### ISSUE TITLE
Detect EditorConfig configuration for indentation

### ISSUE THREAD

**Issue by jmfayard** [square/kotlinpoet#749]
Hello,

for tools that produce code that is committed in the repository, like my Gradle plugin [buildSrcVersions](https://github.com/jmfayard/buildSrcVersions), it would be great if there was a way to detect and respect the indentation preferences of the user as configured in the https://editorconfig.org/ file.

**Comment by JakeWharton** [comment]
That seems like the responsibility of your plugin, not this library. Your plugin is an integration point where it makes sense to do this because you have access to the filesystem. KotlinPoet had no context as to where it's running (annotation processor, Gradle plugin, IDE plugin, etc.) let alone where on the filesystem to even begin to look.

**Comment by jmfayard** [comment]
Hello to any people reading this issue in the future. 

I implemented detecting the indents from `.editorconfig`.

If you don't want to re-invent the wheel, you can use my code (MIT-licensed) as a starting point:
https://github.com/jmfayard/buildSrcVersions/blob/84414da65573d9d6870983b581099a25d0243cce/plugin/src/main/kotlin/de/fayard/internal/EditorConfig.kt
https://github.com/jmfayard/buildSrcVersions/blob/84414da65573d9d6870983b581099a25d0243cce/plugin/src/test/kotlin/de/fayard/EditorConfigTest.kt

Passing the information to KotlinPoet itself is quite trivial

```kotlin
val fileSpec : FileSpecBuilder = TODO()
val fromDirectory : File = TODO() // for me: buildSrc/src/main/Kotlin
val defaultIndent = "    "
val findIndentForKotlin = EditorConfig.findIndentForKotlin(fromDirectory) ?: defaultIndent

filespec.indent(findIndentForKotlin).build()
```
