### ISSUE TITLE
ClassName empty name ambiguity

### ISSUE THREAD

**Issue by ZacSweers** [square/kotlinpoet#795]
This will pass right now on master

```kotlin
val name1 = ClassName("", "", "Taco")
val name2 = ClassName("", "Taco")
assertThat(name1).isEqualTo(name2)
```

This is because their `toString()` is used for equality, and their `toString()`s are surprisingly the same. Their canonical names are different (`".Taco"` and `"Taco"`, respectively).

Not sure if canonical name should match the toString() behavior, toString() should account for this, or if equality should just compare names in an override instead. Or some combination of these.

**Comment by JakeWharton** [comment]
Empty simple names should not be allowed.
