### ISSUE TITLE
Naming conflict for auto imported types

### ISSUE THREAD

**Issue by devkanro** [square/kotlinpoet#797]
# Description
I got some naming conflict with auto imported types like `kotlin.Any` in code generating, here are the recurring step.

01. Build a class named `Any` in file `Any.kt` with package `com.example.kotlinpoet`
02. Build a interface named `ListValue` in file `ListValue.kt` with package `com.example.kotlinpoet`
03. Make `ListValue` has superinterface `kotlin.List<kotlin.Any>`
04. Generate them all
05. You can get `ListValue` with code
```Kotlin
package com.example.kotlinpoet

interface ListValue: List<Any>
```
06. The `Any` of `List<Any>` will be `com.example.kotlinpoet.Any` not the `kotlin.Any` due to package `com.example.kotlinpoet` has a class named `Any`

# Suggested Solution?
Maybe we can make `FileSpec` belong a `PackageSpec`? `PackageSpec` will optimize imports.

Or we can make `FileSpec` has a 'context', we can set the context to FileSpec with the builder? FileSpec will emit the import with context.

The focus is to make `FileSpec` can discover each other, optimize the behavior of the auto-import class.

Another way is to make the `TypeName` has a not import flag, `FileSpec` will use the full name all the time.

**Comment by Egorand** [comment]
Could you please share a snippet of code that reproduces the problem?

**Comment by Egorand** [comment]
Yeah, `toString()` won't resolve imports for you.
