### ISSUE TITLE
Support multiple inits

### ISSUE THREAD

**Issue by ZacSweers** [square/kotlinpoet#801]
This is legal in kotlin, and they are just executed in source order

```kotlin
class Foo {
  init {}
  init {}
}
```

**Comment by Egorand** [comment]
Any reason why you'd ever have more than one?

**Comment by ZacSweers** [comment]
Proximity to the property it's initializing was a reason someone suggested
to me

**Comment by Egorand** [comment]
I'm really not sure it's a common use case that would justify us remodeling how we store properties and initializer blocks.

**Comment by ZacSweers** [comment]
It depends on if Kotlinpoet is trying to model kotlin's supported source
features or just an opinionated subset :). I don't have a strong feeling on
this one, but it does seem like if it supports inits then it should at
least be documented why it only supports one.

**Comment by Egorand** [comment]
Actually I just checked the code, and calling `addInitializerBlock()` multiple times will result in multiple `init`s being printed. One thing that's missing is being able to interleave property declarations with `init` blocks. Not sure we want it.

**Comment by ZacSweers** [comment]
Ah! So it works then and I just misread how that API works. Interleaving might come for free with #800 though
