### ISSUE TITLE
Trailing spaces on generated parameter function

### ISSUE THREAD

**Issue by ScottPierce** [square/kotlinpoet#827]
I've been running ktlint on the generated code from kotlin poet, because it's been working without issues. **I probably shouldn't do that**, but I think it's exposed a minor bug. Look at the generated code for the lambda extension on this function:

```Kotlin
@HtmlDsl
inline fun BodyContext.bold(
    vararg attrs: Pair<String, String?>,
    func: BodyContext.() -> Unit =
            {}
) {
    writer.writeTag("bold")
    writer.writeAttributes(attrs)
    writer.write('>')
    writer.indent()
    func()
    writer.writeNormalElementEnd("bold")
}
```

Which gets dinged by code style for:
```
.../dev.scottpierce/kotlin-html/kotlin-html-writer/src/genMain/kotlin/dev/scottpierce/html/writer/element/Bold.kt:51:9: Trailing space(s)
```

The generated code should probably be:
```Kotlin
func: BodyContext.() -> Unit = {}
```

I tried to pull the kotlin poet code that actually generates this, but it's very spread out, and is in the middle of a fairly large for loop. This code generates ~100 of these functions, but this is the only one that has this issue. You can look at the actual code [here](https://github.com/ScottPierce/kotlin-html/blob/scott/StyleRework/kotlin-html-generator/src/main/kotlin/dev/scottpierce/html/generate/task/GenerateElementsTask.kt#L110-L117)

**Comment by Egorand** [comment]
@ScottPierce unfortunately I can't access the code you linked since the link returns 404. In general, we don't prevent default values from being printed on the next line if the line limit is exceeded (which I believe was the case here), I think this is the correct strategy. I'm gonna close the issue now.
