### ISSUE TITLE
Can't escape identifier `List<io` because it contains illegal characters: <

### ISSUE THREAD

**Issue by KirillVolkov** [square/kotlinpoet#835]
Error:  e: [kapt] An exception occurred: java.lang.IllegalArgumentException: Can't escape identifier `List<io` because it contains illegal characters: <

Generated Method:
`
    @Get("accounts/{addresses}/info")
    suspend fun getInfo(
        @Path("addresses") addresses: List<String>,
        @Query("skip") skip: Int = 0,
        @Query("limit") limit: Int = DEFAULT_PAGE_SIZE
    ): List<EthInfo>
`

It happens only with suspend methods. If I try to generate
`
    @Get("accounts/{addresses}/info")
    fun getInfo(
        @Path("addresses") addresses: List<String>,
        @Query("skip") skip: Int = 0,
        @Query("limit") limit: Int = DEFAULT_PAGE_SIZE,
        callback: TypedCallback<List<EthInfo>>
` 

> All ok

P.S. List<EthInfo> is  List<io.companyname.model.response.EthInfo>

**Comment by Egorand** [comment]
It's not clear how it's KotlinPoet's fault. Can you please submit a reproducible test case?

**Comment by KirillVolkov** [comment]
@Egorand Ok, can you try to generate annotated suspend method with "List<Any>" return value?

**Comment by KirillVolkov** [comment]
![Снимок экрана 2019-11-22 в 18 34 02](https://user-images.githubusercontent.com/10828411/69438767-b5ffa500-0d56-11ea-80ba-00e6cfd73223.png)

**Comment by KirillVolkov** [comment]
It happens when I try to write my FileSpec to File

**Comment by C7ABT** [comment]
> Error: e: [kapt] An exception occurred: java.lang.IllegalArgumentException: Can't escape identifier `List<io` because it contains illegal characters: <
> 
> Generated Method: `@Get("accounts/{addresses}/info") suspend fun getInfo( @Path("addresses") addresses: List<String>, @Query("skip") skip: Int = 0, @Query("limit") limit: Int = DEFAULT_PAGE_SIZE ): List<EthInfo>`
> 
> It happens only with suspend methods. If I try to generate `@Get("accounts/{addresses}/info") fun getInfo( @Path("addresses") addresses: List<String>, @Query("skip") skip: Int = 0, @Query("limit") limit: Int = DEFAULT_PAGE_SIZE, callback: TypedCallback<List<EthInfo>>`
> 
> > All ok
> 
> P.S. List is List<io.companyname.model.response.EthInfo>

Hello, I got the same problems too. Would you plz show me how did you solve it?

**Comment by KirillVolkov** [comment]
@C7ABT use classes with list instead of just lists

**Comment by Syer10** [comment]
I started having this problem after restructuring one of my projects, I found an easy workaround is just using a Typealias.
