### ISSUE TITLE
How do I build a constructor where the field is `var` and can be `@annotated`?

### ISSUE THREAD

**Issue by eahau** [square/kotlinpoet#840]
like this:
```kotlin
data class Test (
  @Id
  var id: Long
) : Interface {
  override fun primaryKey() : Serializable = this
}
```

**Comment by Egorand** [comment]
Thanks for your question! We use the issue tracker for bug reports and feature requests only, a good place to ask usage questions is [StackOverflow](https://stackoverflow.com/questions/tagged/kotlinpoet).
