### ISSUE TITLE
char '$' in type name escape fail

### ISSUE THREAD

**Issue by YvesCheung** [square/kotlinpoet#841]
`A$B` is a valid Java identifier, but not a valid Kotlin type name.

`escapeIfNotJavaIdentifier().escapeIfKeyword().failIfEscapeInvalid()`
none of these method respond to '$'.

`TypeSpec.classBuilder("A\$B").build()` build an invalid type name!
``TypeSpec.classBuilder("`A\$B`").build()`` also build an invalid type name!

**Comment by Egorand** [comment]
Yeah, our valid identifier characters check is mostly based on JDK methods, should be updated to follow Kotlin rules.
