### ISSUE TITLE
KAPT: Elements.getPackageElement can not find class named with escape charater

### ISSUE THREAD

**Issue by YvesCheung** [square/kotlinpoet#842]
Using `Elements.getPackageElement` function to find set of TypeElement in PackageElement.
Only valid Java Identifier can be found.
Kotlin class named ```-A``` can not be found.

**Comment by JakeWharton** [comment]
kapt works on Java stubs which are produced from Java source files which cannot represent types that start with a dash character.

But, ultimately, this is unrelated to KotlinPoet.
