### ISSUE TITLE
Impossible to generate valid keyword enum, 1.4.4

### ISSUE THREAD

**Issue by Dkhusainov** [square/kotlinpoet#848]
kotlinpoet: 1.4.4

```kotlin
FileSpec
      .builder("a", "a")
      .addType(
        TypeSpec
          .enumBuilder("MyEnum")
          .addEnumConstant("object")
          .build()
      )
      .build()
      .writeTo(File("a"))
```

This fails with

```
java.lang.IllegalArgumentException: not a valid enum constant: MyEnum
	at com.squareup.kotlinpoet.TypeSpec$Builder.build(TypeSpec.kt:656)
```

1. Error message should contain invalid enum value as well as the type
2. If I add backtics to object string manually, kotlinpoet generates enum value with double backtics

**Comment by Dkhusainov** [comment]
Any ETA for 1.5 release?

**Comment by ZacSweers** [comment]
No. Please read #8 of this blog post: https://medium.com/@teejeetech/etiquette-in-open-source-projects-f302b6e19c38

**Comment by Dkhusainov** [comment]
I have to decide whether to wait for a fix or to workaround it. Asking for an ETA on a BUG(not feature, not api issue) that is blocking us is a completely normal and not "out of an etiquette from a medium blogpost".

**Comment by ZacSweers** [comment]
Sorry to hear you're blocked on this, but to reiterate what I was trying to get across with that article link: this is an open source project and we're not really able to provide ETAs. That applies for everything, including bugs. It will be released when it's ready. You can unblock yourself by forking and fixing it (and preferably PRing that fix back here!), or you can work around it. 

Even if you feel it's normal to ask for ETAs on OSS projects, knocking on the issue tracker here asking for one the day after submitting a bug and during the middle of a major holiday season is not really going to get you the answers you're looking for. The best thing you can do is submit a PR!

**Comment by Egorand** [comment]
The best way to speed up the process is to submit a fix.

**Comment by Egorand** [comment]
The fix has been merged, you should be able to use the snapshots while we're working on 1.5. I'd like for this to happen in January but no definite plans at the moment.

**Comment by Dkhusainov** [comment]
Thanks for the fix
