### ISSUE TITLE
Support copying of non-trivial, arbitrary annotations from source

### ISSUE THREAD

**Issue by manosbatsis** [square/kotlinpoet#860]
Copying arbitrary, complex annotations from source to generated code doesn't seem possible with the current API.

**Comment by Egorand** [comment]
This is supported through annotation processing using the `javax.lang.model.element` API, see [AnnotationSpec.get()](https://square.github.io/kotlinpoet/1.x/kotlinpoet/com.squareup.kotlinpoet/-annotation-spec/get/). We don't, however, provide any API for parsing source files nor do we plan to add this functionality.

**Comment by manosbatsis** [comment]
Thanks for the reply @Egorand - kept looking for this without seeing it, got sillier than a silly issue tbh. Cheers
