### ISSUE TITLE
Type mismatch

### ISSUE THREAD

**Issue by liujingxing** [square/kotlinpoet#863]
I need to copy the test method from `A.java` into `B.kt` via kotlinpoet, but the compiler prompts
`Type mismatch: inferred Type is Java. Lang. String but kotlin. The String was expected`
![image](https://user-images.githubusercontent.com/7237396/71976227-c4474900-3250-11ea-9a14-e0c9821b8588.png)
![image](https://user-images.githubusercontent.com/7237396/71976343-083a4e00-3251-11ea-8c2f-3e4b9eb1efc8.png)

![image](https://user-images.githubusercontent.com/7237396/71976790-248aba80-3252-11ea-994a-badf84edab57.png)

How do I automatically import kotlin.string into `B.kt`  ?

**Comment by Egorand** [comment]
Your input has that type as `java.lang.String` hence this is what you get in the output. KotlinPoet doesn't auto-convert `java.lang.String` to `kotlin.String` cause these types are not interchangeable.

**Comment by liujingxing** [comment]
![image](https://user-images.githubusercontent.com/7237396/72032599-ca7a0b80-32ca-11ea-9f0d-437cbf267a68.png)
I tried to copy from `A.kt` to `B.kt` and the same thing happened, What do I do?

**Comment by Egorand** [comment]
The annotation processor will still see the type as `java.lang.String`, the only place that contains the correct type information is the metadata. You'll need to use the `kotlinpoet-metadata-specs` API, see https://github.com/square/kotlinpoet/tree/master/kotlinpoet-metadata-specs.
