### ISSUE TITLE
Import extension operators

### ISSUE THREAD

**Issue by devkanro** [square/kotlinpoet#870]
I have defined an extension operator like this:
```Kotlin
package foo.bar.baz

operator fun MyClass.plus(other: MyClass): MyClass {}
```

How I can import it in kotlinpoet?
```Kotlin
FunSpec.builder("myFunction")
    .addParameter("value", MyClass::class)
    .returns(MyClass::class)
    .addStatement("return this.value + value")
    .build()
```
It will generate:
```Kotlin
fun myFunction(value: MyClass): MyClass {
   return this.value + value // foo.bar.baz.plus not import
}
```

In my use case, I can't get `FileSpec.Builder`  in this timing. How can I import it?

**Comment by Egorand** [comment]
For normal functions you could use `MemberName`:

```kotlin
val plus = MemberName("foo.bar.baz", "plus")
FunSpec.builder("myFunction")
    .addParameter("value", MyClass::class)
    .returns(MyClass::class)
    .addStatement("return this.value.%M(value)", plus)
    .build()

// Prints out
import foo.bar.baz.plus
    
fun myFunction(value: MyClass): MyClass = this.value.plus(value)
```

This doesn't work for operators though, so you'd have to import the extension manually via [`FileSpec.Builder.addImport()`](https://square.github.io/kotlinpoet/1.x/kotlinpoet/com.squareup.kotlinpoet/-file-spec/-builder/add-import/). I think that auto-unfolding `MemberName`s that represent operator functions into operators could be an interesting feature.

In future, please use [Stackoverflow](https://stackoverflow.com/questions/tagged/kotlinpoet) for usage questions. We only use the issue tracker for bug reports and feature requests.

**Comment by devkanro** [comment]
I created a PR for it, check it
