### ISSUE TITLE
class not found

### ISSUE THREAD

**Issue by liujingxing** [square/kotlinpoet#890]
I had a project written in the pure Java language that compiled the `kotlinpoet` project using the `annotationProcessor`, generating a class called `RxHttp`, but when I run the project, the Android studio prompted class was not found.

Compile with `kapt` and everything is fine , What should I do ？

![image](https://user-images.githubusercontent.com/7237396/76160560-2a275280-6166-11ea-88e5-b2f84fdb27d6.png)
![image](https://user-images.githubusercontent.com/7237396/76160606-82f6eb00-6166-11ea-873e-c6503ae64d7b.png)

**Comment by liujingxing** [comment]
I know this is not kotlinpoet's problem, but I want to know how to solve this problem

**Comment by Egorand** [comment]
Please use Stackoverflow.
