### ISSUE TITLE
Use trimIndent() instead of trimMargin() for multiline strings

### ISSUE THREAD

**Issue by Dominaezzz** [square/kotlinpoet#899]
How do I get kotlinpoet to use trimIndent() instead of trimMargin() for multiline strings?

```
// language=json
val json = """
    |{
    |    "type": "m.key.verification.start",
    |    "content": {
    |        "from_device": "BobDevice1",
    |        "transaction_id": "S0meUniqueAndOpaqueString",
    |        "method": "m.sas.v1"
    |    }
    |}
    """.trimMargin()
```

The margins here break the language injection feature. Relevant issue [KT-14864](https://youtrack.jetbrains.com/issue/KT-14864).

**Comment by Egorand** [comment]
There's no option to switch to `trimIndent()`, it's an implementation detail. What's the use-case for using language injection in generated code?

**Comment by Dominaezzz** [comment]
The code is semi-generated as it needs to be slightly modified manually (because edge cases), and it is committed.
In my particular case, I'm generating one-off unit tests for JSON serialization.

I'm hoping for something like.
```
FileSpec.build(....)
   .indent("") // config
   .multilineSetting(Setting.TRIM_INDENT) // Another config, can bike-shed the names later.
   .build()
```

**Comment by JakeWharton** [comment]
I'm opposed to exposing this flag. Would prefer to push on JetBrains to fix the IDE behavior. This problem is far more widespread than the output of this library.
