### ISSUE TITLE
ElementsClassInspector: Annotations wit use site property in intefaces are not picked up

### ISSUE THREAD

**Issue by blaugold** [square/kotlinpoet#900]
The kotlin compiler puts the `syntheticMethodForAnnotations` for properties of interfaces into the `DefaultImpls` class of the interface, but the `ElementsClassInspector` [only looks at the type itself](https://github.com/square/kotlinpoet/blob/e93c861f9e6255f556f8d50fb124ac8e71e4decb/kotlinpoet-classinspector-elements/src/main/kotlin/com/squareup/kotlinpoet/classinspector/elements/ElementsClassInspector.kt#L395). 

Is there a reason not to look into the `DefaultImpls` class?

**Comment by ZacSweers** [comment]
Synthetic elements aren't available in the elements API in general, we have no way to read them.

**Comment by romansl** [comment]
> Synthetic elements aren't available in the elements API in general, we have no way to read them.

You can get it using this code:
```kotlin
        val syntheticClass = element.getEnclosedElements().first {
            it.kind == ElementKind.CLASS && it.simpleName.toString() == "DefaultImpls"
        }
        val syntheticElements = syntheticClass.enclosedElements
```
