### ISSUE TITLE
metadata-specs: make toPropertySpec()/toFunSpec()/toParameterSpec() public?

### ISSUE THREAD

**Issue by gefilte** [square/kotlinpoet#904]
I have an annotation processor currently using the Java libraries for processing and `kotlinpoet` for generating code; I'd like to port it over to `kotlinpoet-metadata` as there are some significant functionality gaps due to the lack of metadata. Thing is, I'm only processing specific annotated methods and properties of a class for handling, so I don't want to take an entire class and wholesale convert it to `KotlinPoet` targets – I'd rather just send specific types for conversion.

I see those extension functions that do this work internally are `private`. Why not make them public?

**Comment by ZacSweers** [comment]
What's the concern with getting the whole class? Members use internal APIs so we're not keen to make them public API.

**Comment by gefilte** [comment]
No big concern, of course I can just cherry-pick what I want out of that. I just figured it was a bunch of wasted cycles.

**Comment by ZacSweers** [comment]
Unless you can show some data that those wasted cycles are nontrivial and
worth avoiding, I don't think this makes sense right now

**Comment by gefilte** [comment]
Got it, thanks
