### ISSUE TITLE
[Kotlinpoet-metadata] How to get annotation on ImmutableKmValueParameter?

### ISSUE THREAD

**Issue by ptdede** [square/kotlinpoet#905]
Hi! How to get annotation list from `ImmutableKmValueParameter`? I can get the boolean value using  `hasAnnotations` but I don't know how to get the annotations. 

using `it.type?.annotations` is returning empty array. :/

**Comment by ZacSweers** [comment]
Please post usage questions (with more details) on stackoverflow with the kotlinpoet tag

**Comment by ptdede** [comment]
posted. https://stackoverflow.com/questions/61435337/getting-annotation-from-constructor-value-parameter-using-kotlinpoet-metadata
Thanks 🙏
