### ISSUE TITLE
What about add some extenison

### ISSUE THREAD

**Issue by VovaStelmashchuk** [square/kotlinpoet#913]
What about add extension for easy work with java classes?

I provide one example here.
Method for get `AnnotationMirror`  

`element.getAnnotationMirror(Nullable::class)`

Code
```kotlin
fun <T : Annotation> Element.getAnnotationMirror(type: KClass<T>): AnnotationMirror? {
    return this.getAnnotation(type.java.name)
}

fun Element.getAnnotation(annotationClass: String): AnnotationMirror? {
    for (annotationMirror in this.annotationMirrors) {
        if (annotationMirror.annotationType.asElement().toString() == annotationClass) {
            return annotationMirror
        }
    }
    return null
}
```

**Comment by Egorand** [comment]
I'm not sure these kinds of methods belong in KotlinPoet, they seem too generic to me.

**Comment by JakeWharton** [comment]
Agreed. They belong in Google's auto/common or a Kotlin version of that library. There's nothing specific to this library.
