### ISSUE TITLE
Support for overriding suspend functions

### ISSUE THREAD

**Issue by shivanshs9** [square/kotlinpoet#914]
I am facing unexpected generated code on overriding suspend functions in the generated class. I understand that's probably because kotlin suspend keyword is transformed to an extra parameter at the end when compiled for JVM, but there's no such need for kotlin output.

#### Input code
```kotlin
abstract suspend fun parse(rawData: String): RequestData
```
#### Expected Output
```kotlin
override suspend fun parse(arg0: String): RequestData {
    ...
}
```
#### Actual Output
```kotlin
import kotlin.coroutines.Continuation

override fun parse(
    arg0: String,
    arg1: Continuation<in RequestData>
  ): Object {
    ...
}
```

### Extra context
On more debugging, I also found that suspending vararg functions are considered as non-varargs functions and the generated code has Continuation as the last parameter, replacing the vararg parameter.

**Comment by Egorand** [comment]
Please attach the snippet of code you use to produce Actual Output, it's unclear which KotlinPoet APIs you're referring to.

**Comment by shivanshs9** [comment]
Ah here it is:
```kotlin
    FunSpec.overriding(
        RequestParser::class.getExecutableElement(
            "parse",
            elementUtils
        )!!
    ).addStatement("...").build()
```

**Comment by Egorand** [comment]
Same issue as in #915. Closing as this is not actionable.
