### ISSUE TITLE
How to get TypeName with correct nullable

### ISSUE THREAD

**Issue by VovaStelmashchuk** [square/kotlinpoet#920]
I try to call `this.asType().asTypeName().isNullable`
`isNullable` - does not work correct.

I found a solution, but it does not look well:
```
fun Element.getTypeNameWithRealNullable(): TypeName {
    val annotation = this.getAnnotationMirror(Nullable::class)
    return annotation?.let {
        this.asType().asTypeName().copy(nullable = true)
    } ?: this.asType().asTypeName().copy(nullable = false)
}

fun <T : Annotation> Element.getAnnotationMirror(type: KClass<T>): AnnotationMirror? {
    return this.getAnnotation(type.java.name)
}
```

Do kotlinpoet has better way for get correct `isNullable`?

**Comment by Egorand** [comment]
`this.asType().asTypeName().copy(nullable = true)` (see the [KDoc](https://square.github.io/kotlinpoet/1.x/kotlinpoet/com.squareup.kotlinpoet/-type-name/copy/)).

Also, please ask usage questions on [Stackoverflow](https://stackoverflow.com/questions/tagged/kotlinpoet), this issue tracker is for bug reports and feature requests only.
