### ISSUE TITLE
Add "val" modifier to KModifier

### ISSUE THREAD

**Issue by dariush-fathie** [square/kotlinpoet#921]
Hi
Thank you for this great library
Please add `val` modifier to `KModifier`

**Comment by Egorand** [comment]
`val` is not a modifier. `KModifier` is based on the following list of [modifiers](https://kotlinlang.org/docs/reference/coding-conventions.html#modifiers). What's your use case?

**Comment by dariush-fathie** [comment]
I just want to generate data class with `val` parameters and the default values

**Comment by Egorand** [comment]
You shouldn't need `val` to be in `KModifier` to achieve that. [Here's](https://github.com/square/kotlinpoet/blob/3fb6a2585861b0833440e294a437db5f7f218ced/kotlinpoet/src/test/java/com/squareup/kotlinpoet/TypeSpecTest.kt#L3242) an example of how this can be done.

**Comment by dariush-fathie** [comment]
Yes it's my answer
Thank you again
Hope you the bests
