### ISSUE TITLE
Incompatibility with library mode

### ISSUE THREAD

**Issue by JakeWharton** [square/kotlinpoet#926]
KotlinPoet currently cannot be used with library mode since it omits optional visibility modifiers. I'm somewhat tempted to just always emit them rather than making this some kind of option. With an option, it means every consumer has to either detect library mode or expose a flag to turn it on which will probably never happen in practice. If we just emit library-mode-compatible code always, it'll always work regardless of the setting. We already do this with return types anyway.

**Comment by Egorand** [comment]
Agree. Is missing visibility modifiers the only issue preventing emitted code to be used with library mode?

**Comment by JakeWharton** [comment]
I think we also have to emit `Unit` which we currently omit. I've only been toying with it in side projects that don't use code gen so I'm not actually sure what (if anything) else is missing.

**Comment by Egorand** [comment]
Should we enable library mode in KP itself and compile a list of issues we bump into?

**Comment by JakeWharton** [comment]
Sounds like a good plan.

**Comment by Egorand** [comment]
List of issues:

- Visibility must be specified explicitly
- Return type must be specified explicitly

**Comment by ShaishavGandhi** [comment]
For library mode should the return type be specified only for public functions or internal/private as well?

**Comment by JakeWharton** [comment]
I would probably just do everything for simplicity. Currently the only return type we omit is `Unit`, right?

**Comment by ShaishavGandhi** [comment]
We also emit return types on expression bodies but not sure if we can do anything about that unless we do some type inference as discussed in #407.

From the tests:
```kotlin
@Test fun whenReturn() {
    val taco = TypeSpec.classBuilder("Taco")
        .addFunction(FunSpec.builder("toppingPrice")
            .addParameter("topping", String::class)
            .beginControlFlow("return when(topping)")
            .addStatement("%S -> 1", "beef")
            .addStatement("%S -> 2", "lettuce")
            .addStatement("%S -> 3", "cheese")
            .addStatement("else -> throw IllegalToppingException(topping)")
            .endControlFlow()
            .build())
        .build()
    assertThat(toString(taco)).isEqualTo("""
        |package com.squareup.tacos
        |
        |import kotlin.String
        |
        |class Taco {
        |  fun toppingPrice(topping: String) = when(topping) {
        |    "beef" -> 1
        |    "lettuce" -> 2
        |    "cheese" -> 3
        |    else -> throw IllegalToppingException(topping)
        |  }
        |}
        |""".trimMargin())
  }
```

**Comment by Egorand** [comment]
Seems like `public` and `Unit` are the only things required by the library mode, and this is covered by #932 and #933. Will close this issue and we'll file new ones if we encounter additional requirements.
