### ISSUE TITLE
Consecutive blank lines with top level property

### ISSUE THREAD

**Issue by btrautmann** [square/kotlinpoet#941]
I'm noticing that when creating a top-level property in a file, two blank lines are output below the property, causing detekt to fail with a `NoConsecutiveBlankLines` violation.

Sample `FileSpec`:
```
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.PropertySpec

val spec = FileSpec.builder("com.example.foo", "Test")
  .addProperty(
    PropertySpec.builder("MyProperty", String::class.java)
      .initializer(
        CodeBlock.builder()
            .beginControlFlow("if (1 + 1 == 2)")
            .addStatement("Expected")
            .endControlFlow()
            .beginControlFlow("else")
            .addStatement("Unexpected")
            .endControlFlow()
            .build()
      ).build()
  ).build()
```

Results in:
```
val equals = """
    |package com.example.foo
    |
    |import java.lang.String
    |
    |val MyProperty: String = if (1 + 1 == 2) {
    |  Expected
    |}
    |else {
    |  Unexpected
    |}
    |
    | <-- Extra line. Removing this causes `equals` to be `false`
""".trimMargin() == spec.toString()
println(equals) <-- Prints `true`
```

I don't think we should ever have consecutive blank lines.

**Comment by Egorand** [comment]
Thanks for reporting, please feel free to send us a PR.

That said, we usually discourage people from running code quality tools over KotlinPoet's output. Generated code is semantically different from source code, so you shouldn't expect it to match the levels of quality that you would expect from code written by a programmer. It should either live in `build/generated` or be added to the code quality tool's excludes.

**Comment by btrautmann** [comment]
@Egorand Thanks, and yeah, in most cases I do agree with you. In our particular case, we are using KotlinPoet to generate some actual source to help alleviate the pain of some boilerplate code needing to be written for each new "mini-feature-module". Totally understand that it's an unorthodox usage of generated code. If I have some time to look into the reason for the extra line, I'll give a contribution a shot!

**Comment by JakeWharton** [comment]
In that case you might want to run ktfmt or ktlint's formatter on the output as part of the generation process.

BTW you can replace `endControlFlow().beginControlFlow()` calls with `nextControlFlow()`

**Comment by btrautmann** [comment]
@JakeWharton That's a great idea, thanks. I'll try to incorporate that into the generation process. And thanks for that control flow tip :) Still new to KotlinPoet (have been loving it by the way)!

**Comment by btrautmann** [comment]
It's been over 3 years and I can say with a fair level of confidence that I will never come back to this to address it. Because it's such a minor issue, and I think @JakeWharton was correct to point out that if you're producing source code using Kotlin Poet you probably should just run a formatter on the code post-generation, I'm going to close this issue.

**Comment by JakeWharton** [comment]
If you don't mind I'd like to keep it open because it is an issue and _could_ be fixed. You don't have to fix it. We should get to it eventually, or more likely someone else will find the time and send a PR.

You can unsubscribe to not be notified of future comments. Or if you don't want it to show up in your issue list I can create a new one with the contents.
