### ISSUE TITLE
Properties with custom getter are still "merged" into primary constructor properties 

### ISSUE THREAD

**Issue by enjoydambience** [square/kotlinpoet#942]
When a property in a class
- Is initialized with a _same name_ primary constructor parameter
- has a getter

It produces wrong code (tries to merge into a primary constructor property).

Miminal example:
```kotlin
TypeSpec.classBuilder("Greeter")
    .primaryConstructor(FunSpec.constructorBuilder()
        .addParameter("name", String::class)
        .build()
    )
    .addProperty(PropertySpec.builder("name", String::class)
        .initializer("name")
        .getter(FunSpec.getterBuilder()
            .addStatement("return field")
            .build()
        )
        .build()
    ).build()
```
Which produces the output
```kotlin
class Greeter(
  val name: kotlin.Stringget() = field

)
```

Tested in version 1.6.0

**Comment by Egorand** [comment]
Merging a property and a primary constructor parameter, where the property's `initializer` matches the name of the parameter, is not a bug, it's a feature, as described in the [docs](https://square.github.io/kotlinpoet/#constructors).

What's the expected output in this case? Are both `initializer` and a custom getter required for the property?

**Comment by JakeWharton** [comment]
Yeah the merging logic is just broken. It shouldn't apply when there's a custom getter or setter.

**Comment by enjoydambience** [comment]
It also doesn't put a space between `String` and `get`, and still wouldn't be right even if it did.

A correct output could look like this
```kotlin
class Greeter(
    name: kotlin.String
) {
   val name: kotlin.String = name
       get() = field
}
```
