### ISSUE TITLE
Disallow setter on non-mutable property

### ISSUE THREAD

**Issue by enjoydambience** [square/kotlinpoet#945]
A property that isn't mutable can still have a setter. This shouldn't be allowed.

Another option is to implicitly make a property mutable whenever a setter is included.

**Comment by JakeWharton** [comment]
We can do the former. Silently changing behavior is not appealing to me. Also, for what it's worth, the compiler still has our backs here. We don't aim for 100% enforcement of semantics, but this is an easy one to validate and it will result in a stacktrace that points directly at the problem so I'm supportive.

**Comment by JakeWharton** [comment]
Feel free to send a PR + test.
