### ISSUE TITLE
Reduce API bloat

### ISSUE THREAD

**Issue by enjoydambience** [square/kotlinpoet#956]
With the current API:
- `TypeSpec` covers all classes, objects, interfaces, enums, and annotations, even though these have properties that don't pertain to other types.
- Similarly, there are also multiple FunSpecs (regular, getter, setter, constructor) that each render differently.
- All `KModifier`s can be apply to almost everything even when they shouldn't, and are sometimes applied in an inconsistent manner (#939).

This makes the API harder to use as many functions are put behind preconditions. Maintaining code is harder due requiring having one Spec class simultaneously implement multiple forms, which could perhaps better be done using polymorphism. (many `if` statements and preconditions is a code smell).

Here are some possible suggestions on how to improve this:
- Have more Specs/Builders for different kinds of specs. Common behaviors/properties among specs could be expressed through common interfaces instead of putting them all into one type; builders could use the abstract builder pattern (perhaps similarly to how `Taggable` and `OriginatingElementsHolder` is currently done). This will (maybe?) be backwards incompatible.
- For a backwards compatible change that affects only the API; provide separate interfaces for each kind of TypeSpec/FunSpec (like `ClassBuilder`, `EnumBuilder`, etc) that expose a subset of the a builders' API, that the current Builders implement. 
   - This could also be migration step if there were to be a backwards incompatible change.
- For modifiers, make them a sealed class (hierarchy) instead of an enum. Each modifier can then implement interface(s) declaring where it can be applied to, which the builders receive, something like: 
```kotlin
object TailRec : Modifier(), AppliesToFun
---
fun addModifiers(vararg modifiers: AppliesToFun) {...}
```

What do you think?

**Comment by Egorand** [comment]
I like the suggestions around introducing more specific Spec and Builder interfaces to make it easier to navigate the APIs. Agree that it would also help make the library more maintainable by reducing the amount of special-casing in the logic around different flavours of existing Specs. Backwards compatibility is definitely a concern here, so we should definitely go with introducing new API and deprecating existing ones. We can clean it up in 2.0.

As for hierarchical `KModifier` API, my concern is that we might end up with a complicated hierarchy and a lot of unnecessary marker interfaces. Would love to be proven wrong, if it's something you wanna build - it may be easier to sell with a PR.

A general point about the API is that KotlinPoet is not trying to emulate the Kotlin compiler, which is the ultimate source of truth for the correctness of the generated code. I'd welcome improvements that make the API more intuitive and the codebase easier to maintain, but only as long as we don't overcomplicate the library by adding all kinds of compiler validations.

**Comment by JakeWharton** [comment]
Just to record my preference I'm opposed to the modifier thing and weakly opposed to different builder types. The Kotlin compiler ultimately validates what is allowed and our goal should be to strike a usability balance in a pragmatic API, not to model the entire syntax perfectly. It's especially important since we don't want to have to add a new API every time the language adds a new feature.

**Comment by enjoydambience** [comment]
I agree it would not be practical to try to emulate the compiler entirely, however KotlinPoet already performs many of these checks. A reasonable balance can be found.

In my view:

- It would likely be enough to split TypeSpec into ClassSpec, InterfaceSpec, and ObjectSpec, with a common supertype between these, and maybe additionally EnumSpec (a subtype of ClassSpec?). More specific variants can fit into those types.
- FunSpec should be split into regular functions and constructors; and maybe additionally accessors (get/set).
- For `KModifier`, it would make more sense to just make better use of the existing `checkTarget` mechanism, and add more "granular" targets to check against. This could probably group together some of existing checks, and might even be backwards compatible, except for changing some exception messages. I might make a PR that applies this.

**Comment by JakeWharton** [comment]
I am definitely opposed to the first two bullets and would require convincing of their value.

**Comment by enjoydambience** [comment]
I think there are more than enough distinctions between variants of specs to warrant splitting it into multiple classes. Right now these distinctions are represented by lots of checks, which is hard to understand and maintain. From inspection, some checks aren't fully correct, and some are repeated multiple times.
However, it all comes down to the fact that there is one class being used represent multiple dissimilar roles (violating the single responsibility principle). Polymorphism is a better substitute for many if statements.

---

I have since realized that it would backwards compatible to make internal subclasses of the current Spec/Builder types just for performing checks. I can make a PR demonstrating this.

---

Here is a (likely non-exhaustive) list of distinctions between types, currently implemented using checks:

### TypeSpec:
**In common**:
  - KDoc, modifiers, and annotations (many other specs have these)
  - Member functions/properties
  - Inner types
  - Super interfaces

**Not in common**:

Class & object (maybe combine these):
  - Superclass & superclass constructor calling
  - Initializer blocks
  - Interface delegation

Class:
 - Constructors
 - Type variables

Interface:
 - Type variables
 - Must have all public members

Enums, annotation classes, Fun interfaces, and anonymous classes, all have further restrictions.

### FunSpec:
**In common**:
- KDoc, modifiers, and annotations (many other specs have these)
- May have function body

**Not in common**:
Regular functions:
- Parameters
- Type parameters
- Receiver
- Return type
- be inline (reified type parameter, crossinline and noinline modifiers)

Constructors:
- Parameters
- Calling other constructors

Getter:
- (implicit) return type

Setter:
- Optional single parameter

### Other notes
- The type of the parameter must be specified twice when making properties. Making Setter it's own spec would remove this requirement.
- This would also facilitate making primary constructor properties easier to do. It's simple in the language, but very cumbersome in KotlinPoet (this could be a separate issue).
- Adding a new type would simply require making a (sub)class, and would integrate into any user code using the superclass.

**Comment by JakeWharton** [comment]
Yeah I just don't see any value in doing this work and you've made no real arguments for it aside from single-responsibility principle (which I don't buy as important here since this is not a project that's undergoing constant development). The fact that you can, say, add an enum constant to a non-enum type in the API isn't a problem for me. If anything, the changes in Kotlin 1.4 have detailed that we should probably have fewer checks and rely on the Kotlin compiler more as the canonical validator of what's correct.

**Comment by swankjesse** [comment]
My problem with this approach is that language features don’t roll up into the type hierarchy. For example: 

 * On what `*Spec` does `typeVariables` go? Classes have these; objects don’t.
 * On what `*Spec` does `superclass` go? Both classes and objects have these.

**Comment by enjoydambience** [comment]
Some more comments:

This issue originated from my observation that the checks inside `TypeSpec.Builder.build` should be cleaned up; and possibly by extension the API. To me it seems the root problem is that the Specs are trying to be too many things at once. There might be other ways to address this.

If there were to be an inheritance hierarchy, one way to make it work is to have a superclass support everything but as `protected` members, but have the subclasses selectively expose methods as `public` members.

Right now there already exists a large number of checks that KotlinPoet do that the compiler could otherwise do. 
At what level do we perform semantics checks in the code, and when is it left to the compiler?

**Comment by swankjesse** [comment]
I think our stance is that fewer types is easier because there's fewer decisions: you don't need to decide if your helper method takes a TypeSpec, ClassSpec, ObjectSpec, or whatever.

I think this is great! And it's okay that you want more types that are each more focused.

No action to take on this.
