### ISSUE TITLE
Checks should use consistent exception types.

### ISSUE THREAD

**Issue by enjoydambience** [square/kotlinpoet#959]
Right now some checks use`check`/`IllegalStateException`, while others use `require`/`IllegalArugmentException`. It should be all one or the other, probably `IllegalArgumentException`.

**Comment by JakeWharton** [comment]
From a quick sampling it looks like we're using each correctly. `require` is for validating arguments, `check` is for validating state.

**Comment by JakeWharton** [comment]
Do you have a specific example where one is wrong?

**Comment by enjoydambience** [comment]
I guess it depends on the interpretation of what counts as "state" and what counts as "arguments".

However, it does seem a bit inconsistent -- the most obvious example being in `TypeSpec.Builder.build`: checks relating to the "variant" of the type is state, modifiers of contents count as arguments, needing abstract functions in interfaces is `require`, checking properties of inner contents is sometimes `require` and sometimes `check`, etc.

It would be simpler to make everything `require` since all these checks relate to arguments given to a builder, or make a clearer distinction as to what counts as "arguments" vs "state".
