### ISSUE TITLE
Exclude default imports from FileSpec

### ISSUE THREAD

**Issue by nielsvanvelzen** [square/kotlinpoet#960]
A lot of classes inside of the `kotlin.*` package are imported automatically by Kotlin. (See [Packages and Imports](https://kotlinlang.org/docs/reference/packages.html#default-imports)).

KotlinPoet still adds import statements for these packages. This is unnecessary in most (or all?) scenarios. To reduce the generated code size the default imports could be ignored in the FileSpec class when generating the code.

**Comment by Egorand** [comment]
See #361, #763

**Comment by nielsvanvelzen** [comment]
Thanks for the reply. I didn't find those issues as I only searched for open issues (my bad!)
