### ISSUE TITLE
Support for Higher Order Functions

### ISSUE THREAD

**Issue by rgbrizzlehizzle** [square/kotlinpoet#964]
As far as I can tell, there isn't an established way to declare higher order functions using KotlinPoet.  Since they are more a syntactic sugar than an explicit necessity, wanted to poll the dev base on if this is a feature people want.  Also I could just be wrong and it's totally doable already and I just missed it in the docs 😅

**Comment by JakeWharton** [comment]
You can use `LambdaTypeName`: https://github.com/square/kotlinpoet/blob/master/kotlinpoet/src/main/java/com/squareup/kotlinpoet/TypeName.kt#L494

Anything not covered by that?

**Comment by rgbrizzlehizzle** [comment]
Ahh yep that'll do it, thanks!! Spent like 10 minutes looking for "higher order" and it was right in front of me using a different terminology... classic :D
