### ISSUE TITLE
addStatement creating new line in the middle of a string

### ISSUE THREAD

**Issue by rgbrizzlehizzle** [square/kotlinpoet#968]
For example

```
addStatement("val exceptionResponse = %T(cause.message ?: \"%L\")", ExceptionResponse, default)
```
where `ExceptionResponse` is a `ClassName` and default is of type `String`

KotlinPoet will output the following 

```
val exceptionResponse = ExceptionResponse(cause.message ?: "Requested resource could not be
          found")
```
which cannot be interpreted by the kotlin compiler

**Comment by JakeWharton** [comment]
Change `\"%L\"` to `%S` which should correct the problem.

**Comment by rgbrizzlehizzle** [comment]
WOW is there world record for fastest ticket open and close 

Yep that was it, thank you sir
