### ISSUE TITLE
Idea: A meta-kotlinpoet code generator cli - Input raw kotlin and get kotlinpoet code

### ISSUE THREAD

**Issue by AdityaAnand1** [square/kotlinpoet#972]
A cli command or a method that takes in a kotlin file or snippet and outputs the Kotlinpoet code required to in turn generate the input code itself.

Does this sound feasible?  What would it take to build something like this?

**Comment by JakeWharton** [comment]
Possible, but probably not in scope for this project. You would need to use UAST to be able to resolve types for things like extensions becoming proper member references.

**Comment by ZacSweers** [comment]
You could write a UastClassInspector for KotlinPoet-metadata. It already has elements and reflective versions right now

**Comment by AdityaAnand1** [comment]
Got it, will check it out. Thanks 👍
