### ISSUE TITLE
Modified keywords not escape when generating enums.

### ISSUE THREAD

**Issue by oldergod** [square/kotlinpoet#991]
For instance, KP will generate the following and this doesn't compile because of `open`.
```kt
enum class Sort {
  open,
  sort
}
```

**Comment by Egorand** [comment]
Looking into this more closely. `open` is a modifier keyword, it only acts as a keyword in specific contexts, and can be used as an identifier outside of those contexts (see https://kotlinlang.org/docs/reference/keyword-reference.html#modifier-keywords). E.g. this snippet [compiles fine](https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS40LjEwIiwicGxhdGZvcm0iOiJqYXZhIiwiYXJncyI6IiIsImpzQ29kZSI6IiIsIm5vbmVNYXJrZXJzIjp0cnVlLCJ0aGVtZSI6ImlkZWEiLCJjb2RlIjoiLyoqXG4gKiBZb3UgY2FuIGVkaXQsIHJ1biwgYW5kIHNoYXJlIHRoaXMgY29kZS4gXG4gKiBwbGF5LmtvdGxpbmxhbmcub3JnIFxuICovXG5cbmVudW0gY2xhc3MgRm9vIHtcbiAgICBvcGVuLFxufVxuXG5mdW4gbWFpbigpIHtcbiAgICBwcmludGxuKFwiSGVsbG8sIHdvcmxkISEhXCIpXG59In0=):
```kotlin
enum class Foo {
  open,
}
```
Sure you're getting compilation errors for that snippet of code?

**Comment by oldergod** [comment]
Oh right, it fails in Wire because there's a payload with the tag, it gets generated as

```
enum class Foo : WireEnum {
  open(0)
}
```
and this doesn't compile.

**Comment by Egorand** [comment]
Interesting, guess we should escape soft keywords as well.
