### ISSUE TITLE
Snapshots published from pull requests?

### ISSUE THREAD

**Issue by Egorand** [square/kotlinpoet#998]
Just noticed this on https://github.com/square/kotlinpoet/pull/997:

<img width="924" alt="image" src="https://user-images.githubusercontent.com/1186186/96027737-4d199380-0e26-11eb-9d3c-0ca1200416c8.png">

Looking at the [CI job](https://github.com/square/kotlinpoet/pull/997/checks?check_run_id=1254894934), it seems that the snapshot is still published from master, but still shouldn't publish a snapshot before merging the PR.

Could it be related to https://github.com/square/kotlinpoet/pull/996/files?

**Comment by ZacSweers** [comment]
it's possible, if the check is just that it's "not a pull_request" event rather than also gating on the branch and push event type

**Comment by Egorand** [comment]
#1008 makes this issue obsolete
